---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AccessoryDescription: Instance  
AccessoryDescription = {}

---@return Instance
function AccessoryDescription:GetAppliedInstance() end
---@field AccessoryType AccessoryType
---@field AssetId int64
---@field Instance Instance
---@field IsLayered bool
---@field Order int
---@field Position Vector3
---@field Puffiness float
---@field Rotation Vector3
---@field Scale Vector3
