---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AccountService: Instance  
AccountService = {}

---@return bool
function AccountService:DeviceAccessTokenAvailable() end


---@return bool
function AccountService:DeviceIntegrityAvailable() end

---@param data string
---@return string
function AccountService:GetDeviceIntegrityToken(data) end


---@return string
function AccountService:GetCredentialsHeaders() end


---@return string
function AccountService:GetDeviceAccessToken() end

---@param data string
---@return string
function AccountService:GetDeviceIntegrityTokenYield(data) end

