---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Accoutrement: Instance  
Accoutrement = {}

---@field AttachmentForward Vector3
---@field AttachmentPoint CFrame
---@field AttachmentPos Vector3
---@field AttachmentRight Vector3
---@field AttachmentUp Vector3
---@field BackendAccoutrementState int
