---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AchievementService: Instance  
AchievementService = {}

---@return bool
function AchievementService:IsAvailable() end

---@param achievementName string
---@return bool
function AchievementService:GrantAchievement(achievementName) end

---@param achievementName string
---@return bool
function AchievementService:HasAchieved(achievementName) end

