---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Actor: Model  
Actor = {}
---@param topic string
---@param function Function
---@return RBXScriptConnection
function Actor:BindToMessage(topic, function) end

---@param topic string
---@param function Function
---@return RBXScriptConnection
function Actor:BindToMessageParallel(topic, function) end

---@param topic string
---@param message Tuple
function Actor:SendMessage(topic, message) end

