---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum AdEventType  
AdEventType = {
  RewardedAdLoaded = 3
, RewardedAdGrant = 4
, RewardedAdUnloaded = 5
, VideoLoaded = 0
, VideoRemoved = 1
, UserCompletedVideo = 2
}
