---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AdGui: SurfaceGuiBase  
AdGui = {}
---@param eventType AdUIEventType
function AdGui:HandleLuaUIEvent(eventType) end
---@field AdShape AdShape
---@field EnableVideoAds bool
---@field FallbackImage Content
---@field Status AdUnitStatus
