---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AdService: Instance  
AdService = {}

---@return Tuple
function AdService:GetAdTeleportInfo() end


---@return Array
function AdService:GetReportAdInfo() end


function AdService:HideEudsaDisclosure() end

---@param adTeleportMethod AdTeleportMethod
function AdService:ReturnToPublisherExperience(adTeleportMethod) end


function AdService:SetAdGuiInteractivityHandlerInitialized() end


function AdService:ShowVideoAd() end

