---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum AdTeleportMethod  
AdTeleportMethod = {
  Undefined = 0
, PortalForward = 1
, InGameMenuBackButton = 2
, UIBackButton = 3
}
