---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum AdUIEventType  
AdUIEventType = {
  AdLabelClicked = 0
, VolumeButtonClicked = 1
, FullscreenButtonClicked = 2
, PlayButtonClicked = 3
, PauseButtonClicked = 4
, CloseButtonClicked = 5
}
