---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AirController: ControllerBase  
AirController = {}

---@field BalanceMaxTorque float
---@field BalanceSpeed float
---@field LinearImpulse Vector3
---@field MaintainAngularMomentum bool
---@field MaintainLinearMomentum bool
---@field MoveMaxForce float
---@field TurnMaxTorque float
---@field TurnSpeedFactor float
