---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum AlignType  
AlignType = {
  PrimaryAxisParallel = 2
, PrimaryAxisPerpendicular = 3
, PrimaryAxisLookAt = 4
, AllAxes = 5
, Parallel = 0
, Perpendicular = 1
}
