---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AlignPosition: Constraint  
AlignPosition = {}

---@field ApplyAtCenterOfMass bool
---@field ForceLimitMode ForceLimitMode
---@field ForceRelativeTo ActuatorRelativeTo
---@field MaxAxesForce Vector3
---@field MaxForce float
---@field MaxVelocity float
---@field Mode PositionAlignmentMode
---@field Position Vector3
---@field ReactionForceEnabled bool
---@field Responsiveness float
---@field RigidityEnabled bool
