---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AlignOrientation: Constraint  
AlignOrientation = {}

---@field AlignType AlignType
---@field CFrame CFrame
---@field LookAtPosition Vector3
---@field MaxAngularVelocity float
---@field MaxTorque float
---@field Mode OrientationAlignmentMode
---@field PrimaryAxis Vector3
---@field PrimaryAxisOnly bool
---@field ReactionTorqueEnabled bool
---@field Responsiveness float
---@field RigidityEnabled bool
---@field SecondaryAxis Vector3
