---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum AnalyticsProgressionStatus  
AnalyticsProgressionStatus = {
  Default = 0
, Begin = 1
, Complete = 2
, Abandon = 3
, Fail = 4
}
