---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum AnalyticsLogLevel  
AnalyticsLogLevel = {
  Trace = 0
, Debug = 1
, Information = 2
, Warning = 3
, Error = 4
, Fatal = 5
}
