---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AnalyticsService: Instance  
AnalyticsService = {}
---@param player Instance
---@param eventCategory string
---@param customData Variant
function AnalyticsService:FireCustomEvent(player, eventCategory, customData) end

---@param category string
---@param value Variant
function AnalyticsService:FireEvent(category, value) end

---@param player Instance
---@param itemName string
---@param economyAction AnalyticsEconomyAction
---@param itemCategory string
---@param amount int
---@param currency string
---@param location Variant
---@param customData Variant
function AnalyticsService:FireInGameEconomyEvent(player, itemName, economyAction, itemCategory, amount, currency, location, customData) end

---@param player Instance
---@param logLevel AnalyticsLogLevel
---@param message string
---@param debugInfo Variant
---@param customData Variant
function AnalyticsService:FireLogEvent(player, logLevel, message, debugInfo, customData) end

---@param player Instance
---@param category string
---@param progressionStatus AnalyticsProgressionStatus
---@param location Variant
---@param statistics Variant
---@param customData Variant
function AnalyticsService:FirePlayerProgressionEvent(player, category, progressionStatus, location, statistics, customData) end

---@param player Player
---@param flowType AnalyticsEconomyFlowType
---@param currencyType string
---@param amount float
---@param endingBalance float
---@param transactionType string
---@param itemSku string
---@param customFields Dictionary
function AnalyticsService:LogEconomyEvent(player, flowType, currencyType, amount, endingBalance, transactionType, itemSku, customFields) end

---@param player Player
---@param funnelName string
---@param funnelSessionId string
---@param step int
---@param stepName string
---@param customFields Dictionary
function AnalyticsService:LogFunnelStepEvent(player, funnelName, funnelSessionId, step, stepName, customFields) end

---@param player Player
---@param step int
---@param stepName string
---@param customFields Dictionary
function AnalyticsService:LogOnboardingFunnelStepEvent(player, step, stepName, customFields) end

---@param player Player
---@param progressionPathName string
---@param level int
---@param levelName string
---@param customFields Dictionary
function AnalyticsService:LogProgressionCompleteEvent(player, progressionPathName, level, levelName, customFields) end

---@param player Player
---@param progressionPathName string
---@param status AnalyticsProgressionType
---@param level int
---@param levelName string
---@param customFields Dictionary
function AnalyticsService:LogProgressionEvent(player, progressionPathName, status, level, levelName, customFields) end

---@param player Player
---@param progressionPathName string
---@param level int
---@param levelName string
---@param customFields Dictionary
function AnalyticsService:LogProgressionFailEvent(player, progressionPathName, level, levelName, customFields) end

---@param player Player
---@param progressionPathName string
---@param level int
---@param levelName string
---@param customFields Dictionary
function AnalyticsService:LogProgressionStartEvent(player, progressionPathName, level, levelName, customFields) end
---@field ApiKey string
