---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum AnalyticsEconomyTransactionType  
AnalyticsEconomyTransactionType = {
  IAP = 0
, Shop = 1
, Gameplay = 2
, ContextualPurchase = 3
, TimedReward = 4
, Onboarding = 5
}
