---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AngularVelocity: Constraint  
AngularVelocity = {}

---@field AngularVelocity Vector3
---@field MaxTorque float
---@field ReactionTorqueEnabled bool
---@field RelativeTo ActuatorRelativeTo
