---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AnimationFromVideoCreatorStudioService: Instance  
AnimationFromVideoCreatorStudioService = {}

---@return bool
function AnimationFromVideoCreatorStudioService:IsAgeRestricted() end

---@param progressCallback Function
---@return string
function AnimationFromVideoCreatorStudioService:CreateAnimationByUploadingVideo(progressCallback) end


---@return string
function AnimationFromVideoCreatorStudioService:ImportVideoWithPrompt() end

