---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AnimationTrack: Instance  
AnimationTrack = {}
---@param speed float
function AnimationTrack:AdjustSpeed(speed) end

---@param weight float
---@param fadeTime float
function AnimationTrack:AdjustWeight(weight, fadeTime) end

---@param name string
---@return RBXScriptSignal
function AnimationTrack:GetMarkerReachedSignal(name) end

---@param keyframeName string
---@return double
function AnimationTrack:GetTimeOfKeyframe(keyframeName) end

---@param fadeTime float
---@param weight float
---@param speed float
function AnimationTrack:Play(fadeTime, weight, speed) end

---@param fadeTime float
function AnimationTrack:Stop(fadeTime) end
---@field Animation Animation
---@field IsPlaying bool
---@field Length float
---@field Looped bool
---@field Priority AnimationPriority
---@field Speed float
---@field TimePosition float
---@field WeightCurrent float
---@field WeightTarget float
