---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum AnimationPriority  
AnimationPriority = {
  Core = 1000
, Idle = 0
, Movement = 1
, Action = 2
, Action2 = 3
, Action3 = 4
, Action4 = 5
}
