---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AnimationClip: Instance  
AnimationClip = {}

---@field Guid string
---@field GuidBinaryString BinaryString
---@field Loop bool
---@field Priority AnimationPriority
