---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AnimationClipProvider: Instance  
AnimationClipProvider = {}
---@param assetId Content
---@return AnimationClip
function AnimationClipProvider:GetAnimationClip(assetId) end

---@param assetId int64
---@param useCache bool
---@return AnimationClip
function AnimationClipProvider:GetAnimationClipById(assetId, useCache) end


---@return Dictionary
function AnimationClipProvider:GetMemStats() end

---@param animationClip AnimationClip
---@return Content
function AnimationClipProvider:RegisterActiveAnimationClip(animationClip) end

---@param animationClip AnimationClip
---@return Content
function AnimationClipProvider:RegisterAnimationClip(animationClip) end

---@param assetId Content
---@return AnimationClip
function AnimationClipProvider:GetAnimationClipAsync(assetId) end

---@param userId int64
---@return Instance
function AnimationClipProvider:GetAnimations(userId) end

---@param assetId Content
---@return ClipEvaluator
function AnimationClipProvider:GetClipEvaluatorAsync(assetId) end

