---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AnimationStreamTrack: Instance  
AnimationStreamTrack = {}
---@param weight float
---@param fadeTime float
function AnimationStreamTrack:AdjustWeight(weight, fadeTime) end


---@return bool
function AnimationStreamTrack:GetActive() end


---@return Tuple
function AnimationStreamTrack:GetTrackerData() end

---@param fadeTime float
---@param weight float
function AnimationStreamTrack:Play(fadeTime, weight) end

---@param fadeTime float
function AnimationStreamTrack:Stop(fadeTime) end

---@param paused bool
function AnimationStreamTrack:TogglePause(paused) end
---@field Animation TrackerStreamAnimation
---@field FACSDataLod FACSDataLod
---@field IsPlaying bool
---@field Priority AnimationPriority
---@field WeightCurrent float
---@field WeightTarget float
