---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AnimationRigData: Instance  
AnimationRigData = {}
---@param humanoid Instance
---@return bool
function AnimationRigData:LoadFromHumanoid(humanoid) end
---@field articulatedJoint BinaryString
---@field label BinaryString
---@field name BinaryString
---@field parent BinaryString
---@field postTransform BinaryString
---@field preTransform BinaryString
---@field transform BinaryString
