---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AnimationController: Instance  
AnimationController = {}

---@return Array
function AnimationController:GetPlayingAnimationTracks() end

---@param animation Animation
---@return AnimationTrack
function AnimationController:LoadAnimation(animation) end

