---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Animator: Instance  
Animator = {}
---@param motors Variant
function Animator:ApplyJointVelocities(motors) end


---@return Array
function Animator:GetPlayingAnimationTracks() end


---@return Array
function Animator:GetPlayingAnimationTracksCoreScript() end

---@param animation Animation
---@return AnimationTrack
function Animator:LoadAnimation(animation) end

---@param animation Animation
---@return AnimationTrack
function Animator:LoadAnimationCoreScript(animation) end

---@param animation TrackerStreamAnimation
---@return AnimationStreamTrack
function Animator:LoadStreamAnimation(animation) end

---@param animation TrackerStreamAnimation
---@param player Player
---@return AnimationStreamTrack
function Animator:LoadStreamAnimationForSelfieView_deprecated(animation, player) end

---@param callback Function
function Animator:RegisterEvaluationParallelCallback(callback) end

---@param deltaTime float
function Animator:StepAnimations(deltaTime) end

---@param otherAnimator Animator
function Animator:SynchronizeWith(otherAnimator) end
---@field EvaluationThrottled bool
---@field PreferLodEnabled bool
---@field RootMotion CFrame
---@field RootMotionWeight float
