---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AnimationConstraint: Constraint  
AnimationConstraint = {}

---@field C0 CFrame
---@field C1 CFrame
---@field IsKinematic bool
---@field MaxForce float
---@field MaxTorque float
---@field Part0 BasePart
---@field Part1 BasePart
---@field Transform CFrame
