---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AppLifecycleObserverService: Instance  
AppLifecycleObserverService = {}

---@return bool
function AppLifecycleObserverService:IsDidDetachSupported() end

