---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum AppShellFeature  
AppShellFeature = {
  None = 0
, Chat = 1
, AvatarEditor = 2
, GamePage = 3
, HomePage = 4
, More = 5
, Landing = 6
}
