---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ArcHandles: HandlesBase  
ArcHandles = {}

---@field Axes Axes
---@field MouseButton1DownConnectionCount int
---@field MouseButton1UpConnectionCount int
---@field MouseDragConnectionCount int
---@field MouseEnterConnectionCount int
---@field MouseLeaveConnectionCount int
