---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AssetDeliveryProxy: Instance  
AssetDeliveryProxy = {}

---@field Interface string
---@field Port int
---@field StartServer bool
