---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AssetService: Instance  
AssetService = {}
---@param serializedInstance string
---@return Instance
function AssetService:DeserializeInstance(serializedInstance) end

---@param bundleId int64
---@return Dictionary
function AssetService:GetBundleDetailsSync(bundleId) end

---@param function Function
function AssetService:RegisterUGCValidationFunction(function) end

---@param textureId Content
---@return EditableImage
function AssetService:CreateEditableImageAsync(textureId) end

---@param meshId Content
---@return EditableMesh
function AssetService:CreateEditableMeshAsync(meshId) end

---@param meshPart Instance
---@return EditableMesh
function AssetService:CreateEditableMeshFromPartAsync(meshPart) end

---@param meshId Content
---@return EditableMesh
function AssetService:CreateEditableMeshStripSkinningAsync(meshId) end

---@param meshId Content
---@param options Dictionary
---@return MeshPart
function AssetService:CreateMeshPartAsync(meshId, options) end

---@param placeName string
---@param templatePlaceID int64
---@param description string
---@return int64
function AssetService:CreatePlaceAsync(placeName, templatePlaceID, description) end

---@param player Instance
---@param placeName string
---@param templatePlaceID int64
---@param description string
---@return int64
function AssetService:CreatePlaceInPlayerInventoryAsync(player, placeName, templatePlaceID, description) end

---@param packageAssetId int64
---@return Array
function AssetService:GetAssetIdsForPackage(packageAssetId) end

---@param idList Array
---@return Array
function AssetService:GetAudioMetadataAsync(idList) end

---@param bundleId int64
---@return Dictionary
function AssetService:GetBundleDetailsAsync(bundleId) end

---@param creationID int64
---@return int64
function AssetService:GetCreatorAssetID(creationID) end


---@return Instance
function AssetService:GetGamePlacesAsync() end

---@param player Player
---@param instance Instance
---@param assetType AssetType
---@return Tuple
function AssetService:PromptCreateAssetAsync(player, instance, assetType) end

---@param player Player
---@param progressCallback Function
---@return Tuple
function AssetService:PromptImportAnimationClipFromVideoAsync(player, progressCallback) end


function AssetService:SavePlaceAsync() end

---@param searchParameters AudioSearchParams
---@return AudioPages
function AssetService:SearchAudio(searchParameters) end

