---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AssetPatchSettings: Instance  
AssetPatchSettings = {}

---@field ContentId string
---@field OutputPath string
---@field PatchId string
