---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AssetImportService: Instance  
AssetImportService = {}

---@return Dictionary
function AssetImportService:GetAllPresets() end

---@param name string
---@return Dictionary
function AssetImportService:GetPreset(name) end

---@param name string
function AssetImportService:RemovePreset(name) end

---@param name string
---@param preset Dictionary
---@return bool
function AssetImportService:SavePreset(name, preset) end

---@param filePath string
---@return AssetImportSession
function AssetImportService:StartSessionWithPath(filePath) end


---@return string
function AssetImportService:PickFileWithPrompt() end


---@return Array
function AssetImportService:PickMultipleFilesWithPrompt() end


---@return AssetImportSession
function AssetImportService:StartSessionWithPrompt() end

