---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Atmosphere: Instance  
Atmosphere = {}

---@field Color Color3
---@field Decay Color3
---@field Density float
---@field Glare float
---@field Haze float
---@field Offset float
