---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Attachment: Instance  
Attachment = {}

---@return Vector3
function Attachment:GetAxis() end


---@return Objects
function Attachment:GetConstraints() end


---@return Vector3
function Attachment:GetSecondaryAxis() end

---@param axis Vector3
function Attachment:SetAxis(axis) end

---@param axis Vector3
function Attachment:SetSecondaryAxis(axis) end
---@field Axis Vector3
---@field CFrame CFrame
---@field Orientation Vector3
---@field Position Vector3
---@field Rotation Vector3
---@field SecondaryAxis Vector3
---@field Visible bool
---@field WorldAxis Vector3
---@field WorldCFrame CFrame
---@field WorldOrientation Vector3
---@field WorldPosition Vector3
---@field WorldRotation Vector3
---@field WorldSecondaryAxis Vector3
