---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioDeviceOutput: Instance  
AudioDeviceOutput = {}
---@param pin string
---@return Array
function AudioDeviceOutput:GetConnectedWires(pin) end
---@field Player Player
