---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioEqualizer: Instance  
AudioEqualizer = {}
---@param pin string
---@return Array
function AudioEqualizer:GetConnectedWires(pin) end
---@field Bypass bool
---@field HighGain float
---@field LowGain float
---@field MidGain float
---@field MidRange NumberRange
