---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioFader: Instance  
AudioFader = {}
---@param pin string
---@return Array
function AudioFader:GetConnectedWires(pin) end
---@field Bypass bool
---@field Volume float
