---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioEcho: Instance  
AudioEcho = {}
---@param pin string
---@return Array
function AudioEcho:GetConnectedWires(pin) end
---@field Bypass bool
---@field DelayTime float
---@field DryLevel float
---@field Feedback float
---@field WetLevel float
