---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum AudioFilterType  
AudioFilterType = {
  Peak = 0
, LowShelf = 1
, HighShelf = 2
, Lowpass12dB = 3
, Lowpass24dB = 4
, Lowpass48dB = 5
, Highpass12dB = 6
, Highpass24dB = 7
, Highpass48dB = 8
, Bandpass = 9
, Notch = 10
}
