---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioSearchParams: Instance  
AudioSearchParams = {}

---@field Album string
---@field Artist string
---@field AudioSubType AudioSubType
---@field AudioSubtype AudioSubType
---@field MaxDuration int
---@field MinDuration int
---@field SearchKeyword string
---@field Tag string
---@field Title string
