---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioChorus: Instance  
AudioChorus = {}
---@param pin string
---@return Array
function AudioChorus:GetConnectedWires(pin) end
---@field Bypass bool
---@field Depth float
---@field Mix float
---@field Rate float
