---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioCompressor: Instance  
AudioCompressor = {}
---@param pin string
---@return Array
function AudioCompressor:GetConnectedWires(pin) end
---@field Attack float
---@field Bypass bool
---@field MakeupGain float
---@field Ratio float
---@field Release float
---@field Threshold float
