---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioPlayer: Instance  
AudioPlayer = {}
---@param pin string
---@return Array
function AudioPlayer:GetConnectedWires(pin) end


function AudioPlayer:Play() end


function AudioPlayer:Stop() end
---@field Asset Content
---@field AssetId string
---@field AutoLoad bool
---@field IsPlaying bool
---@field IsReady bool
---@field LoopRegion NumberRange
---@field Looping bool
---@field PlaybackRegion NumberRange
---@field PlaybackSpeed double
---@field TimeLength double
---@field TimePosition double
---@field Volume float
