---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioDistortion: Instance  
AudioDistortion = {}
---@param pin string
---@return Array
function AudioDistortion:GetConnectedWires(pin) end
---@field Bypass bool
---@field Level float
