---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioDeviceInput: Instance  
AudioDeviceInput = {}
---@param pin string
---@return Array
function AudioDeviceInput:GetConnectedWires(pin) end


---@return Array
function AudioDeviceInput:GetUserIdAccessList() end

---@param userIds Array
function AudioDeviceInput:SetUserIdAccessList(userIds) end
---@field AccessList BinaryString
---@field AccessType AccessModifierType
---@field Active bool
---@field IsReady bool
---@field Muted bool
---@field Player Player
---@field Volume float
