---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioListener: Instance  
AudioListener = {}
---@param emitter AudioEmitter
---@return float
function AudioListener:GetAudibilityOf(emitter) end

---@param pin string
---@return Array
function AudioListener:GetConnectedWires(pin) end


---@return Array
function AudioListener:GetInteractingEmitters() end
---@field AudioInteractionGroup string
