---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioFlanger: Instance  
AudioFlanger = {}
---@param pin string
---@return Array
function AudioFlanger:GetConnectedWires(pin) end
---@field Bypass bool
---@field Depth float
---@field Mix float
---@field Rate float
