---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioReverb: Instance  
AudioReverb = {}
---@param pin string
---@return Array
function AudioReverb:GetConnectedWires(pin) end
---@field Bypass bool
---@field DecayRatio float
---@field DecayTime float
---@field Density float
---@field Diffusion float
---@field DryLevel float
---@field EarlyDelayTime float
---@field HighCutFrequency float
---@field LateDelayTime float
---@field LowShelfFrequency float
---@field LowShelfGain float
---@field ReferenceFrequency float
---@field WetLevel float
