---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioAnalyzer: Instance  
AudioAnalyzer = {}
---@param pin string
---@return Array
function AudioAnalyzer:GetConnectedWires(pin) end


---@return Array
function AudioAnalyzer:GetSpectrum() end
---@field PeakLevel float
---@field RmsLevel float
