---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AudioPitchShifter: Instance  
AudioPitchShifter = {}
---@param pin string
---@return Array
function AudioPitchShifter:GetConnectedWires(pin) end
---@field Bypass bool
---@field Pitch float
