---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AvatarGenerationSession: Instance  
AvatarGenerationSession = {}
---@param previewJob Avatar2DGenerationJob
---@param options Dictionary
---@return Avatar3DGenerationJob
function AvatarGenerationSession:GenerateAvatarModel(previewJob, options) end

---@param textPrompt string
---@param options Dictionary
---@return Avatar2DGenerationJob
function AvatarGenerationSession:GenerateAvatarPreview(textPrompt, options) end

