---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum AvatarGenerationError  
AvatarGenerationError = {
  None = 0
, Timeout = 1
, DownloadFailed = 2
, Canceled = 3
, Offensive = 4
, Unknown = 5
}
