---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AvatarGenerationJob: Instance  
AvatarGenerationJob = {}

---@return Dictionary
function AvatarGenerationJob:GetOutput() end


function AvatarGenerationJob:Cancel() end


function AvatarGenerationJob:Wait() end
---@field Error AvatarGenerationError
---@field ErrorMessage string
---@field Progress float
---@field Status AvatarGenerationJobStatus
