---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum AvatarGenerationJobStatus  
AvatarGenerationJobStatus = {
  NotStarted = 0
, InProgress = 1
, Completed = 2
, Failed = 3
}
