---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AvatarChatService: Instance  
AvatarChatService = {}

---@return bool
function AvatarChatService:EnableVoice() end

---@param mask int
---@param feature AvatarChatServiceFeature
---@return bool
function AvatarChatService:IsEnabled(mask, feature) end


---@return bool
function AvatarChatService:IsPlaceEnabled() end


---@return bool
function AvatarChatService:IsUniverseEnabled() end


---@return int
function AvatarChatService:PollClientFeatures() end


---@return int
function AvatarChatService:PollServerFeatures() end

---@param feature DeviceFeatureType
---@return bool
function AvatarChatService:deviceMeetsRequirementsForFeature(feature) end


---@return int
function AvatarChatService:GetClientFeaturesAsync() end


---@return int
function AvatarChatService:GetServerFeaturesAsync() end
---@field ClientFeatures int
---@field ClientFeaturesInitialized bool
---@field ServerFeatures int
