---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class AvatarImportService: Instance  
AvatarImportService = {}
---@param fbxFilePath string
---@param selectedRig Instance
---@param userChooseModelThenImportCB Function
---@return Instance
function AvatarImportService:ImportFBXAnimationFromFilePathUserMayChooseModel(fbxFilePath, selectedRig, userChooseModelThenImportCB) end

---@param selectedRig Instance
---@param userChooseModelThenImportCB Function
---@return Instance
function AvatarImportService:ImportFBXAnimationUserMayChooseModel(selectedRig, userChooseModelThenImportCB) end

---@param isR15 bool
---@return Instance
function AvatarImportService:ImportFbxRigWithoutSceneLoad(isR15) end

---@param useFBXModel bool
---@return Instance
function AvatarImportService:ImportLoadedFBXAnimation(useFBXModel) end

---@param promptR15Callback Function
---@return Instance
function AvatarImportService:LoadRigAndDetectType(promptR15Callback) end

