---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BadgeService: Instance  
BadgeService = {}
---@param userId int64
---@param badgeId int64
---@return bool
function BadgeService:AwardBadge(userId, badgeId) end

---@param userId int64
---@param badgeIds Array
---@return Array
function BadgeService:CheckUserBadgesAsync(userId, badgeIds) end

---@param badgeId int64
---@return Dictionary
function BadgeService:GetBadgeInfoAsync(badgeId) end

---@param badgeId int64
---@return bool
function BadgeService:IsDisabled(badgeId) end

---@param badgeId int64
---@return bool
function BadgeService:IsLegal(badgeId) end

---@param userId int64
---@param badgeId int64
---@return bool
function BadgeService:UserHasBadge(userId, badgeId) end

---@param userId int64
---@param badgeId int64
---@return bool
function BadgeService:UserHasBadgeAsync(userId, badgeId) end

