---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BallSocketConstraint: Constraint  
BallSocketConstraint = {}

---@field LimitsEnabled bool
---@field MaxFrictionTorque float
---@field MaxFrictionTorqueXml float
---@field Radius float
---@field Restitution float
---@field TwistLimitsEnabled bool
---@field TwistLowerAngle float
---@field TwistUpperAngle float
---@field UpperAngle float
