---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BasePlayerGui: Instance  
BasePlayerGui = {}
---@param x int
---@param y int
---@return Objects
function BasePlayerGui:GetGuiObjectsAtPosition(x, y) end

---@param position Vector2
---@param radius float
---@return Objects
function BasePlayerGui:GetGuiObjectsInCircle(position, radius) end

