---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BasePart: PVInstance  
BasePart = {}
---@param angAcceleration Vector3
---@param angVelocity Vector3
---@return Vector3
function BasePart:AngularAccelerationToTorque(angAcceleration, angVelocity) end

---@param impulse Vector3
function BasePart:ApplyAngularImpulse(impulse) end

---@param impulse Vector3
function BasePart:ApplyImpulse(impulse) end

---@param impulse Vector3
---@param position Vector3
function BasePart:ApplyImpulseAtPosition(impulse, position) end


function BasePart:BreakJoints() end

---@param part BasePart
---@return bool
function BasePart:CanCollideWith(part) end


---@return Tuple
function BasePart:CanSetNetworkOwnership() end

---@param position Vector3
---@return Vector3
function BasePart:GetClosestPointOnSurface(position) end

---@param recursive bool
---@return Objects
function BasePart:GetConnectedParts(recursive) end


---@return Objects
function BasePart:GetJoints() end


---@return float
function BasePart:GetMass() end


---@return Instance
function BasePart:GetNetworkOwner() end


---@return bool
function BasePart:GetNetworkOwnershipAuto() end


---@return Objects
function BasePart:GetNoCollisionConstraints() end


---@return CFrame
function BasePart:GetRenderCFrame() end


---@return Instance
function BasePart:GetRootPart() end


---@return Objects
function BasePart:GetTouchingParts() end

---@param position Vector3
---@return Vector3
function BasePart:GetVelocityAtPosition(position) end


---@return bool
function BasePart:IsGrounded() end


function BasePart:MakeJoints() end

---@param normalId NormalId
---@param deltaAmount int
---@return bool
function BasePart:Resize(normalId, deltaAmount) end

---@param playerInstance Player
function BasePart:SetNetworkOwner(playerInstance) end


function BasePart:SetNetworkOwnershipAuto() end

---@param torque Vector3
---@param angVelocity Vector3
---@return Vector3
function BasePart:TorqueToAngularAcceleration(torque, angVelocity) end


function BasePart:breakJoints() end


---@return float
function BasePart:getMass() end


function BasePart:makeJoints() end

---@param normalId NormalId
---@param deltaAmount int
---@return bool
function BasePart:resize(normalId, deltaAmount) end

---@param parts Objects
---@param collisionfidelity CollisionFidelity
---@param renderFidelity RenderFidelity
---@return Instance
function BasePart:IntersectAsync(parts, collisionfidelity, renderFidelity) end

---@param parts Objects
---@param collisionfidelity CollisionFidelity
---@param renderFidelity RenderFidelity
---@return Instance
function BasePart:SubtractAsync(parts, collisionfidelity, renderFidelity) end

---@param parts Objects
---@param collisionfidelity CollisionFidelity
---@param renderFidelity RenderFidelity
---@return Instance
function BasePart:UnionAsync(parts, collisionfidelity, renderFidelity) end
---@field Anchored bool
---@field AssemblyAngularVelocity Vector3
---@field AssemblyCenterOfMass Vector3
---@field AssemblyLinearVelocity Vector3
---@field AssemblyMass float
---@field AssemblyRootPart BasePart
---@field BackParamA float
---@field BackParamB float
---@field BackSurface SurfaceType
---@field BackSurfaceInput InputType
---@field BottomParamA float
---@field BottomParamB float
---@field BottomSurface SurfaceType
---@field BottomSurfaceInput InputType
---@field BrickColor BrickColor
---@field CFrame CFrame
---@field CanCollide bool
---@field CanQuery bool
---@field CanTouch bool
---@field CastShadow bool
---@field CenterOfMass Vector3
---@field CollisionGroup string
---@field CollisionGroupId int
---@field CollisionGroupReplicate string
---@field Color Color3
---@field Color3uint8 Color3uint8
---@field CurrentPhysicalProperties PhysicalProperties
---@field CustomPhysicalProperties PhysicalProperties
---@field DraggingV1 bool
---@field Elasticity float
---@field EnableFluidForces bool
---@field ExtentsCFrame CFrame
---@field ExtentsSize Vector3
---@field Friction float
---@field FrontParamA float
---@field FrontParamB float
---@field FrontSurface SurfaceType
---@field FrontSurfaceInput InputType
---@field LeftParamA float
---@field LeftParamB float
---@field LeftSurface SurfaceType
---@field LeftSurfaceInput InputType
---@field LocalSimulationValidation int
---@field LocalTransparencyModifier float
---@field Locked bool
---@field Mass float
---@field Massless bool
---@field Material Material
---@field MaterialVariant string
---@field MaterialVariantSerialized string
---@field NetworkIsSleeping bool
---@field NetworkOwnerV3 SystemAddress
---@field NetworkOwnershipRule NetworkOwnership
---@field Orientation Vector3
---@field PhysicsCFrame CFrame
---@field PhysicsLinearVelocity Vector3
---@field PhysicsRepRootPart BasePart
---@field PhysicsRotationalVelocity Vector3
---@field PivotOffset CFrame
---@field Position Vector3
---@field ReceiveAge float
---@field Reflectance float
---@field ResizeIncrement int
---@field ResizeableFaces Faces
---@field RightParamA float
---@field RightParamB float
---@field RightSurface SurfaceType
---@field RightSurfaceInput InputType
---@field RootPriority int
---@field RotVelocity Vector3
---@field Rotation Vector3
---@field Size Vector3
---@field SpecificGravity float
---@field TopParamA float
---@field TopParamB float
---@field TopSurface SurfaceType
---@field TopSurfaceInput InputType
---@field Transparency float
---@field Velocity Vector3
---@field brickColor BrickColor
---@field siz Vector3
---@field size Vector3
