---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BaseScript: LuaSourceContainer  
BaseScript = {}

---@field Disabled bool
---@field Enabled bool
---@field LinkedSource Content
---@field RunContext RunContext
