---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BaseWrap: Instance  
BaseWrap = {}

---@return Vector3
function BaseWrap:GetCageOffset() end

---@param cageType CageType
---@return Array
function BaseWrap:GetFaces(cageType) end

---@param cageType CageType
---@return Array
function BaseWrap:GetUVs(cageType) end

---@param cageType CageType
---@return Array
function BaseWrap:GetVertices(cageType) end


---@return bool
function BaseWrap:IsHSRReady() end

---@param cageType CageType
---@param vertices Array
function BaseWrap:ModifyVertices(cageType, vertices) end
---@field CageMeshId Content
---@field CageOrigin CFrame
---@field CageOriginWorld CFrame
---@field HSRAssetId Content
---@field HSRData SharedString
---@field HSRMeshIdData SharedString
---@field ImportInProcess bool
---@field ImportOrigin CFrame
---@field ImportOriginWorld CFrame
---@field TemporaryCageMeshId Content
