---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BaseImportData: Instance  
BaseImportData = {}

---@return Dictionary
function BaseImportData:CreatePresetFromData() end


---@return Instance
function BaseImportData:GetPreview() end


---@return Dictionary
function BaseImportData:GetStatuses() end
---@field Id string
---@field ImportName string
---@field ShouldImport bool
