---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Beam: Instance  
Beam = {}
---@param offset float
function Beam:SetTextureOffset(offset) end
---@field Attachment0 Attachment
---@field Attachment1 Attachment
---@field Brightness float
---@field Color ColorSequence
---@field CurveSize0 float
---@field CurveSize1 float
---@field Enabled bool
---@field FaceCamera bool
---@field LightEmission float
---@field LightInfluence float
---@field LocalTransparencyModifier float
---@field Segments int
---@field Texture Content
---@field TextureLength float
---@field TextureMode TextureMode
---@field TextureSpeed float
---@field Transparency NumberSequence
---@field Width0 float
---@field Width1 float
---@field ZOffset float
