---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BillboardGui: LayerCollector  
BillboardGui = {}

---@return Variant
function BillboardGui:GetScreenSpaceBounds() end
---@field Active bool
---@field Adornee Instance
---@field AlwaysOnTop bool
---@field Brightness float
---@field ClipsDescendants bool
---@field CurrentDistance float
---@field DistanceLowerLimit float
---@field DistanceStep float
---@field DistanceUpperLimit float
---@field ExtentsOffset Vector3
---@field ExtentsOffsetWorldSpace Vector3
---@field LightInfluence float
---@field MaxDistance float
---@field PlayerToHideFrom Instance
---@field Size UDim2
---@field SizeOffset Vector2
---@field StudsOffset Vector3
---@field StudsOffsetWorldSpace Vector3
