---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BindableFunction: Instance  
BindableFunction = {}
---@param arguments Tuple
---@return Tuple
function BindableFunction:Invoke(arguments) end

