---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BodyAngularVelocity: BodyMover  
BodyAngularVelocity = {}

---@field AngularVelocity Vector3
---@field MaxTorque Vector3
---@field P float
---@field angularvelocity Vector3
---@field maxTorque Vector3
