---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BodyThrust: BodyMover  
BodyThrust = {}

---@field Force Vector3
---@field Location Vector3
---@field force Vector3
---@field location Vector3
