---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BodyPosition: BodyMover  
BodyPosition = {}

---@return Vector3
function BodyPosition:GetLastForce() end


---@return Vector3
function BodyPosition:lastForce() end
---@field D float
---@field MaxForce Vector3
---@field P float
---@field Position Vector3
---@field maxForce Vector3
---@field position Vector3
