---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BodyGyro: BodyMover  
BodyGyro = {}

---@field CFrame CFrame
---@field D float
---@field MaxTorque Vector3
---@field P float
---@field cframe CFrame
---@field maxTorque Vector3
