---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BodyPartDescription: Instance  
BodyPartDescription = {}

---@field AssetId int64
---@field BodyPart BodyPart
---@field Color Color3
---@field Instance Instance
