---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BodyColors: CharacterAppearance  
BodyColors = {}

---@field HeadColor BrickColor
---@field HeadColor3 Color3
---@field LeftArmColor BrickColor
---@field LeftArmColor3 Color3
---@field LeftLegColor BrickColor
---@field LeftLegColor3 Color3
---@field RightArmColor BrickColor
---@field RightArmColor3 Color3
---@field RightLegColor BrickColor
---@field RightLegColor3 Color3
---@field TorsoColor BrickColor
---@field TorsoColor3 Color3
