---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BodyVelocity: BodyMover  
BodyVelocity = {}

---@return Vector3
function BodyVelocity:GetLastForce() end


---@return Vector3
function BodyVelocity:lastForce() end
---@field MaxForce Vector3
---@field P float
---@field Velocity Vector3
---@field maxForce Vector3
---@field velocity Vector3
