---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Bone: Attachment  
Bone = {}

---@field Transform CFrame
---@field TransformedCFrame CFrame
---@field TransformedWorldCFrame CFrame
