---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Breakpoint: Instance  
Breakpoint = {}

---@field Condition string
---@field ContinueExecution bool
---@field Enabled bool
---@field Id int
---@field Line int
---@field LogMessage string
---@field MetaBreakpointId int
---@field RemoveOnHit bool
---@field Script string
---@field Valid bool
---@field Verified bool
