---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BrowserService: Instance  
BrowserService = {}

function BrowserService:CloseBrowserWindow() end


function BrowserService:CopyAuthCookieFromBrowserToEngine() end

---@param moduleName string
---@param eventName string
---@param params string
function BrowserService:EmitHybridEvent(moduleName, eventName, params) end

---@param javascript string
function BrowserService:ExecuteJavaScript(javascript) end

---@param url string
function BrowserService:OpenBrowserWindow(url) end

---@param title string
---@param url string
function BrowserService:OpenNativeOverlay(title, url) end


function BrowserService:OpenWeChatAuthWindow() end

---@param callbackId string
---@param success bool
---@param params string
function BrowserService:ReturnToJavaScript(callbackId, success, params) end

---@param command string
function BrowserService:SendCommand(command) end

