---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BubbleChatMessageProperties: Instance  
BubbleChatMessageProperties = {}

---@field BackgroundColor3 Color3
---@field BackgroundTransparency double
---@field FontFace Font
---@field TailVisible bool
---@field TextColor3 Color3
---@field TextSize int64
