---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BubbleChatConfiguration: TextChatConfigurations  
BubbleChatConfiguration = {}

---@field AdorneeName string
---@field BackgroundColor3 Color3
---@field BackgroundTransparency double
---@field BubbleDuration float
---@field BubblesSpacing float
---@field Enabled bool
---@field Font Font
---@field FontFace Font
---@field LocalPlayerStudsOffset Vector3
---@field MaxBubbles float
---@field MaxDistance float
---@field MinimizeDistance float
---@field TailVisible bool
---@field TextColor3 Color3
---@field TextSize int64
---@field VerticalStudsOffset float
