---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class BulkImportService: Instance  
BulkImportService = {}
---@param assetTypeToImport int
function BulkImportService:LaunchBulkImport(assetTypeToImport) end


function BulkImportService:ShowBulkImportView() end

