---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum ButtonStyle  
ButtonStyle = {
  Custom = 0
, RobloxButtonDefault = 1
, RobloxButton = 2
, RobloxRoundButton = 3
, RobloxRoundDefaultButton = 4
, RobloxRoundDropdownButton = 5
}
