---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CalloutService: Instance  
CalloutService = {}
---@param definitionId string
---@param locationId string
---@param target Instance
function CalloutService:AttachCallout(definitionId, locationId, target) end

---@param definitionId string
---@param title string
---@param description string
---@param learnMoreURL string
function CalloutService:DefineCallout(definitionId, title, description, learnMoreURL) end

---@param definitionId string
function CalloutService:DetachCalloutsByDefinitionId(definitionId) end

