---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum CameraType  
CameraType = {
  Fixed = 0
, Attach = 1
, Watch = 2
, Track = 3
, Follow = 4
, Custom = 5
, Scriptable = 6
, Orbital = 7
}
