---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Camera: Instance  
Camera = {}
---@param ignoreList Objects
---@return float
function Camera:GetLargestCutoffDistance(ignoreList) end


---@return float
function Camera:GetPanSpeed() end

---@param castPoints Array
---@param ignoreList Objects
---@return Objects
function Camera:GetPartsObscuringTarget(castPoints, ignoreList) end


---@return CFrame
function Camera:GetRenderCFrame() end


---@return float
function Camera:GetRoll() end


---@return float
function Camera:GetTiltSpeed() end

---@param endPos CFrame
---@param endFocus CFrame
---@param duration float
function Camera:Interpolate(endPos, endFocus, duration) end

---@param units int
function Camera:PanUnits(units) end

---@param x float
---@param y float
---@param depth float
---@return Ray
function Camera:ScreenPointToRay(x, y, depth) end

---@param mode CameraPanMode
function Camera:SetCameraPanMode(mode) end

---@param modelCoord CFrame
function Camera:SetImageServerView(modelCoord) end

---@param rollAngle float
function Camera:SetRoll(rollAngle) end

---@param units int
---@return bool
function Camera:TiltUnits(units) end

---@param x float
---@param y float
---@param depth float
---@return Ray
function Camera:ViewportPointToRay(x, y, depth) end

---@param worldPoint Vector3
---@return Tuple
function Camera:WorldToScreenPoint(worldPoint) end

---@param worldPoint Vector3
---@return Tuple
function Camera:WorldToViewportPoint(worldPoint) end

---@param distance float
---@return bool
function Camera:Zoom(distance) end

---@param boundingBoxCFrame CFrame
---@param boundingBoxSize Vector3
function Camera:ZoomToExtents(boundingBoxCFrame, boundingBoxSize) end
---@field CFrame CFrame
---@field CameraSubject Instance
---@field CameraType CameraType
---@field CoordinateFrame CFrame
---@field DiagonalFieldOfView float
---@field FieldOfView float
---@field FieldOfViewMode FieldOfViewMode
---@field Focus CFrame
---@field HeadLocked bool
---@field HeadScale float
---@field MaxAxisFieldOfView float
---@field NearPlaneZ float
---@field VRTiltAndRollEnabled bool
---@field ViewportSize Vector2
---@field focus CFrame
