---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CaptureService: Instance  
CaptureService = {}
---@param onCaptureReady Function
function CaptureService:CaptureScreenshot(onCaptureReady) end

---@param capturePath string
function CaptureService:DeleteCapture(capturePath) end


function CaptureService:OnCaptureBegan() end


function CaptureService:OnCaptureEnded() end

---@param capturePath string
function CaptureService:OnCaptureShared(capturePath) end

---@param promptId int64
---@param results Dictionary
function CaptureService:OnSavePromptFinished(promptId, results) end

---@param promptId int64
---@param accepted bool
function CaptureService:OnSharePromptFinished(promptId, accepted) end

---@param contentIds Array
---@param resultCallback Function
function CaptureService:PromptSaveCapturesToGallery(contentIds, resultCallback) end

---@param contentId Content
---@param launchData string
---@param onAcceptedCallback Function
---@param onDeniedCallback Function
function CaptureService:PromptShareCapture(contentId, launchData, onAcceptedCallback, onDeniedCallback) end


---@return Array
function CaptureService:RetrieveCaptures() end

---@param capturePath string
function CaptureService:SaveCaptureToExternalStorage(capturePath) end


function CaptureService:SaveScreenshotCapture() end

---@param pathArr Array
---@param caption string
---@return Dictionary
function CaptureService:CreatePostAsync(pathArr, caption) end

---@param pathArr Array
---@return int64
function CaptureService:DeleteCapturesAsync(pathArr) end

---@param captureContentId Content
---@return string
function CaptureService:GetCaptureFilePathAsync(captureContentId) end

---@param captureContentId Content
---@return Vector2
function CaptureService:GetCaptureSizeAsync(captureContentId) end

---@param pathArr Array
---@return int64
function CaptureService:GetCaptureStorageSizeAsync(pathArr) end

---@param pathArr Array
---@return int64
function CaptureService:SaveCapturesToExternalStorageAsync(pathArr) end

