---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum CatalogSortType  
CatalogSortType = {
  Relevance = 1
, PriceHighToLow = 2
, PriceLowToHigh = 3
, MostFavorited = 5
, RecentlyCreated = 6
, Bestselling = 7
}
