---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum CatalogCategoryFilter  
CatalogCategoryFilter = {
  None = 1
, Featured = 2
, Collectibles = 3
, CommunityCreations = 4
, Premium = 5
, Recommended = 6
}
