---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum CatalogSortAggregation  
CatalogSortAggregation = {
  Past12Hours = 1
, PastDay = 2
, Past3Days = 3
, PastWeek = 4
, PastMonth = 5
, AllTime = 6
}
