---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum CellBlock  
CellBlock = {
  Solid = 0
, VerticalWedge = 1
, CornerWedge = 2
, InverseCornerWedge = 3
, HorizontalWedge = 4
}
