---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum CenterDialogType  
CenterDialogType = {
  UnsolicitedDialog = 1
, PlayerInitiatedDialog = 2
, ModalDialog = 3
, QuitDialog = 4
}
