---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ChangeHistoryService: Instance  
ChangeHistoryService = {}
---@param identifier string
---@param operation FinishRecordingOperation
---@param finalOptions Dictionary?
function ChangeHistoryService:FinishRecording(identifier, operation, finalOptions) end


---@return Tuple
function ChangeHistoryService:GetCanRedo() end


---@return Tuple
function ChangeHistoryService:GetCanUndo() end

---@param identifier string?
---@return bool
function ChangeHistoryService:IsRecordingInProgress(identifier) end


function ChangeHistoryService:Redo() end


function ChangeHistoryService:ResetWaypoints() end

---@param state bool
function ChangeHistoryService:SetEnabled(state) end

---@param name string
function ChangeHistoryService:SetWaypoint(name) end

---@param name string
---@param displayName string?
---@return string?
function ChangeHistoryService:TryBeginRecording(name, displayName) end


function ChangeHistoryService:Undo() end

