---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum CharacterControlMode  
CharacterControlMode = {
  Default = 0
, Legacy = 1
, NoCharacterController = 2
, LuaCharacterController = 3
}
