---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CharacterMesh: CharacterAppearance  
CharacterMesh = {}

---@field BaseTextureId int64
---@field BodyPart BodyPart
---@field MeshId int64
---@field OverlayTextureId int64
