---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ChatInputBarConfiguration: TextChatConfigurations  
ChatInputBarConfiguration = {}

---@field AbsolutePosition Vector2
---@field AbsolutePositionWrite Vector2
---@field AbsoluteSize Vector2
---@field AbsoluteSizeWrite Vector2
---@field AutocompleteEnabled bool
---@field BackgroundColor3 Color3
---@field BackgroundTransparency double
---@field Enabled bool
---@field FontFace Font
---@field IsFocused bool
---@field IsFocusedWrite bool
---@field KeyboardKeyCode KeyCode
---@field PlaceholderColor3 Color3
---@field TargetTextChannel TextChannel
---@field TextBox TextBox
---@field TextColor3 Color3
---@field TextSize int64
---@field TextStrokeColor3 Color3
---@field TextStrokeTransparency double
