---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ChatbotUIService: Instance  
ChatbotUIService = {}
---@param contentType string
---@param data Dictionary
function ChatbotUIService:DisplayContent(contentType, data) end


---@return Dictionary
function ChatbotUIService:GetSettings() end

