---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ChatWindowConfiguration: TextChatConfigurations  
ChatWindowConfiguration = {}

---@field AbsolutePosition Vector2
---@field AbsolutePositionWrite Vector2
---@field AbsoluteSize Vector2
---@field AbsoluteSizeWrite Vector2
---@field BackgroundColor3 Color3
---@field BackgroundTransparency double
---@field Enabled bool
---@field FontFace Font
---@field HeightScale float
---@field HorizontalAlignment HorizontalAlignment
---@field TextColor3 Color3
---@field TextSize int64
---@field TextStrokeColor3 Color3
---@field TextStrokeTransparency double
---@field VerticalAlignment VerticalAlignment
---@field WidthScale float
