---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum ChatCallbackType  
ChatCallbackType = {
  OnCreatingChatWindow = 1
, OnClientSendingMessage = 2
, OnClientFormattingMessage = 3
, OnServerReceivingMessage = 17
}
