---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Chat: Instance  
Chat = {}
---@param partOrCharacter Instance
---@param message string
---@param color ChatColor
function Chat:Chat(partOrCharacter, message, color) end

---@param partOrCharacter Instance
---@param message string
---@param color ChatColor
function Chat:ChatLocal(partOrCharacter, message, color) end


---@return bool
function Chat:GetShouldUseLuaChat() end

---@param callbackType ChatCallbackType
---@param callbackArguments Tuple
---@return Tuple
function Chat:InvokeChatCallback(callbackType, callbackArguments) end

---@param callbackType ChatCallbackType
---@param callbackFunction Function
function Chat:RegisterChatCallback(callbackType, callbackFunction) end

---@param settings Variant
function Chat:SetBubbleChatSettings(settings) end

---@param userId int64
---@return bool
function Chat:CanUserChatAsync(userId) end

---@param userIdFrom int64
---@param userIdTo int64
---@return bool
function Chat:CanUsersChatAsync(userIdFrom, userIdTo) end

---@param stringToFilter string
---@param playerFrom Player
---@param playerTo Player
---@return string
function Chat:FilterStringAsync(stringToFilter, playerFrom, playerTo) end

---@param stringToFilter string
---@param playerFrom Player
---@return string
function Chat:FilterStringForBroadcast(stringToFilter, playerFrom) end

---@param stringToFilter string
---@param playerToFilterFor Player
---@return string
function Chat:FilterStringForPlayerAsync(stringToFilter, playerToFilterFor) end
---@field BubbleChatEnabled bool
---@field LoadDefaultChat bool
