---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ClientReplicator: NetworkReplicator  
ClientReplicator = {}
---@param frameRate int
---@param timeFrame int
function ClientReplicator:RequestRCCProfilerData(frameRate, timeFrame) end


function ClientReplicator:RequestServerLuauHeapData() end

---@param start bool
---@param frequency int?
function ClientReplicator:RequestServerScriptProfiling(start, frequency) end


function ClientReplicator:RequestServerScriptProfilingData() end

---@param request bool
function ClientReplicator:RequestServerStats(request) end

