---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ClimbController: ControllerBase  
ClimbController = {}

---@field AccelerationTime float
---@field BalanceMaxTorque float
---@field BalanceSpeed float
---@field MoveMaxForce float
