---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Clothing: CharacterAppearance  
Clothing = {}

---@field Color3 Color3
---@field Outfit1 Content
---@field Outfit2 Content
