---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Clouds: Instance  
Clouds = {}

---@field Color Color3
---@field Cover float
---@field Density float
---@field Enabled bool
