---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CollaboratorsService: Instance  
CollaboratorsService = {}

---@return Objects
function CollaboratorsService:GetCollaboratorsList() end


---@return bool
function CollaboratorsService:GetSelectionHighlightsEnabled() end

---@param collaboratorId int64
function CollaboratorsService:RequestFlyToCollaborator(collaboratorId) end

---@param showHighlights bool
function CollaboratorsService:ToggleSelectionHighlights(showHighlights) end

---@param on bool
function CollaboratorsService:ToggleTeamCreate(on) end

