---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CollectionService: Instance  
CollectionService = {}
---@param instance Instance
---@param tag string
function CollectionService:AddTag(instance, tag) end


---@return Array
function CollectionService:GetAllTags() end

---@param class string
---@return Objects
function CollectionService:GetCollection(class) end

---@param tag string
---@return RBXScriptSignal
function CollectionService:GetInstanceAddedSignal(tag) end

---@param tag string
---@return RBXScriptSignal
function CollectionService:GetInstanceRemovedSignal(tag) end

---@param tag string
---@return Objects
function CollectionService:GetTagged(tag) end

---@param instance Instance
---@return Array
function CollectionService:GetTags(instance) end

---@param instance Instance
---@param tag string
---@return bool
function CollectionService:HasTag(instance, tag) end

---@param instance Instance
---@param tag string
function CollectionService:RemoveTag(instance, tag) end

