---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Collaborator: Instance  
Collaborator = {}

---@field CFrame CFrame
---@field CollaboratorColor int
---@field CollaboratorColor3 Color3
---@field CurDocGUID string
---@field CurScriptLineNumber int
---@field IsIdle bool
---@field Status CollaboratorStatus
---@field UserId int64
---@field Username string
