---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ColorCorrectionEffect: PostEffect  
ColorCorrectionEffect = {}

---@field Brightness float
---@field Contrast float
---@field Saturation float
---@field TintColor Color3
