---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CommandService: Instance  
CommandService = {}
---@param name string
---@param params Variant
---@return Variant
function CommandService:Execute(name, params) end

---@param plugin Plugin
---@param name string
---@param context string
---@param permission CommandPermission
---@return CommandInstance
function CommandService:RegisterCommand(plugin, name, context, permission) end

