---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CommerceService: Instance  
CommerceService = {}
---@param player Player
---@param url string
function CommerceService:PromptRealWorldCommerceBrowser(player, url) end


---@return bool
function CommerceService:UserEligibleForRealWorldCommerceAsync() end

