---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CommandInstance: Instance  
CommandInstance = {}
---@param displayName string
---@param statusTip string
---@param defaultShortcut string
function CommandInstance:EnableGuiAccess(displayName, statusTip, defaultShortcut) end

---@param callbackFunction Function
function CommandInstance:RegisterExecutionCallback(callbackFunction) end
---@field AllowGUIAccessPoints bool
---@field Checked bool
---@field DefaultShortcut string
---@field DisplayName string
---@field Enabled bool
---@field Icon string
---@field Name string
---@field Permission CommandPermission
---@field StatusTip string
