---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum CompletionTriggerKind  
CompletionTriggerKind = {
  Invoked = 1
, TriggerCharacter = 2
, TriggerForIncompleteCompletions = 3
}
