---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CompressorSoundEffect: SoundEffect  
CompressorSoundEffect = {}

---@field Attack float
---@field GainMakeup float
---@field Ratio float
---@field Release float
---@field SideChain Instance
---@field Threshold float
