---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ConnectivityService: Instance  
ConnectivityService = {}

---@return bool
function ConnectivityService:IsNetworkStateAvailable() end
---@field NetworkStatus NetworkStatus
