---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Constraint: Instance  
Constraint = {}
---@param bodyId int
---@return Vector3
function Constraint:GetDebugAppliedForce(bodyId) end

---@param bodyId int
---@return Vector3
function Constraint:GetDebugAppliedTorque(bodyId) end
---@field Active bool
---@field Attachment0 Attachment
---@field Attachment1 Attachment
---@field Color BrickColor
---@field Enabled bool
---@field Visible bool
