---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ContentProvider: Instance  
ContentProvider = {}
---@param meshId string
---@return int
function ContentProvider:CalculateNumTrianglesInMeshSync(meshId) end

---@param contentId Content
---@return AssetFetchStatus
function ContentProvider:GetAssetFetchStatus(contentId) end

---@param contentId Content
---@return RBXScriptSignal
function ContentProvider:GetAssetFetchStatusChangedSignal(contentId) end


---@return Array
function ContentProvider:GetDetailedFailedRequests() end


---@return Array
function ContentProvider:GetFailedRequests() end


---@return Array
function ContentProvider:ListEncryptedAssets() end

---@param contentId Content
function ContentProvider:Preload(contentId) end

---@param encryptionKey string
function ContentProvider:RegisterDefaultEncryptionKey(encryptionKey) end

---@param sessionKey string
function ContentProvider:RegisterDefaultSessionKey(sessionKey) end

---@param assetId Content
---@param encryptionKey string
function ContentProvider:RegisterEncryptedAsset(assetId, encryptionKey) end

---@param contentId Content
---@param sessionKey string
function ContentProvider:RegisterSessionEncryptedAsset(contentId, sessionKey) end

---@param url string
function ContentProvider:SetBaseUrl(url) end


function ContentProvider:UnregisterDefaultEncryptionKey() end

---@param assetId Content
function ContentProvider:UnregisterEncryptedAsset(assetId) end

---@param meshId string
---@return int
function ContentProvider:CalculateNumTrianglesInMesh(meshId) end

---@param contentIdList Array
---@param callbackFunction Function
function ContentProvider:PreloadAsync(contentIdList, callbackFunction) end
---@field BaseUrl string
---@field RequestQueueSize int
