---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ContextActionService: Instance  
ContextActionService = {}
---@param actionName string
---@param functionToBind Function
---@param createTouchButton bool
---@param inputTypes Tuple
function ContextActionService:BindAction(actionName, functionToBind, createTouchButton, inputTypes) end

---@param actionName string
---@param functionToBind Function
---@param createTouchButton bool
---@param priorityLevel int
---@param inputTypes Tuple
function ContextActionService:BindActionAtPriority(actionName, functionToBind, createTouchButton, priorityLevel, inputTypes) end

---@param actionName string
---@param functionToBind Function
---@param createTouchButton bool
---@param inputTypes Tuple
function ContextActionService:BindActionToInputTypes(actionName, functionToBind, createTouchButton, inputTypes) end

---@param userInputTypeForActivation UserInputType
---@param keyCodesForActivation Tuple
function ContextActionService:BindActivate(userInputTypeForActivation, keyCodesForActivation) end

---@param actionName string
---@param functionToBind Function
---@param createTouchButton bool
---@param inputTypes Tuple
function ContextActionService:BindCoreAction(actionName, functionToBind, createTouchButton, inputTypes) end

---@param actionName string
---@param functionToBind Function
---@param createTouchButton bool
---@param priorityLevel int
---@param inputTypes Tuple
function ContextActionService:BindCoreActionAtPriority(actionName, functionToBind, createTouchButton, priorityLevel, inputTypes) end

---@param userInputTypeForActivation UserInputType
---@param keyCodesForActivation Tuple
function ContextActionService:BindCoreActivate(userInputTypeForActivation, keyCodesForActivation) end

---@param actionName string
---@param state UserInputState
---@param inputObject Instance
---@return Tuple
function ContextActionService:CallFunction(actionName, state, inputObject) end

---@param actionName string
---@param actionButton Instance
function ContextActionService:FireActionButtonFoundSignal(actionName, actionButton) end


---@return Dictionary
function ContextActionService:GetAllBoundActionInfo() end


---@return Dictionary
function ContextActionService:GetAllBoundCoreActionInfo() end

---@param actionName string
---@return Dictionary
function ContextActionService:GetBoundActionInfo(actionName) end

---@param actionName string
---@return Dictionary
function ContextActionService:GetBoundCoreActionInfo(actionName) end


---@return string
function ContextActionService:GetCurrentLocalToolIcon() end

---@param actionName string
---@param description string
function ContextActionService:SetDescription(actionName, description) end

---@param actionName string
---@param image string
function ContextActionService:SetImage(actionName, image) end

---@param actionName string
---@param position UDim2
function ContextActionService:SetPosition(actionName, position) end

---@param actionName string
---@param title string
function ContextActionService:SetTitle(actionName, title) end

---@param actionName string
function ContextActionService:UnbindAction(actionName) end

---@param userInputTypeForActivation UserInputType
---@param keyCodeForActivation KeyCode
function ContextActionService:UnbindActivate(userInputTypeForActivation, keyCodeForActivation) end


function ContextActionService:UnbindAllActions() end

---@param actionName string
function ContextActionService:UnbindCoreAction(actionName) end

---@param userInputTypeForActivation UserInputType
---@param keyCodeForActivation KeyCode
function ContextActionService:UnbindCoreActivate(userInputTypeForActivation, keyCodeForActivation) end

---@param actionName string
---@return Instance
function ContextActionService:GetButton(actionName) end

