---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ControllerBase: Instance  
ControllerBase = {}

---@field Active bool
---@field BalanceRigidityEnabled bool
---@field MoveSpeedFactor float
