---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ControllerManager: Instance  
ControllerManager = {}

---@field ActiveController ControllerBase
---@field BaseMoveSpeed float
---@field BaseTurnSpeed float
---@field ClimbSensor ControllerSensor
---@field FacingDirection Vector3
---@field GroundSensor ControllerSensor
---@field MovingDirection Vector3
---@field RootPart BasePart
---@field UpDirection Vector3
