---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ControllerPartSensor: ControllerSensor  
ControllerPartSensor = {}

---@field HitFrame CFrame
---@field HitNormal Vector3
---@field SearchDistance float
---@field SensedPart BasePart
---@field SensorMode SensorMode
