---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Controller: Instance  
Controller = {}
---@param button Button
---@param caption string
function Controller:BindButton(button, caption) end

---@param button Button
---@return bool
function Controller:GetButton(button) end

---@param button Button
function Controller:UnbindButton(button) end

---@param button Button
---@param caption string
function Controller:bindButton(button, caption) end

---@param button Button
---@return bool
function Controller:getButton(button) end

