---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ConversationalAIAcceptanceService: Instance  
ConversationalAIAcceptanceService = {}
---@param requestId string
---@param previousAssetId int64
---@param assetId int64
function ConversationalAIAcceptanceService:AlternativeAssetSelected(requestId, previousAssetId, assetId) end

---@param requestId string
---@param assetId int64
function ConversationalAIAcceptanceService:AssetInserted(requestId, assetId) end

---@param requestId string
---@param code string
---@param serverAutorun bool
---@param autorunEnabled bool
---@param autoExpandDropdowns bool
function ConversationalAIAcceptanceService:CodeRunnerActivated(requestId, code, serverAutorun, autorunEnabled, autoExpandDropdowns) end

---@param requestId string
---@param success bool
---@param errorMessage string
function ConversationalAIAcceptanceService:CodeRunnerCompleted(requestId, success, errorMessage) end

---@param requestId string
function ConversationalAIAcceptanceService:CodeRunnerUndone(requestId) end

---@param requestId string
---@param latency double
function ConversationalAIAcceptanceService:DataModelHierarchyLatency(requestId, latency) end

---@param requestId string
---@param errorType string
function ConversationalAIAcceptanceService:ErrorTelemetry(requestId, errorType) end

---@param requestId string
function ConversationalAIAcceptanceService:InstanceInserted(requestId) end

---@param requestId string
---@param waypointName string
function ConversationalAIAcceptanceService:RecordingActionEnded(requestId, waypointName) end

