---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum CoreGuiType  
CoreGuiType = {
  PlayerList = 0
, Health = 1
, Backpack = 2
, Chat = 3
, All = 4
, EmotesMenu = 5
, SelfView = 6
, Captures = 7
}
