---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CoreScriptSyncService: Instance  
CoreScriptSyncService = {}
---@param script Instance
---@return Variant
function CoreScriptSyncService:GetScriptFilePath(script) end

