---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CoreGui: BasePlayerGui  
CoreGui = {}
---@param enabled bool
---@param guiAdornee Instance
---@param faceId NormalId
---@param horizontalCurvature float
function CoreGui:SetUserGuiRendering(enabled, guiAdornee, faceId, horizontalCurvature) end


function CoreGui:TakeScreenshot() end


function CoreGui:ToggleRecording() end
---@field SelectionImageObject GuiObject
---@field Version int
