---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CrossDMScriptChangeListener: Instance  
CrossDMScriptChangeListener = {}
---@param scriptRef string
---@param lineNumber int
---@return bool
function CrossDMScriptChangeListener:IsWatchingScriptLine(scriptRef, lineNumber) end

---@param scriptRef string
---@param debuggerConnectionId int
---@param lineNumber int
function CrossDMScriptChangeListener:StartWatchingScriptLine(scriptRef, debuggerConnectionId, lineNumber) end

