---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CustomEventReceiver: Instance  
CustomEventReceiver = {}

---@return float
function CustomEventReceiver:GetCurrentValue() end
---@field Source Instance
