---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CustomEvent: Instance  
CustomEvent = {}

---@return Objects
function CustomEvent:GetAttachedReceivers() end

---@param newValue float
function CustomEvent:SetValue(newValue) end
---@field PersistedCurrentValue float
