---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CylindricalConstraint: SlidingBallConstraint  
CylindricalConstraint = {}

---@field AngularActuatorType ActuatorType
---@field AngularLimitsEnabled bool
---@field AngularResponsiveness float
---@field AngularRestitution float
---@field AngularSpeed float
---@field AngularVelocity float
---@field CurrentAngle float
---@field InclinationAngle float
---@field LowerAngle float
---@field MotorMaxAngularAcceleration float
---@field MotorMaxTorque float
---@field RotationAxisVisible bool
---@field ServoMaxTorque float
---@field SoftlockAngularServoUponReachingTarget bool
---@field TargetAngle float
---@field UpperAngle float
---@field WorldRotationAxis Vector3
