---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class CylinderHandleAdornment: HandleAdornment  
CylinderHandleAdornment = {}

---@field Angle float
---@field Height float
---@field InnerRadius float
---@field Radius float
