---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DataStoreSetOptions: Instance  
DataStoreSetOptions = {}

---@return Dictionary
function DataStoreSetOptions:GetMetadata() end

---@param attributes Dictionary
function DataStoreSetOptions:SetMetadata(attributes) end

