---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DataModelPatchService: Instance  
DataModelPatchService = {}
---@param patchName string
---@return string
function DataModelPatchService:GetLuaVersion(patchName) end

---@param patchName string
---@return Instance
function DataModelPatchService:GetPatch(patchName) end

---@param patchName string
---@param behaviorName string
---@param localConfigPath string
---@param userId int64
function DataModelPatchService:RegisterPatch(patchName, behaviorName, localConfigPath, userId) end

---@param userId int64
---@param patchName string
---@param callbackFunction Function
function DataModelPatchService:UpdatePatch(userId, patchName, callbackFunction) end

