---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DataStoreIncrementOptions: Instance  
DataStoreIncrementOptions = {}

---@return Dictionary
function DataStoreIncrementOptions:GetMetadata() end

---@param attributes Dictionary
function DataStoreIncrementOptions:SetMetadata(attributes) end

