---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DataStoreInfo: Instance  
DataStoreInfo = {}

---@field CreatedTime int64
---@field DataStoreName string
---@field UpdatedTime int64
