---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DataStoreObjectVersionInfo: Instance  
DataStoreObjectVersionInfo = {}

---@field CreatedTime int64
---@field IsDeleted bool
---@field Version string
