---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DataStoreService: Instance  
DataStoreService = {}
---@param name string
---@param scope string
---@param options Instance
---@return GlobalDataStore
function DataStoreService:GetDataStore(name, scope, options) end


---@return GlobalDataStore
function DataStoreService:GetGlobalDataStore() end

---@param name string
---@param scope string
---@return OrderedDataStore
function DataStoreService:GetOrderedDataStore(name, scope) end

---@param requestType DataStoreRequestType
---@return int
function DataStoreService:GetRequestBudgetForRequestType(requestType) end

---@param prefix string
---@param pageSize int
---@param cursor string
---@return DataStoreListingPages
function DataStoreService:ListDataStoresAsync(prefix, pageSize, cursor) end
---@field AutomaticRetry bool
---@field LegacyNamingScheme bool
