---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DataModel: ServiceProvider  
DataModel = {}
---@param function Function
function DataModel:BindToClose(function) end

---@param name string
---@param defaultValue bool
---@return bool
function DataModel:DefineFastFlag(name, defaultValue) end

---@param name string
---@param defaultValue int
---@return int
function DataModel:DefineFastInt(name, defaultValue) end

---@param name string
---@param defaultValue string
---@return string
function DataModel:DefineFastString(name, defaultValue) end

---@param name string
---@return bool
function DataModel:GetEngineFeature(name) end

---@param name string
---@return bool
function DataModel:GetFastFlag(name) end

---@param name string
---@return int
function DataModel:GetFastInt(name) end

---@param name string
---@return string
function DataModel:GetFastString(name) end


---@return Array
function DataModel:GetJobsInfo() end


---@return string
function DataModel:GetMessage() end

---@param url Content
---@return Objects
function DataModel:GetObjects(url) end

---@param url Content
---@param binaryFormatOnly bool
---@return Objects
function DataModel:GetObjectsAllOrNone(url, binaryFormatOnly) end

---@param urls Array
---@return Array
function DataModel:GetObjectsList(urls) end


---@return string
function DataModel:GetPlaySessionId() end


---@return bool
function DataModel:GetRemoteBuildMode() end


---@return bool
function DataModel:IsContentLoaded() end

---@param gearType GearType
---@return bool
function DataModel:IsGearTypeAllowed(gearType) end


---@return bool
function DataModel:IsLoaded() end


---@return bool
function DataModel:IsUniverseMetadataLoaded() end

---@param url Content
function DataModel:Load(url) end


function DataModel:OpenScreenshotsFolder() end


function DataModel:OpenVideosFolder() end

---@param category string
---@param action string
---@param label string
---@param value int
function DataModel:ReportInGoogleAnalytics(category, action, label, value) end

---@param name string
---@param newValue bool
---@return bool
function DataModel:SetFastFlagForTesting(name, newValue) end

---@param name string
---@param newValue int
---@return int
function DataModel:SetFastIntForTesting(name, newValue) end

---@param name string
---@param newValue string
---@return string
function DataModel:SetFastStringForTesting(name, newValue) end

---@param name string
---@param version int
function DataModel:SetFlagVersion(name, version) end

---@param value bool
---@param placeSizeInBytes int?
function DataModel:SetIsLoaded(value, placeSizeInBytes) end

---@param placeId int64
function DataModel:SetPlaceId(placeId) end

---@param universeId int64
function DataModel:SetUniverseId(universeId) end


function DataModel:Shutdown() end

---@param url Content
---@return Objects
function DataModel:GetObjectsAsync(url) end

---@param url string
---@param httpRequestType HttpRequestType
---@return string
function DataModel:HttpGetAsync(url, httpRequestType) end

---@param url string
---@param data string
---@param contentType string
---@param httpRequestType HttpRequestType
---@return string
function DataModel:HttpPostAsync(url, data, contentType, httpRequestType) end

---@param url Content
---@return Objects
function DataModel:InsertObjectsAndJoinIfLegacyAsync(url) end

---@param saveFilter SaveFilter
---@return bool
function DataModel:SavePlace(saveFilter) end
---@field CreatorId int64
---@field CreatorType CreatorType
---@field ForceR15 bool
---@field GameAvatarType GameAvatarType
---@field GameId int64
---@field GearGenreSetting GearGenreSetting
---@field Genre Genre
---@field IsSFFlagsLoaded bool
---@field JobId string
---@field PlaceId int64
---@field PlaceVersion int
---@field PrivateServerId string
---@field PrivateServerOwnerId int64
---@field R15CollisionType R15CollisionType
---@field VIPServerId string
---@field VIPServerOwnerId int64
---@field Workspace Workspace
---@field lighting Instance
---@field workspace Workspace
