---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DataModelSession: Instance  
DataModelSession = {}

---@field CurrentDataModelType StudioDataModelType
---@field SessionId string
