---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DataModelMesh: Instance  
DataModelMesh = {}

---@field Offset Vector3
---@field Scale Vector3
---@field VertexColor Vector3
