---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DataStoreKeyInfo: Instance  
DataStoreKeyInfo = {}

---@return Dictionary
function DataStoreKeyInfo:GetMetadata() end


---@return Array
function DataStoreKeyInfo:GetUserIds() end
---@field CreatedTime int64
---@field UpdatedTime int64
---@field Version string
