---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DataStoreOptions: Instance  
DataStoreOptions = {}
---@param experimentalFeatures Dictionary
function DataStoreOptions:SetExperimentalFeatures(experimentalFeatures) end
---@field AllScopes bool
