---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum DataStoreRequestType  
DataStoreRequestType = {
  GetAsync = 0
, SetIncrementAsync = 1
, UpdateAsync = 2
, GetSortedAsync = 3
, SetIncrementSortedAsync = 4
, OnUpdate = 5
, ListAsync = 6
, GetVersionAsync = 7
, RemoveVersionAsync = 8
}
