---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Debris: Instance  
Debris = {}
---@param item Instance
---@param lifetime double
function Debris:AddItem(item, lifetime) end

---@param enabled bool
function Debris:SetLegacyMaxItems(enabled) end

---@param item Instance
---@param lifetime double
function Debris:addItem(item, lifetime) end
---@field MaxItems int
