---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DebuggerUIService: Instance  
DebuggerUIService = {}
---@param metaBreakpointId int
function DebuggerUIService:EditBreakpoint(metaBreakpointId) end

---@param expression string
function DebuggerUIService:EditWatch(expression) end

---@param debuggerConnectionId int
---@return bool
function DebuggerUIService:IsConnectionForPlayDataModel(debuggerConnectionId) end

---@param exceptionMessage string
---@param pausedLine int
function DebuggerUIService:OpenExceptionMessagePopup(exceptionMessage, pausedLine) end

---@param guid string
---@param debuggerConnectionId int
---@param line int
---@param showErrorOnFail bool
function DebuggerUIService:OpenScriptAtLine(guid, debuggerConnectionId, line, showErrorOnFail) end


function DebuggerUIService:Pause() end

---@param debuggerConnectionId int
---@param allMarkers bool
function DebuggerUIService:RemoveScriptLineMarkers(debuggerConnectionId, allMarkers) end


function DebuggerUIService:Resume() end

---@param debuggerThreadId int
function DebuggerUIService:SetCurrentThreadId(debuggerThreadId) end

---@param guid string
---@param debuggerConnectionId int
---@param line int
---@param lineMarkerType bool
function DebuggerUIService:SetScriptLineMarker(guid, debuggerConnectionId, line, lineMarkerType) end

---@param expressions Array
function DebuggerUIService:SetWatchExpressions(expressions) end

