---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DebuggerVariable: Instance  
DebuggerVariable = {}
---@param index int
---@return DebuggerVariable
function DebuggerVariable:GetVariableByIndex(index) end

---@param name string
---@return DebuggerVariable
function DebuggerVariable:GetVariableByName(name) end
---@field Name string
---@field Populated bool
---@field Type string
---@field Value string
---@field VariableId int
---@field VariablesCount int
