---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum DebuggerEndReason  
DebuggerEndReason = {
  ClientRequest = 0
, Timeout = 1
, InvalidHost = 2
, Disconnected = 3
, ServerShutdown = 4
, ServerProtocolMismatch = 5
, ConfigurationFailed = 6
, RpcError = 7
}
