---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum DebuggerPauseReason  
DebuggerPauseReason = {
  Unknown = 0
, Requested = 1
, Breakpoint = 2
, Exception = 3
, SingleStep = 4
, Entrypoint = 5
}
