---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DebuggerLuaResponse: Instance  
DebuggerLuaResponse = {}

---@return Variant
function DebuggerLuaResponse:GetArg() end
---@field IsError bool
---@field IsSuccess bool
---@field Message string
---@field RequestId int
---@field Status DebuggerStatus
