---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DebuggerConnectionManager: Instance  
DebuggerConnectionManager = {}
---@param dataModel DataModel
---@return int
function DebuggerConnectionManager:ConnectLocal(dataModel) end

---@param host string
---@param port int
---@return int
function DebuggerConnectionManager:ConnectRemote(host, port) end

---@param connection DebuggerConnection
function DebuggerConnectionManager:FocusConnection(connection) end

---@param id int
---@return DebuggerConnection
function DebuggerConnectionManager:GetConnectionById(id) end
---@field Timeout double
