---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DebugSettings: Instance  
DebugSettings = {}

---@field DataModel int
---@field InstanceCount int
---@field IsScriptStackTracingEnabled bool
---@field JobCount int
---@field PlayerCount int
---@field ReportSoundWarnings bool
---@field RobloxVersion string
---@field TickCountPreciseOverride TickCountSampleMethod
