---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum DebuggerStatus  
DebuggerStatus = {
  Success = 0
, Timeout = 1
, ConnectionLost = 2
, InvalidResponse = 3
, InternalError = 4
, InvalidState = 5
, RpcError = 6
, InvalidArgument = 7
, ConnectionClosed = 8
}
