---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DebuggerBreakpoint: Instance  
DebuggerBreakpoint = {}

---@field Condition string
---@field ContinueExecution bool
---@field IsEnabled bool
---@field Line int
---@field LogExpression string
---@field isContextDependentBreakpoint bool
---@field line int
