---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DebuggerManager: Instance  
DebuggerManager = {}
---@param script Instance
---@return Instance
function DebuggerManager:AddDebugger(script) end


function DebuggerManager:EnableDebugging() end


---@return Objects
function DebuggerManager:GetDebuggers() end


function DebuggerManager:Resume() end


function DebuggerManager:StepIn() end


function DebuggerManager:StepOut() end


function DebuggerManager:StepOver() end
---@field DebuggingEnabled bool
