---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DebuggerConnection: Instance  
DebuggerConnection = {}
---@param script string
---@param line int
---@param breakpoint Breakpoint
function DebuggerConnection:AddBreakpoint(script, line, breakpoint) end


function DebuggerConnection:Close() end

---@param expression string
---@param frame StackFrame
---@param callback Function
---@return int
function DebuggerConnection:EvaluateWatch(expression, frame, callback) end

---@param id int
---@return StackFrame
function DebuggerConnection:GetFrameById(id) end

---@param scriptRef string
---@param status Function
---@return int
function DebuggerConnection:GetSource(scriptRef, status) end

---@param id int
---@return ThreadState
function DebuggerConnection:GetThreadById(id) end

---@param callback Function
---@return int
function DebuggerConnection:GetThreads(callback) end

---@param id int
---@return DebuggerVariable
function DebuggerConnection:GetVariableById(id) end

---@param thread ThreadState
---@param status Function
---@return int
function DebuggerConnection:Pause(thread, status) end

---@param instance Instance
---@param callback Function
---@return int
function DebuggerConnection:Populate(instance, callback) end

---@param breakpoint Breakpoint
function DebuggerConnection:RemoveBreakpoint(breakpoint) end

---@param thread ThreadState
---@param status Function
---@return int
function DebuggerConnection:Resume(thread, status) end

---@param breakMode DebuggerExceptionBreakMode
---@param callback Function
---@return int
function DebuggerConnection:SetExceptionBreakMode(breakMode, callback) end

---@param variable DebuggerVariable
---@param value string
---@param callback Function
---@return int
function DebuggerConnection:SetVariable(variable, value, callback) end

---@param thread ThreadState
---@param callback Function
---@return int
function DebuggerConnection:Step(thread, callback) end

---@param thread ThreadState
---@param callback Function
---@return int
function DebuggerConnection:StepIn(thread, callback) end

---@param thread ThreadState
---@param callback Function
---@return int
function DebuggerConnection:StepOut(thread, callback) end

---@param threadId int
---@param frameNumber int
function DebuggerConnection:UpdateSelectedFrame(threadId, frameNumber) end
---@field ErrorMessage string
---@field HasError bool
---@field Id int
---@field IsPaused bool
