---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Decal: FaceInstance  
Decal = {}

---@field Color3 Color3
---@field LocalTransparencyModifier float
---@field Shiny float
---@field Specular float
---@field Texture Content
---@field Transparency float
---@field ZIndex int
