---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DepthOfFieldEffect: PostEffect  
DepthOfFieldEffect = {}

---@field FarIntensity float
---@field FocusDistance float
---@field InFocusRadius float
---@field NearIntensity float
