---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum DevComputerMovementMode  
DevComputerMovementMode = {
  UserChoice = 0
, KeyboardMouse = 1
, ClickToMove = 2
, Scriptable = 3
}
