---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum DevComputerCameraMovementMode  
DevComputerCameraMovementMode = {
  UserChoice = 0
, Classic = 1
, Follow = 2
, Orbital = 3
, CameraToggle = 4
}
