---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DialogChoice: Instance  
DialogChoice = {}

---@field GoodbyeChoiceActive bool
---@field GoodbyeDialog string
---@field ResponseDialog string
---@field UserDialog string
