---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Dialog: Instance  
Dialog = {}

---@return Objects
function Dialog:GetCurrentPlayers() end

---@param player Instance
---@param isUsing bool
function Dialog:SetPlayerIsUsing(player, isUsing) end

---@param player Instance
---@param dialogChoice Instance
function Dialog:SignalDialogChoiceSelected(player, dialogChoice) end
---@field BehaviorType DialogBehaviorType
---@field ConversationDistance float
---@field GoodbyeChoiceActive bool
---@field GoodbyeDialog string
---@field InUse bool
---@field InitialPrompt string
---@field Purpose DialogPurpose
---@field Tone DialogTone
---@field TriggerDistance float
---@field TriggerOffset Vector3
