---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DockWidgetPluginGui: PluginGui  
DockWidgetPluginGui = {}

function DockWidgetPluginGui:RequestRaise() end
---@field HostWidgetWasRestored bool
