---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DoubleConstrainedValue: ValueBase  
DoubleConstrainedValue = {}

---@field ConstrainedValue double
---@field MaxValue double
---@field MinValue double
---@field Value double
---@field value double
