---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DraftsService: Instance  
DraftsService = {}
---@param scripts Objects
function DraftsService:DiscardEdits(scripts) end

---@param script Instance
---@return DraftStatusCode
function DraftsService:GetDraftStatus(script) end

---@param script Instance
---@return Objects
function DraftsService:GetEditors(script) end

---@param scripts Objects
function DraftsService:RestoreScripts(scripts) end

---@param scripts Objects
function DraftsService:ShowDiffsAgainstBase(scripts) end

---@param scripts Objects
function DraftsService:ShowDiffsAgainstServer(scripts) end

---@param sources Array
---@param scripts Objects
function DraftsService:ShowSourceDiffsAgainstCurrent(sources, scripts) end

---@param scripts Objects
function DraftsService:CommitEdits(scripts) end


---@return Objects
function DraftsService:GetDrafts() end

---@param scripts Objects
function DraftsService:UpdateToLatestVersion(scripts) end

