---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DraggerService: Instance  
DraggerService = {}

---@field AlignDraggedObjects bool
---@field AngleSnapEnabled bool
---@field AngleSnapIncrement float
---@field AnimateHover bool
---@field CollisionsEnabled bool
---@field DraggerCoordinateSpace DraggerCoordinateSpace
---@field DraggerMovementMode DraggerMovementMode
---@field GeometrySnapColor Color3
---@field HoverAnimateFrequency float
---@field HoverLineThickness int
---@field HoverThickness float
---@field JointsEnabled bool
---@field LinearSnapEnabled bool
---@field LinearSnapIncrement float
---@field PartSnapEnabled bool
---@field PivotSnapToGeometry bool
---@field ShowHover bool
---@field ShowPivotIndicator bool
