---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Dragger: Instance  
Dragger = {}
---@param axis Axis
function Dragger:AxisRotate(axis) end

---@param mousePart Instance
---@param pointOnMousePart Vector3
---@param parts Objects
function Dragger:MouseDown(mousePart, pointOnMousePart, parts) end

---@param mouseRay Ray
function Dragger:MouseMove(mouseRay) end


function Dragger:MouseUp() end

