---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum DragDetectorDragStyle  
DragDetectorDragStyle = {
  TranslateLine = 0
, TranslatePlane = 1
, TranslatePlaneOrLine = 2
, TranslateLineOrPlane = 3
, TranslateViewPlane = 4
, RotateAxis = 5
, RotateTrackball = 6
, Scriptable = 7
, BestForDevice = 8
}
