---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class DragDetector: ClickDetector  
DragDetector = {}
---@param priority int
---@param function Function
---@return RBXScriptConnection
function DragDetector:AddConstraintFunction(priority, function) end


---@return CFrame
function DragDetector:GetReferenceFrame() end


function DragDetector:RestartDrag() end

---@param function Function
function DragDetector:SetDragStyleFunction(function) end

---@param function Function
function DragDetector:SetPermissionPolicyFunction(function) end
---@field ActivatedCursorIcon Content
---@field ApplyAtCenterOfMass bool
---@field Axis Vector3
---@field DragFrame CFrame
---@field DragStyle DragDetectorDragStyle
---@field Enabled bool
---@field GamepadModeSwitchKeyCode KeyCode
---@field KeyboardModeSwitchKeyCode KeyCode
---@field MaxDragAngle float
---@field MaxDragTranslation Vector3
---@field MaxForce float
---@field MaxTorque float
---@field MinDragAngle float
---@field MinDragTranslation Vector3
---@field Orientation Vector3
---@field PermissionPolicy DragDetectorPermissionPolicy
---@field PhysicalDragClickedPart Instance
---@field PhysicalDragHitPoint Vector3
---@field PhysicalDragIsInVR bool
---@field PhysicalDragTargetFrame CFrame
---@field ReferenceInstance Instance
---@field ResponseStyle DragDetectorResponseStyle
---@field Responsiveness float
---@field RunLocally bool
---@field SecondaryAxis Vector3
---@field TrackballRadialPullFactor float
---@field TrackballRollFactor float
---@field VRSwitchKeyCode KeyCode
---@field WorldAxis Vector3
---@field WorldSecondaryAxis Vector3
