---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum EasingStyle  
EasingStyle = {
  Linear = 0
, Sine = 1
, Back = 2
, Quad = 3
, Quart = 4
, Quint = 5
, Bounce = 6
, Elastic = 7
, Exponential = 8
, Circular = 9
, Cubic = 10
}
