---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class EchoSoundEffect: SoundEffect  
EchoSoundEffect = {}

---@field Delay float
---@field DryLevel float
---@field Feedback float
---@field WetLevel float
