---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class EditableMesh: DataModelMesh  
EditableMesh = {}
---@param vertexId0 int64
---@param vertexId1 int64
---@param vertexId2 int64
---@return int64
function EditableMesh:AddTriangle(vertexId0, vertexId1, vertexId2) end

---@param p Vector3
---@return int64
function EditableMesh:AddVertex(p) end

---@param point Vector3
---@return Tuple
function EditableMesh:FindClosestPointOnSurface(point) end

---@param toThisPoint Vector3
---@return int64
function EditableMesh:FindClosestVertex(toThisPoint) end

---@param center Vector3
---@param radius float
---@return Array
function EditableMesh:FindVerticesWithinSphere(center, radius) end

---@param triangleId int64
---@return Array
function EditableMesh:GetAdjacentTriangles(triangleId) end

---@param vertexId int64
---@return Array
function EditableMesh:GetAdjacentVertices(vertexId) end

---@param vertexId int64
---@return Vector3
function EditableMesh:GetPosition(vertexId) end

---@param triangleId int64
---@return Tuple
function EditableMesh:GetTriangleVertices(triangleId) end


---@return Array
function EditableMesh:GetTriangles() end

---@param vertexId int64
---@return Vector2
function EditableMesh:GetUV(vertexId) end

---@param vertexId int64
---@return Color3
function EditableMesh:GetVertexColor(vertexId) end

---@param vertexId int64
---@return float
function EditableMesh:GetVertexColorAlpha(vertexId) end

---@param vertexId int64
---@return Vector3
function EditableMesh:GetVertexNormal(vertexId) end


---@return Array
function EditableMesh:GetVertices() end

---@param origin Vector3
---@param direction Vector3
---@return Tuple
function EditableMesh:RaycastLocal(origin, direction) end

---@param triangleId int64
function EditableMesh:RemoveTriangle(triangleId) end

---@param vertexId int64
function EditableMesh:RemoveVertex(vertexId) end

---@param vertexId int64
---@param p Vector3
function EditableMesh:SetPosition(vertexId, p) end

---@param vertexId int64
---@param uv Vector2
function EditableMesh:SetUV(vertexId, uv) end

---@param vertexId int64
---@param color Color3
function EditableMesh:SetVertexColor(vertexId, color) end

---@param vertexId int64
---@param alpha float
function EditableMesh:SetVertexColorAlpha(vertexId, alpha) end

---@param vertexId int64
---@param vnormal Vector3
function EditableMesh:SetVertexNormal(vertexId, vnormal) end

---@param options Dictionary
---@return MeshPart
function EditableMesh:CreateMeshPartAsync(options) end
---@field MeshData SharedString
---@field SkinningEnabled bool
