---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum EnviromentalPhysicsThrottle  
EnviromentalPhysicsThrottle = {
  DefaultAuto = 0
, Disabled = 1
, Always = 2
, Skip2 = 3
, Skip4 = 4
, Skip8 = 5
, Skip16 = 6
}
