---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class EqualizerSoundEffect: SoundEffect  
EqualizerSoundEffect = {}

---@field HighGain float
---@field LowGain float
---@field MidGain float
