---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class EulerRotationCurve: Instance  
EulerRotationCurve = {}
---@param time float
---@return Array
function EulerRotationCurve:GetAnglesAtTime(time) end

---@param time float
---@return CFrame
function EulerRotationCurve:GetRotationAtTime(time) end


---@return FloatCurve
function EulerRotationCurve:X() end


---@return FloatCurve
function EulerRotationCurve:Y() end


---@return FloatCurve
function EulerRotationCurve:Z() end
---@field RotationOrder RotationOrder
