---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class EventIngestService: Instance  
EventIngestService = {}
---@param target string
---@param eventContext string
---@param eventName string
---@param additionalArgs Dictionary
function EventIngestService:SendEventDeferred(target, eventContext, eventName, additionalArgs) end

---@param target string
---@param eventContext string
---@param eventName string
---@param additionalArgs Dictionary
function EventIngestService:SendEventImmediately(target, eventContext, eventName, additionalArgs) end

---@param target string
---@param eventContext string
---@param eventName string
---@param additionalArgs Dictionary
function EventIngestService:SetRBXEvent(target, eventContext, eventName, additionalArgs) end

---@param target string
---@param eventContext string
---@param eventName string
---@param additionalArgs Dictionary
function EventIngestService:SetRBXEventStream(target, eventContext, eventName, additionalArgs) end

