---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ExperienceService: Instance  
ExperienceService = {}
---@param callId string
---@param params Dictionary
---@param successCallback Function
---@param errorCallback Function
function ExperienceService:ExecuteCrossExperienceCall(callId, params, successCallback, errorCallback) end


---@return Dictionary
function ExperienceService:GetPendingJoinAttempt() end

---@param params Dictionary
---@return string
function ExperienceService:LaunchExperience(params) end

---@param params Dictionary
---@param source string
---@return string
function ExperienceService:LaunchExperienceFromSource(params, source) end

---@param params Dictionary
---@param source string
---@param callback Function
function ExperienceService:LaunchExperienceFromSourceWithCallback(params, source, callback) end

---@param callback Function
---@return RBXScriptConnection
function ExperienceService:RegisterForExperienceJoin(callback) end

---@param callback Function
---@return RBXScriptConnection
function ExperienceService:RegisterForExperienceLeave(callback) end

---@param type string
---@param params Dictionary
function ExperienceService:StartCrossExperience(type, params) end

---@param type string
---@param params Dictionary
function ExperienceService:StopCrossExperience(type, params) end

