---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ExperienceStateCaptureService: Instance  
ExperienceStateCaptureService = {}

---@return bool
function ExperienceStateCaptureService:CanEnterCaptureMode() end


function ExperienceStateCaptureService:ResetHighlight() end


function ExperienceStateCaptureService:ToggleCaptureMode() end
---@field HiddenSelectionEnabled bool
---@field IsInBackground bool
---@field IsInCaptureMode bool
