---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ExperienceInviteOptions: Instance  
ExperienceInviteOptions = {}

---@field InviteMessageId string
---@field InviteUser int64
---@field LaunchData string
---@field PromptMessage string
