---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ExperienceNotificationService: Instance  
ExperienceNotificationService = {}

function ExperienceNotificationService:InvokeOptInPromptClosed() end


function ExperienceNotificationService:PromptOptIn() end


---@return bool
function ExperienceNotificationService:CanPromptOptInAsync() end

