---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ExperienceAuthService: Instance  
ExperienceAuthService = {}
---@param guid string
---@param scopes Array
---@param result ScopeCheckResult
---@param metadata Dictionary
function ExperienceAuthService:ScopeCheckUIComplete(guid, scopes, result, metadata) end

