---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Explosion: Instance  
Explosion = {}

---@field BlastPressure float
---@field BlastRadius float
---@field DestroyJointRadiusPercent float
---@field ExplosionType ExplosionType
---@field LocalTransparencyModifier float
---@field Position Vector3
---@field TimeScale float
---@field Visible bool
