---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class FaceAnimatorService: Instance  
FaceAnimatorService = {}

---@return TrackerLodController
function FaceAnimatorService:GetTrackerLodController() end

---@param videoEnabled bool
---@param audioEnabled bool
function FaceAnimatorService:Init(videoEnabled, audioEnabled) end


---@return bool
function FaceAnimatorService:IsStarted() end


function FaceAnimatorService:Start() end


function FaceAnimatorService:Step() end


function FaceAnimatorService:Stop() end
---@field AudioAnimationEnabled bool
---@field FaceTrackingStatusEnum TrackerFaceTrackingStatus
---@field FlipHeadOrientation bool
---@field VideoAnimationEnabled bool
