---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class FacialAnimationRecordingService: Instance  
FacialAnimationRecordingService = {}

---@return bool
function FacialAnimationRecordingService:IsAgeRestricted() end


---@return string
function FacialAnimationRecordingService:CheckOrRequestCameraPermission() end
---@field BiometricDataConsent bool
