---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum FacialAnimationStreamingState  
FacialAnimationStreamingState = {
  None = 0
, Audio = 1
, Video = 2
, Place = 4
, Server = 8
}
