---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class FacialAnimationStreamingServiceV2: Instance  
FacialAnimationStreamingServiceV2 = {}

---@return FacialAnimationStreamingServiceStats
function FacialAnimationStreamingServiceV2:GetStats() end

---@param mask int
---@return bool
function FacialAnimationStreamingServiceV2:IsAudioEnabled(mask) end

---@param mask int
---@return bool
function FacialAnimationStreamingServiceV2:IsPlaceEnabled(mask) end

---@param mask int
---@return bool
function FacialAnimationStreamingServiceV2:IsServerEnabled(mask) end

---@param mask int
---@return bool
function FacialAnimationStreamingServiceV2:IsVideoEnabled(mask) end

---@param userId int64
---@return int
function FacialAnimationStreamingServiceV2:ResolveStateForUser(userId) end
---@field ServiceState int
