---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class FacialAnimationStreamingServiceStats: Instance  
FacialAnimationStreamingServiceStats = {}
---@param label string
---@return int64
function FacialAnimationStreamingServiceStats:Get(label) end

---@param label string
---@param playerId int64
---@return int64
function FacialAnimationStreamingServiceStats:GetWithPlayerId(label, playerId) end

