---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Feature: Instance  
Feature = {}

---@field FaceId NormalId
---@field InOut InOut
---@field LeftRight LeftRight
---@field TopBottom TopBottom
