---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class File: Instance  
File = {}

---@return string
function File:GetBinaryContents() end


---@return Content
function File:GetTemporaryId() end
---@field Size int64
