---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Fire: Instance  
Fire = {}
---@param numFrames int
function Fire:FastForward(numFrames) end
---@field Color Color3
---@field Enabled bool
---@field Heat float
---@field LocalTransparencyModifier float
---@field SecondaryColor Color3
---@field Size float
---@field TimeScale float
---@field heat_xml float
---@field size float
---@field size_xml float
