---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class FloatCurve: Instance  
FloatCurve = {}
---@param index int
---@return FloatCurveKey
function FloatCurve:GetKeyAtIndex(index) end

---@param time float
---@return Array
function FloatCurve:GetKeyIndicesAtTime(time) end


---@return Array
function FloatCurve:GetKeys() end

---@param time float
---@return float?
function FloatCurve:GetValueAtTime(time) end

---@param key FloatCurveKey
---@return Array
function FloatCurve:InsertKey(key) end

---@param startingIndex int
---@param count int
---@return int
function FloatCurve:RemoveKeyAtIndex(startingIndex, count) end

---@param keys Array
---@return int
function FloatCurve:SetKeys(keys) end
---@field Length int
---@field ValuesAndTimes BinaryString
