---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class FloorWire: GuiBase3d  
FloorWire = {}

---@field CycleOffset float
---@field From BasePart
---@field StudsBetweenTextures float
---@field Texture Content
---@field TextureSize Vector2
---@field To BasePart
---@field Velocity float
---@field WireRadius float
