---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum FontWeight  
FontWeight = {
  Thin = 100
, ExtraLight = 200
, Light = 300
, Regular = 400
, Medium = 500
, SemiBold = 600
, Bold = 700
, ExtraBold = 800
, Heavy = 900
}
