---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class FormFactorPart: BasePart  
FormFactorPart = {}

---@field FormFactor FormFactor
---@field formFactor FormFactor
---@field formFactorRaw FormFactor
