---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum FrameStyle  
FrameStyle = {
  Custom = 0
, ChatBlue = 1
, RobloxSquare = 2
, RobloxRound = 3
, ChatGreen = 4
, ChatRed = 5
, DropShadow = 6
}
