---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum FriendStatus  
FriendStatus = {
  Unknown = 0
, NotFriend = 1
, Friend = 2
, FriendRequestSent = 3
, FriendRequestReceived = 4
}
