---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class FunctionalTest: Instance  
FunctionalTest = {}
---@param message string
function FunctionalTest:Error(message) end

---@param message string
function FunctionalTest:Failed(message) end

---@param message string
function FunctionalTest:Pass(message) end

---@param message string
function FunctionalTest:Passed(message) end

---@param message string
function FunctionalTest:Warn(message) end
---@field AllowSleep bool
---@field Description string
---@field HasMigratedSettingsToTestService bool
---@field Is30FpsThrottleEnabled bool
---@field PhysicsEnvironmentalThrottle bool
---@field Timeout double
