---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GamePassService: Instance  
GamePassService = {}
---@param player Player
---@param gamePassId int64
---@return bool
function GamePassService:PlayerHasPass(player, gamePassId) end

