---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GamepadService: Instance  
GamepadService = {}

function GamepadService:DisableGamepadCursor() end

---@param guiObject Instance
function GamepadService:EnableGamepadCursor(guiObject) end


---@return Vector2
function GamepadService:GetGamepadCursorPosition() end

---@param position Vector2
function GamepadService:SetGamepadCursorPosition(position) end
---@field GamepadCursorEnabled bool
