---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GenericChallengeService: Instance  
GenericChallengeService = {}
---@param challengeID string
function GenericChallengeService:SignalChallengeAbandoned(challengeID) end

---@param challengeID string
---@param challengeType string
---@param challengeMetadata string
function GenericChallengeService:SignalChallengeCompleted(challengeID, challengeType, challengeMetadata) end

---@param challengeID string
function GenericChallengeService:SignalChallengeInvalidated(challengeID) end

---@param challengeID string
---@param success bool
function GenericChallengeService:SignalChallengeLoaded(challengeID, success) end

---@param challengeID string
---@param challengeType string
---@param challengeMetadata string
function GenericChallengeService:SignalChallengeRequired(challengeID, challengeType, challengeMetadata) end

