---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GetTextBoundsParams: Instance  
GetTextBoundsParams = {}

---@field Font Font
---@field RichText bool
---@field Size float
---@field Text string
---@field Width float
