---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GlobalDataStore: Instance  
GlobalDataStore = {}
---@param key string
---@param callback Function
---@return RBXScriptConnection
function GlobalDataStore:OnUpdate(key, callback) end

---@param key string
---@param options DataStoreGetOptions
---@return Tuple
function GlobalDataStore:GetAsync(key, options) end

---@param key string
---@param delta int
---@param userIds Array
---@param options DataStoreIncrementOptions
---@return Variant
function GlobalDataStore:IncrementAsync(key, delta, userIds, options) end

---@param key string
---@return Tuple
function GlobalDataStore:RemoveAsync(key) end

---@param key string
---@param value Variant
---@param userIds Array
---@param options DataStoreSetOptions
---@return Variant
function GlobalDataStore:SetAsync(key, value, userIds, options) end

---@param key string
---@param transformFunction Function
---@return Tuple
function GlobalDataStore:UpdateAsync(key, transformFunction) end

