---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GlobalSettings: GenericSettings  
GlobalSettings = {}
---@param name string
---@return bool
function GlobalSettings:GetFFlag(name) end

---@param name string
---@return string
function GlobalSettings:GetFVariable(name) end

