---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum GraphicsMode  
GraphicsMode = {
  Automatic = 1
, Direct3D11 = 2
, OpenGL = 4
, Metal = 5
, Vulkan = 6
, NoGraphics = 9
}
