---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GroupImportData: BaseImportData  
GroupImportData = {}

---@field Anchored bool
---@field ImportAsModelAsset bool
---@field InsertInWorkspace bool
