---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GroupService: Instance  
GroupService = {}
---@param groupId int64
---@return StandardPages
function GroupService:GetAlliesAsync(groupId) end

---@param groupId int64
---@return StandardPages
function GroupService:GetEnemiesAsync(groupId) end

---@param groupId int64
---@return Variant
function GroupService:GetGroupInfoAsync(groupId) end

---@param userId int64
---@return Array
function GroupService:GetGroupsAsync(userId) end

