---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GroundController: ControllerBase  
GroundController = {}

---@field AccelerationLean float
---@field AccelerationTime float
---@field BalanceMaxTorque float
---@field BalanceSpeed float
---@field DecelerationTime float
---@field Friction float
---@field FrictionWeight float
---@field GroundOffset float
---@field StandForce float
---@field StandSpeed float
---@field TurnSpeedFactor float
