---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GuiBase2d: GuiBase  
GuiBase2d = {}

---@field AbsolutePosition Vector2
---@field AbsoluteRotation float
---@field AbsoluteSize Vector2
---@field AutoLocalize bool
---@field ClippedRect Rect
---@field IsNotOccluded bool
---@field Localize bool
---@field RawRect2D Rect
---@field ReplicatedInsertionOrder int
---@field RootLocalizationTable LocalizationTable
---@field SelectionBehaviorDown SelectionBehavior
---@field SelectionBehaviorLeft SelectionBehavior
---@field SelectionBehaviorRight SelectionBehavior
---@field SelectionBehaviorUp SelectionBehavior
---@field SelectionGroup bool
---@field TotalGroupScale float
