---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GuiButton: GuiObject  
GuiButton = {}

---@field AutoButtonColor bool
---@field Modal bool
---@field MouseButton1ClickConnectionCount int
---@field MouseButton1DownConnectionCount int
---@field MouseButton1UpConnectionCount int
---@field MouseButton2ClickConnectionCount int
---@field MouseButton2DownConnectionCount int
---@field MouseButton2UpConnectionCount int
---@field Selected bool
---@field Style ButtonStyle
