---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GuiBase3d: GuiBase  
GuiBase3d = {}

---@field Color BrickColor
---@field Color3 Color3
---@field Transparency float
---@field Visible bool
