---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GuiObject: GuiBase2d  
GuiObject = {}
---@param endPosition UDim2
---@param easingDirection EasingDirection
---@param easingStyle EasingStyle
---@param time float
---@param override bool
---@param callback Function
---@return bool
function GuiObject:TweenPosition(endPosition, easingDirection, easingStyle, time, override, callback) end

---@param endSize UDim2
---@param easingDirection EasingDirection
---@param easingStyle EasingStyle
---@param time float
---@param override bool
---@param callback Function
---@return bool
function GuiObject:TweenSize(endSize, easingDirection, easingStyle, time, override, callback) end

---@param endSize UDim2
---@param endPosition UDim2
---@param easingDirection EasingDirection
---@param easingStyle EasingStyle
---@param time float
---@param override bool
---@param callback Function
---@return bool
function GuiObject:TweenSizeAndPosition(endSize, endPosition, easingDirection, easingStyle, time, override, callback) end
---@field Active bool
---@field AnchorPoint Vector2
---@field AutomaticSize AutomaticSize
---@field BackgroundColor BrickColor
---@field BackgroundColor3 Color3
---@field BackgroundTransparency float
---@field BorderColor BrickColor
---@field BorderColor3 Color3
---@field BorderMode BorderMode
---@field BorderSizePixel int
---@field ClipsDescendants bool
---@field DragBeginConnectionCount int
---@field DragStoppedConnectionCount int
---@field Draggable bool
---@field GuiState GuiState
---@field Interactable bool
---@field LayoutOrder int
---@field MouseEnterConnectionCount int
---@field MouseLeaveConnectionCount int
---@field MouseMovedConnectionCount int
---@field MouseWheelBackwardConnectionCount int
---@field MouseWheelForwardConnectionCount int
---@field NextSelectionDown GuiObject
---@field NextSelectionLeft GuiObject
---@field NextSelectionRight GuiObject
---@field NextSelectionUp GuiObject
---@field Position UDim2
---@field Rotation float
---@field Selectable bool
---@field SelectionImageObject GuiObject
---@field SelectionOrder int
---@field Size UDim2
---@field SizeConstraint SizeConstraint
---@field Transparency float
---@field Visible bool
---@field ZIndex int
