---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class GuiService: Instance  
GuiService = {}
---@param dialog Instance
---@param centerDialogType CenterDialogType
---@param showFunction Function
---@param hideFunction Function
function GuiService:AddCenterDialog(dialog, centerDialogType, showFunction, hideFunction) end

---@param key string
function GuiService:AddKey(key) end

---@param selectionName string
---@param selectionParent Instance
function GuiService:AddSelectionParent(selectionName, selectionParent) end

---@param selectionName string
---@param selections Tuple
function GuiService:AddSelectionTuple(selectionName, selections) end

---@param key SpecialKey
function GuiService:AddSpecialKey(key) end

---@param data string
---@param notificationType int
function GuiService:BroadcastNotification(data, notificationType) end


function GuiService:ClearError() end


function GuiService:CloseInspectMenu() end

---@param input string
---@return bool
function GuiService:CloseStatsBasedOnInputString(input) end

---@param isForced bool
function GuiService:ForceTenFootInterface(isForced) end


---@return int
function GuiService:GetBrickCount() end

---@param position Vector3
---@return Instance
function GuiService:GetClosestDialogToPosition(position) end


---@return bool
function GuiService:GetEmotesMenuOpen() end


---@return ConnectionError
function GuiService:GetErrorCode() end


---@return string
function GuiService:GetErrorMessage() end


---@return ConnectionError
function GuiService:GetErrorType() end


---@return bool
function GuiService:GetGameplayPausedNotificationEnabled() end


---@return Tuple
function GuiService:GetGuiInset() end

---@param guiType GuiType
---@return bool
function GuiService:GetGuiIsVisible(guiType) end


---@return Vector2
function GuiService:GetHardwareSafeViewport() end


---@return bool
function GuiService:GetInspectMenuEnabled() end


---@return Dictionary
function GuiService:GetNotificationTypeList() end


---@return int
function GuiService:GetResolutionScale() end


---@return Dictionary
function GuiService:GetSafeZoneOffsets() end


---@return string
function GuiService:GetUiMessage() end

---@param humanoidDescription Instance
---@param name string
function GuiService:InspectPlayerFromHumanoidDescription(humanoidDescription, name) end

---@param userId int64
function GuiService:InspectPlayerFromUserId(userId) end

---@param userId int64
---@param ctx string
function GuiService:InspectPlayerFromUserIdWithCtx(userId, ctx) end


---@return bool
function GuiService:IsMemoryTrackerEnabled() end


---@return bool
function GuiService:IsTenFootInterface() end

---@param url string
function GuiService:OpenBrowserWindow(url) end

---@param title string
---@param url string
function GuiService:OpenNativeOverlay(title, url) end

---@param dialog Instance
function GuiService:RemoveCenterDialog(dialog) end

---@param key string
function GuiService:RemoveKey(key) end

---@param selectionName string
function GuiService:RemoveSelectionGroup(selectionName) end

---@param key SpecialKey
function GuiService:RemoveSpecialKey(key) end

---@param selectionParent Instance
function GuiService:Select(selectionParent) end

---@param position UDim2
---@param size UDim2
---@param regionName string
function GuiService:SendUIOcclusionMetricsForQueryRegion(position, size, regionName) end

---@param isOpen bool
function GuiService:SetEmotesMenuOpen(isOpen) end

---@param enabled bool
function GuiService:SetGameplayPausedNotificationEnabled(enabled) end

---@param x1 int
---@param y1 int
---@param x2 int
---@param y2 int
function GuiService:SetGlobalGuiInset(x1, y1, x2, y2) end

---@param left float
---@param top float
---@param right float
---@param bottom float
function GuiService:SetHardwareSafeAreaInsets(left, top, right, bottom) end

---@param enabled bool
function GuiService:SetInspectMenuEnabled(enabled) end

---@param open bool
---@param menuName string
function GuiService:SetMenuIsOpen(open, menuName) end

---@param isShown bool
function GuiService:SetPurchasePromptIsShown(isShown) end

---@param top float
---@param bottom float
---@param left float
---@param right float
function GuiService:SetSafeZoneOffsets(top, bottom, left, right) end

---@param topbarInset Rect
function GuiService:SetTopbarInset(topbarInset) end

---@param msgType UiMessageType
---@param uiMessage string
function GuiService:SetUiMessage(msgType, uiMessage) end

---@param input string
---@return bool
function GuiService:ShowStatsBasedOnInputString(input) end


function GuiService:ToggleFullscreen() end

---@param guiType GuiType
function GuiService:ToggleGuiIsVisibleForCaptures(guiType) end

---@param guiType GuiType
function GuiService:ToggleGuiIsVisibleIfAllowed(guiType) end


---@return Vector2
function GuiService:GetScreenResolution() end
---@field AutoSelectGuiEnabled bool
---@field CoreEffectFolder Folder
---@field CoreGuiFolder Folder
---@field CoreGuiNavigationEnabled bool
---@field GuiNavigationEnabled bool
---@field IsModalDialog bool
---@field IsWindows bool
---@field MenuIsOpen bool
---@field PreferredTransparency float
---@field ReducedMotionEnabled bool
---@field SelectedCoreObject GuiObject
---@field SelectedObject GuiObject
---@field TopbarInset Rect
---@field TouchControlsEnabled bool
