---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class HandleAdornment: PVAdornment  
HandleAdornment = {}

---@field AdornCullingMode AdornCullingMode
---@field AlwaysOnTop bool
---@field CFrame CFrame
---@field SizeRelativeOffset Vector3
---@field ZIndex int
