---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Handles: HandlesBase  
Handles = {}

---@field Faces Faces
---@field MouseButton1DownConnectionCount int
---@field MouseButton1UpConnectionCount int
---@field MouseDragConnectionCount int
---@field MouseEnterConnectionCount int
---@field MouseLeaveConnectionCount int
---@field Style HandlesStyle
