---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class HeightmapImporterService: Instance  
HeightmapImporterService = {}

function HeightmapImporterService:CancelImportHeightmap() end

---@param colormapAssetId Content
---@return Tuple
function HeightmapImporterService:IsValidColormap(colormapAssetId) end

---@param heightmapAssetId Content
---@return Tuple
function HeightmapImporterService:IsValidHeightmap(heightmapAssetId) end

---@param paused bool
function HeightmapImporterService:SetImportHeightmapPaused(paused) end

---@param heightmapAssetId Content
---@return Tuple
function HeightmapImporterService:GetHeightmapPreviewAsync(heightmapAssetId) end

---@param region Region3
---@param heightmapAssetId Content
---@param colormapAssetId Content
---@param defaultMaterial Material
function HeightmapImporterService:ImportHeightmap(region, heightmapAssetId, colormapAssetId, defaultMaterial) end

