---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class HiddenSurfaceRemovalAsset: Instance  
HiddenSurfaceRemovalAsset = {}

---@field HSRData BinaryString
---@field HSRMeshIdData BinaryString
