---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Highlight: Instance  
Highlight = {}

---@field Adornee Instance
---@field DepthMode HighlightDepthMode
---@field Enabled bool
---@field FillColor Color3
---@field FillTransparency float
---@field LineThickness int
---@field OutlineColor Color3
---@field OutlineTransparency float
---@field ReservedId ReservedHighlightId
