---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class HingeConstraint: Constraint  
HingeConstraint = {}

---@field ActuatorType ActuatorType
---@field AngularResponsiveness float
---@field AngularSpeed float
---@field AngularVelocity float
---@field CurrentAngle float
---@field LimitsEnabled bool
---@field LowerAngle float
---@field MotorMaxAcceleration float
---@field MotorMaxTorque float
---@field Radius float
---@field Restitution float
---@field ServoMaxTorque float
---@field SoftlockServoUponReachingTarget bool
---@field TargetAngle float
---@field UpperAngle float
