---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class HopperBin: BackpackItem  
HopperBin = {}

function HopperBin:Disable() end


function HopperBin:ToggleSelect() end
---@field Active bool
---@field BinType BinType
---@field Command string
---@field TextureName string
