---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum HttpError  
HttpError = {
  OK = 0
, InvalidUrl = 1
, DnsResolve = 2
, ConnectFail = 3
, OutOfMemory = 4
, TimedOut = 5
, TooManyRedirects = 6
, InvalidRedirect = 7
, NetFail = 8
, Aborted = 9
, SslConnectFail = 10
, SslVerificationFail = 11
, Unknown = 12
}
