---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum HttpContentType  
HttpContentType = {
  ApplicationJson = 0
, ApplicationXml = 1
, ApplicationUrlEncoded = 2
, TextPlain = 3
, TextXml = 4
}
