---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum HttpRequestType  
HttpRequestType = {
  Default = 0
, MarketplaceService = 2
, Players = 7
, Chat = 15
, Avatar = 16
, Analytics = 23
, Localization = 25
}
