---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class HttpRequest: Instance  
HttpRequest = {}

function HttpRequest:Cancel() end

---@param callback Function
function HttpRequest:Start(callback) end

