---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Humanoid: Instance  
Humanoid = {}
---@param accessory Instance
function Humanoid:AddAccessory(accessory) end

---@param status string
---@return bool
function Humanoid:AddCustomStatus(status) end

---@param status Status
---@return bool
function Humanoid:AddStatus(status) end


function Humanoid:BuildRigFromAttachments() end


function Humanoid:CacheDefaults() end

---@param state HumanoidStateType
function Humanoid:ChangeState(state) end

---@param tool Instance
function Humanoid:EquipTool(tool) end


---@return Array
function Humanoid:GetAccessories() end

---@param instance Instance
---@param partType BodyPartR15
---@return Vector3
function Humanoid:GetAccessoryHandleScale(instance, partType) end


---@return HumanoidDescription
function Humanoid:GetAppliedDescription() end

---@param part Instance
---@return BodyPartR15
function Humanoid:GetBodyPartR15(part) end

---@param part Instance
---@return Limb
function Humanoid:GetLimb(part) end


---@return Vector3
function Humanoid:GetMoveVelocity() end


---@return Array
function Humanoid:GetPlayingAnimationTracks() end


---@return HumanoidStateType
function Humanoid:GetState() end

---@param state HumanoidStateType
---@return bool
function Humanoid:GetStateEnabled(state) end


---@return Array
function Humanoid:GetStatuses() end

---@param status string
---@return bool
function Humanoid:HasCustomStatus(status) end

---@param status Status
---@return bool
function Humanoid:HasStatus(status) end

---@param animation Animation
---@return AnimationTrack
function Humanoid:LoadAnimation(animation) end

---@param moveDirection Vector3
---@param relativeToCamera bool
function Humanoid:Move(moveDirection, relativeToCamera) end

---@param location Vector3
---@param part Instance
function Humanoid:MoveTo(location, part) end


function Humanoid:RemoveAccessories() end

---@param status string
---@return bool
function Humanoid:RemoveCustomStatus(status) end

---@param status Status
---@return bool
function Humanoid:RemoveStatus(status) end

---@param bodyPart BodyPartR15
---@param part BasePart
---@return bool
function Humanoid:ReplaceBodyPartR15(bodyPart, part) end

---@param enabled bool
function Humanoid:SetClickToWalkEnabled(enabled) end

---@param state HumanoidStateType
---@param enabled bool
function Humanoid:SetStateEnabled(state, enabled) end

---@param amount float
function Humanoid:TakeDamage(amount) end


function Humanoid:UnequipTools() end

---@param animation Animation
---@return AnimationTrack
function Humanoid:loadAnimation(animation) end

---@param amount float
function Humanoid:takeDamage(amount) end

---@param humanoidDescription HumanoidDescription
---@param assetTypeVerification AssetTypeVerification
function Humanoid:ApplyDescription(humanoidDescription, assetTypeVerification) end

---@param humanoidDescription HumanoidDescription
function Humanoid:ApplyDescriptionClientServer(humanoidDescription) end

---@param humanoidDescription HumanoidDescription
---@param assetTypeVerification AssetTypeVerification
function Humanoid:ApplyDescriptionReset(humanoidDescription, assetTypeVerification) end

---@param emoteName string
---@return bool
function Humanoid:PlayEmote(emoteName) end

---@param emoteId int64
---@return Tuple
function Humanoid:PlayEmoteAndGetAnimTrackById(emoteId) end
---@field AutoJumpEnabled bool
---@field AutoRotate bool
---@field AutomaticScalingEnabled bool
---@field BreakJointsOnDeath bool
---@field CameraMaxDistance float
---@field CameraMinDistance float
---@field CameraMode CameraMode
---@field CameraOffset Vector3
---@field CollisionType HumanoidCollisionType
---@field DisplayDistanceType HumanoidDisplayDistanceType
---@field DisplayName string
---@field EvaluateStateMachine bool
---@field FloorMaterial Material
---@field Health float
---@field HealthDisplayDistance float
---@field HealthDisplayType HumanoidHealthDisplayType
---@field Health_XML float
---@field HipHeight float
---@field InternalBodyScale Vector3
---@field InternalDisplayName string
---@field InternalHeadScale float
---@field InternalOriginalHipHeight float
---@field Jump bool
---@field JumpHeight float
---@field JumpPower float
---@field JumpReplicate bool
---@field LeftLeg BasePart
---@field MaxHealth float
---@field MaxSlopeAngle float
---@field MoveDirection Vector3
---@field MoveDirectionInternal Vector3
---@field NameDisplayDistance float
---@field NameOcclusion NameOcclusion
---@field NetworkHumanoidState HumanoidStateType
---@field PlatformStand bool
---@field RequiresNeck bool
---@field RigType HumanoidRigType
---@field RightLeg BasePart
---@field RootPart BasePart
---@field SeatPart BasePart
---@field Sit bool
---@field Strafe bool
---@field TargetPoint Vector3
---@field Torso BasePart
---@field UseJumpPower bool
---@field WalkAngleError float
---@field WalkDirection Vector3
---@field WalkSpeed float
---@field WalkToPart BasePart
---@field WalkToPoint Vector3
---@field maxHealth float
