---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum IKCollisionsMode  
IKCollisionsMode = {
  NoCollisions = 0
, OtherMechanismsAnchored = 1
, IncludeContactedMechanisms = 2
}
