---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class IKControl: Instance  
IKControl = {}

---@return int
function IKControl:GetChainCount() end


---@return float
function IKControl:GetChainLength() end

---@param index int
---@return CFrame
function IKControl:GetNodeLocalCFrame(index) end

---@param index int
---@return CFrame
function IKControl:GetNodeWorldCFrame(index) end


---@return CFrame
function IKControl:GetRawFinalTarget() end


---@return CFrame
function IKControl:GetSmoothedFinalTarget() end
---@field ChainRoot Instance
---@field Enabled bool
---@field EndEffector Instance
---@field EndEffectorOffset CFrame
---@field Offset CFrame
---@field Pole Instance
---@field Priority int
---@field SmoothTime float
---@field Target Instance
---@field Type IKControlType
---@field Weight float
