---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum ImageCombineType  
ImageCombineType = {
  BlendSourceOver = 1
, Overwrite = 2
, Add = 3
, Multiply = 4
, AlphaBlend = 5
}
