---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ImageButton: GuiButton  
ImageButton = {}
---@param enabled bool
function ImageButton:SetEnableContentImageSizeChangedEvents(enabled) end
---@field ContentImageSize Vector2
---@field HoverImage Content
---@field Image Content
---@field ImageColor3 Color3
---@field ImageRectOffset Vector2
---@field ImageRectSize Vector2
---@field ImageTransparency float
---@field IsLoaded bool
---@field PressedImage Content
---@field ResampleMode ResamplerMode
---@field ScaleType ScaleType
---@field SliceCenter Rect
---@field SliceScale float
---@field TileSize UDim2
