---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ImageLabel: GuiLabel  
ImageLabel = {}
---@param enabled bool
function ImageLabel:SetEnableContentImageSizeChangedEvents(enabled) end
---@field ContentImageSize Vector2
---@field Image Content
---@field ImageColor3 Color3
---@field ImageRectOffset Vector2
---@field ImageRectSize Vector2
---@field ImageTransparency float
---@field IsLoaded bool
---@field ResampleMode ResamplerMode
---@field ScaleType ScaleType
---@field SliceCenter Rect
---@field SliceScale float
---@field TileSize UDim2
