---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class IncrementalPatchBuilder: Instance  
IncrementalPatchBuilder = {}

---@field AddPathsToBundle bool
---@field BuildDebouncePeriod double
---@field HighCompression bool
---@field SerializePatch bool
---@field ZstdCompression bool
