---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class InputObject: Instance  
InputObject = {}
---@param modifierKey ModifierKey
---@return bool
function InputObject:IsModifierKeyDown(modifierKey) end
---@field Delta Vector3
---@field KeyCode KeyCode
---@field Position Vector3
---@field UserInputState UserInputState
---@field UserInputType UserInputType
