---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class InsertService: Instance  
InsertService = {}
---@param assetId int64
function InsertService:ApproveAssetId(assetId) end

---@param assetVersionId int64
function InsertService:ApproveAssetVersionId(assetVersionId) end

---@param contentId string
---@return string
function InsertService:GetLocalFileContents(contentId) end

---@param instance Instance
function InsertService:Insert(instance) end

---@param assetPath string
---@return Instance
function InsertService:LoadLocalAsset(assetPath) end

---@param url Content
---@return Objects
function InsertService:LoadPackageAsset(url) end

---@param meshId Content
---@param collisionFidelity CollisionFidelity
---@param renderFidelity RenderFidelity
---@return MeshPart
function InsertService:CreateMeshPartAsync(meshId, collisionFidelity, renderFidelity) end


---@return Array
function InsertService:GetBaseCategories() end


---@return Array
function InsertService:GetBaseSets() end

---@param categoryId int64
---@return Array
function InsertService:GetCollection(categoryId) end

---@param searchText string
---@param pageNum int
---@return Array
function InsertService:GetFreeDecals(searchText, pageNum) end

---@param searchText string
---@param pageNum int
---@return Array
function InsertService:GetFreeModels(searchText, pageNum) end

---@param assetId int64
---@return int64
function InsertService:GetLatestAssetVersionAsync(assetId) end

---@param userId int64
---@return Array
function InsertService:GetUserCategories(userId) end

---@param userId int64
---@return Array
function InsertService:GetUserSets(userId) end

---@param assetId int64
---@return Instance
function InsertService:LoadAsset(assetId) end

---@param assetVersionId int64
---@return Instance
function InsertService:LoadAssetVersion(assetVersionId) end

---@param assetId int64
---@param format string
---@return Objects
function InsertService:LoadAssetWithFormat(assetId, format) end

---@param url Content
---@return Objects
function InsertService:LoadPackageAssetAsync(url) end

---@param assetId int64
---@return Instance
function InsertService:loadAsset(assetId) end
---@field AllowClientInsertModels bool
---@field AllowInsertFreeModels bool
