---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class IntConstrainedValue: ValueBase  
IntConstrainedValue = {}

---@field ConstrainedValue int64
---@field MaxValue int64
---@field MinValue int64
---@field Value int64
---@field value int64
