---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class InternalSyncItem: Instance  
InternalSyncItem = {}

---@field AutoSync bool
---@field Enabled bool
---@field Path string
---@field Target Instance
