---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum IXPLoadingStatus  
IXPLoadingStatus = {
  None = 0
, Pending = 1
, Initialized = 2
, ErrorInvalidUser = 3
, ErrorConnection = 4
, ErrorJsonParse = 5
, ErrorTimedOut = 6
}
