---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class IXPService: Instance  
IXPService = {}

function IXPService:ClearUserLayers() end


---@return IXPLoadingStatus
function IXPService:GetBrowserTrackerLayerLoadingStatus() end

---@param layerName string
---@return Dictionary
function IXPService:GetBrowserTrackerLayerVariables(layerName) end

---@param layerName string
---@return IXPLoadingStatus?
function IXPService:GetBrowserTrackerStatusForLayer(layerName) end


---@return Dictionary
function IXPService:GetRegisteredUserLayersToStatus() end


---@return IXPLoadingStatus
function IXPService:GetUserLayerLoadingStatus() end

---@param layerName string
---@return Dictionary
function IXPService:GetUserLayerVariables(layerName) end

---@param layerName string
---@return IXPLoadingStatus?
function IXPService:GetUserStatusForLayer(layerName) end

---@param userId int64
function IXPService:InitializeUserLayers(userId) end

---@param layerName string
function IXPService:LogBrowserTrackerLayerExposure(layerName) end

---@param layerName string
function IXPService:LogUserLayerExposure(layerName) end

---@param userLayers Variant
function IXPService:RegisterUserLayers(userLayers) end

