---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class JointInstance: Instance  
JointInstance = {}

---@field Active bool
---@field C0 CFrame
---@field C1 CFrame
---@field Enabled bool
---@field Part0 BasePart
---@field Part1 BasePart
---@field part1 BasePart
