---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class JointsService: Instance  
JointsService = {}

function JointsService:ClearJoinAfterMoveJoints() end


function JointsService:CreateJoinAfterMoveJoints() end

---@param joinInstance Instance
function JointsService:SetJoinAfterMoveInstance(joinInstance) end

---@param joinTarget Instance
function JointsService:SetJoinAfterMoveTarget(joinTarget) end


function JointsService:ShowPermissibleJoints() end

