---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class KeyframeSequenceProvider: Instance  
KeyframeSequenceProvider = {}
---@param assetId Content
---@return Instance
function KeyframeSequenceProvider:GetKeyframeSequence(assetId) end

---@param assetId int64
---@param useCache bool
---@return Instance
function KeyframeSequenceProvider:GetKeyframeSequenceById(assetId, useCache) end


---@return Dictionary
function KeyframeSequenceProvider:GetMemStats() end

---@param keyframeSequence Instance
---@return Content
function KeyframeSequenceProvider:RegisterActiveKeyframeSequence(keyframeSequence) end

---@param keyframeSequence Instance
---@return Content
function KeyframeSequenceProvider:RegisterKeyframeSequence(keyframeSequence) end

---@param userId int64
---@return Instance
function KeyframeSequenceProvider:GetAnimations(userId) end

---@param assetId Content
---@return Instance
function KeyframeSequenceProvider:GetKeyframeSequenceAsync(assetId) end

