---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Keyframe: Instance  
Keyframe = {}
---@param marker Instance
function Keyframe:AddMarker(marker) end

---@param pose Instance
function Keyframe:AddPose(pose) end


---@return Objects
function Keyframe:GetMarkers() end


---@return Objects
function Keyframe:GetPoses() end

---@param marker Instance
function Keyframe:RemoveMarker(marker) end

---@param pose Instance
function Keyframe:RemovePose(pose) end
---@field Time float
