---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class KeyframeSequence: AnimationClip  
KeyframeSequence = {}
---@param keyframe Instance
function KeyframeSequence:AddKeyframe(keyframe) end


---@return Objects
function KeyframeSequence:GetKeyframes() end

---@param keyframe Instance
function KeyframeSequence:RemoveKeyframe(keyframe) end
---@field AuthoredHipHeight float
