---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class LayerCollector: GuiBase2d  
LayerCollector = {}
---@param x int
---@param y int
---@return Objects
function LayerCollector:GetGuiObjectsAtPosition(x, y) end


---@return Dictionary
function LayerCollector:GetLayoutNodeTree() end
---@field Enabled bool
---@field ResetOnSpawn bool
---@field ZIndexBehavior ZIndexBehavior
