---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Lighting: Instance  
Lighting = {}

---@return double
function Lighting:GetMinutesAfterMidnight() end


---@return Vector3
function Lighting:GetMoonDirection() end


---@return float
function Lighting:GetMoonPhase() end


---@return Vector3
function Lighting:GetSunDirection() end

---@param minutes double
function Lighting:SetMinutesAfterMidnight(minutes) end


---@return double
function Lighting:getMinutesAfterMidnight() end

---@param minutes double
function Lighting:setMinutesAfterMidnight(minutes) end
---@field Ambient Color3
---@field Brightness float
---@field ClockTime float
---@field ColorShift_Bottom Color3
---@field ColorShift_Top Color3
---@field EnvironmentDiffuseScale float
---@field EnvironmentSpecularScale float
---@field ExposureCompensation float
---@field FogColor Color3
---@field FogEnd float
---@field FogStart float
---@field GeographicLatitude float
---@field GlobalShadows bool
---@field OutdoorAmbient Color3
---@field Outlines bool
---@field ShadowColor Color3
---@field ShadowSoftness float
---@field Technology Technology
---@field TempUseNewSkyRemovalBehaviour bool
---@field TimeOfDay string
