---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Light: Instance  
Light = {}

---@field Brightness float
---@field Color Color3
---@field Enabled bool
---@field Shadows bool
