---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class LineForce: Constraint  
LineForce = {}

---@field ApplyAtCenterOfMass bool
---@field InverseSquareLaw bool
---@field Magnitude float
---@field MaxForce float
---@field ReactionForceEnabled bool
