---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class LinearVelocity: Constraint  
LinearVelocity = {}

---@field ForceLimitMode ForceLimitMode
---@field ForceLimitsEnabled bool
---@field LineDirection Vector3
---@field LineVelocity float
---@field MaxAxesForce Vector3
---@field MaxForce float
---@field MaxPlanarAxesForce Vector2
---@field PlaneVelocity Vector2
---@field PrimaryTangentAxis Vector3
---@field RelativeTo ActuatorRelativeTo
---@field SecondaryTangentAxis Vector3
---@field VectorVelocity Vector3
---@field VelocityConstraintMode VelocityConstraintMode
