---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class LinkingService: Instance  
LinkingService = {}
---@param url string
function LinkingService:DetectUrl(url) end


---@return Dictionary
function LinkingService:GetAndClearLastPendingUrl() end


---@return string?
function LinkingService:GetLastLuaUrl() end

---@param url string
---@return bool
function LinkingService:IsUrlRegistered(url) end

---@param url string
function LinkingService:RegisterLuaUrl(url) end


---@return Dictionary?
function LinkingService:StartLuaUrlDelivery() end


function LinkingService:StopLuaUrlDelivery() end

---@param url string
---@return bool
function LinkingService:OpenUrl(url) end


---@return bool
function LinkingService:SupportsSwitchToSettingsApp() end

---@param route string?
function LinkingService:SwitchToSettingsApp(route) end

