---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum LiveEditingAtomicUpdateResponse  
LiveEditingAtomicUpdateResponse = {
  Success = 0
, FailureGuidNotFound = 1
, FailureHashMismatch = 2
, FailureOperationIllegal = 3
}
