---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class LocalizationTable: Instance  
LocalizationTable = {}

---@return string
function LocalizationTable:GetContents() end


---@return Array
function LocalizationTable:GetEntries() end

---@param targetLocaleId string
---@param key string
---@return string
function LocalizationTable:GetString(targetLocaleId, key) end

---@param localeId string
---@return Instance
function LocalizationTable:GetTranslator(localeId) end

---@param key string
---@param source string
---@param context string
function LocalizationTable:RemoveEntry(key, source, context) end

---@param key string
---@param source string
---@param context string
---@param localeId string
function LocalizationTable:RemoveEntryValue(key, source, context, localeId) end

---@param key string
function LocalizationTable:RemoveKey(key) end

---@param localeId string
function LocalizationTable:RemoveTargetLocale(localeId) end

---@param contents string
function LocalizationTable:SetContents(contents) end

---@param entries Variant
function LocalizationTable:SetEntries(entries) end

---@param key string
---@param targetLocaleId string
---@param text string
function LocalizationTable:SetEntry(key, targetLocaleId, text) end

---@param key string
---@param source string
---@param context string
---@param newContext string
function LocalizationTable:SetEntryContext(key, source, context, newContext) end

---@param key string
---@param source string
---@param context string
---@param example string
function LocalizationTable:SetEntryExample(key, source, context, example) end

---@param key string
---@param source string
---@param context string
---@param newKey string
function LocalizationTable:SetEntryKey(key, source, context, newKey) end

---@param key string
---@param source string
---@param context string
---@param newSource string
function LocalizationTable:SetEntrySource(key, source, context, newSource) end

---@param key string
---@param source string
---@param context string
---@param localeId string
---@param text string
function LocalizationTable:SetEntryValue(key, source, context, localeId, text) end

---@param value bool
function LocalizationTable:SetIsExemptFromUGCAnalytics(value) end
---@field Contents string
---@field DevelopmentLanguage string
---@field IsExemptFromUGCAnalytics bool
---@field Root Instance
---@field SourceLocaleId string
