---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class LocalizationService: Instance  
LocalizationService = {}

---@return Objects
function LocalizationService:GetCorescriptLocalizations() end

---@param instance Instance
---@return Array
function LocalizationService:GetTableEntries(instance) end

---@param player Instance
---@return Instance
function LocalizationService:GetTranslatorForPlayer(player) end

---@param locale string
function LocalizationService:SetRobloxLocaleId(locale) end


function LocalizationService:StartTextScraper() end


function LocalizationService:StopTextScraper() end

---@param player Instance
---@return string
function LocalizationService:GetCountryRegionForPlayerAsync(player) end

---@param locale string
---@return Instance
function LocalizationService:GetTranslatorForLocaleAsync(locale) end

---@param player Instance
---@return Instance
function LocalizationService:GetTranslatorForPlayerAsync(player) end

---@param table Instance
function LocalizationService:PromptDownloadGameTableToCSV(table) end


function LocalizationService:PromptExportToCSVs() end


function LocalizationService:PromptImportFromCSVs() end


---@return Instance
function LocalizationService:PromptUploadCSVToGameTable() end
---@field ForcePlayModeGameLocaleId string
---@field ForcePlayModeRobloxLocaleId string
---@field GameSourceLanguageId string
---@field IsTextScraperRunning bool
---@field LocaleManifest string
---@field RobloxForcePlayModeGameLocaleId string
---@field RobloxForcePlayModeRobloxLocaleId string
---@field RobloxLocaleId string
---@field ShouldUseCloudTable bool
---@field SystemLocaleId string
