---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class LocalStorageService: Instance  
LocalStorageService = {}

function LocalStorageService:Flush() end

---@param key string
---@return string
function LocalStorageService:GetItem(key) end

---@param key string
---@param value string
function LocalStorageService:SetItem(key, value) end

---@param callback Function
function LocalStorageService:WhenLoaded(callback) end

