---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class LodDataEntity: Instance  
LodDataEntity = {}

---@field EntityData SharedString
---@field EntityLodEnabled bool
---@field EntityPosition CFrame
---@field EntityScale Vector3
---@field EntitySource Instance
