---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class LoginService: Instance  
LoginService = {}

function LoginService:Logout() end


function LoginService:PromptLogin() end

