---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class LogReporterService: Instance  
LogReporterService = {}
---@param fingerprint string
---@param uuid string
---@param desc string
---@param attributes Dictionary
---@param annotations Dictionary
---@return bool
function LogReporterService:ReportLog(fingerprint, uuid, desc, attributes, annotations) end

---@param fingerprint string
---@param uuid string
---@param desc string
---@param attributes Dictionary
---@param annotations Dictionary
---@param numLogs int
---@return bool
function LogReporterService:ReportMultipleLogs(fingerprint, uuid, desc, attributes, annotations, numLogs) end

