---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class LogService: Instance  
LogService = {}

function LogService:ClearOutput() end

---@param source string
function LogService:ExecuteScript(source) end


---@return Array
function LogService:GetHttpResultHistory() end


---@return Array
function LogService:GetLogHistory() end


function LogService:RequestHttpResultApproved() end


function LogService:RequestServerHttpResult() end


function LogService:RequestServerOutput() end

