---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class LuaSourceContainer: Instance  
LuaSourceContainer = {}

---@field CachedRemoteSource ProtectedString
---@field CachedRemoteSourceLoadState int
---@field HasAssociatedDrafts bool
---@field IsDifferentFromFileSystem bool
---@field OriginalScriptGuid string
---@field SandboxedSource ProtectedString
---@field ScriptGuid string
