---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum MarketplaceItemPurchaseStatus  
MarketplaceItemPurchaseStatus = {
  Success = 1
, SystemError = 2
, AlreadyOwned = 3
, InsufficientRobux = 4
, QuantityLimitExceeded = 5
, QuotaExceeded = 6
, NotForSale = 7
, NotAvailableForPurchaser = 8
, PriceMismatch = 9
, SoldOut = 10
, PurchaserIsSeller = 11
, InsufficientMembership = 12
, PlaceInvalid = 13
}
