---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum MarketplaceBulkPurchasePromptStatus  
MarketplaceBulkPurchasePromptStatus = {
  Completed = 1
, Aborted = 2
, Error = 3
}
