---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class MaterialImportData: BaseImportData  
MaterialImportData = {}

---@field DiffuseFilePath string
---@field IsPbr bool
---@field MetalnessFilePath string
---@field NormalFilePath string
---@field RoughnessFilePath string
