---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class MaterialVariant: Instance  
MaterialVariant = {}

---@field AvgMetalness int
---@field AvgRoughness int
---@field BaseMaterial Material
---@field ColorMap Content
---@field CustomPhysicalProperties PhysicalProperties
---@field MaterialPattern MaterialPattern
---@field MetalnessMap Content
---@field NormalMap Content
---@field RoughnessMap Content
---@field StudsPerTile float
---@field TexturePack Content
