---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class MaterialGenerationSession: Instance  
MaterialGenerationSession = {}
---@param prompt string
---@param options Dictionary
---@return Tuple
function MaterialGenerationSession:GenerateImagesAsync(prompt, options) end

---@param imageId string
---@return Dictionary
function MaterialGenerationSession:GenerateMaterialMapsAsync(imageId) end

---@param imageId string
---@return Dictionary
function MaterialGenerationSession:UploadMaterialAsync(imageId) end

