---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum MembershipType  
MembershipType = {
  None = 0
, BuildersClub = 1
, TurboBuildersClub = 2
, OutrageousBuildersClub = 3
, Premium = 4
}
