---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class MemoryStoreService: Instance  
MemoryStoreService = {}
---@param name string
---@return MemoryStoreHashMap
function MemoryStoreService:GetHashMap(name) end

---@param name string
---@param invisibilityTimeout int
---@return MemoryStoreQueue
function MemoryStoreService:GetQueue(name, invisibilityTimeout) end

---@param name string
---@return MemoryStoreSortedMap
function MemoryStoreService:GetSortedMap(name) end

