---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class MemoryStoreHashMap: Instance  
MemoryStoreHashMap = {}
---@param key string
---@return Variant
function MemoryStoreHashMap:GetAsync(key) end

---@param count int
---@return MemoryStoreHashMapPages
function MemoryStoreHashMap:ListItemsAsync(count) end

---@param key string
function MemoryStoreHashMap:RemoveAsync(key) end

---@param key string
---@param value Variant
---@param expiration int64
---@return bool
function MemoryStoreHashMap:SetAsync(key, value, expiration) end

---@param key string
---@param transformFunction Function
---@param expiration int64
---@return Variant
function MemoryStoreHashMap:UpdateAsync(key, transformFunction, expiration) end

