---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class MeshPart: TriangleMeshPart  
MeshPart = {}
---@param meshPart Instance
function MeshPart:ApplyMesh(meshPart) end
---@field AlternateMeshHash int64
---@field DoubleSided bool
---@field EditableMeshString SharedString
---@field HasJointOffset bool
---@field HasSkinnedMesh bool
---@field InitialSize Vector3
---@field JointOffset Vector3
---@field MeshID Content
---@field MeshId Content
---@field PhysicsData BinaryString
---@field RenderFidelity RenderFidelity
---@field RenderFidelityReplicate RenderFidelity
---@field TextureID Content
---@field VertexCount int
