---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class MeshContentProvider: CacheableContentProvider  
MeshContentProvider = {}

---@return Dictionary
function MeshContentProvider:GetContentMemoryData() end

