---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum MeshPartDetailLevel  
MeshPartDetailLevel = {
  DistanceBased = 0
, Level00 = 1
, Level01 = 2
, Level02 = 3
, Level03 = 4
, Level04 = 5
}
