---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class MeshImportData: BaseImportData  
MeshImportData = {}

---@field Anchored bool
---@field CageManifold bool
---@field CageMeshIntersectedPreview bool
---@field CageMeshNotIntersected bool
---@field CageNoOverlappingVertices bool
---@field CageNonManifoldPreview bool
---@field CageOverlappingVerticesPreview bool
---@field CageUVMatched bool
---@field CageUVMisMatchedPreview bool
---@field Dimensions Vector3
---@field DoubleSided bool
---@field IgnoreVertexColors bool
---@field IrrelevantCageModifiedPreview bool
---@field MeshHoleDetectedPreview bool
---@field MeshNoHoleDetected bool
---@field NoIrrelevantCageModified bool
---@field NoOuterCageFarExtendedFromMesh bool
---@field OuterCageFarExtendedFromMeshPreview bool
---@field PolygonCount float
---@field UseImportedPivot bool
