---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class MessagingService: Instance  
MessagingService = {}
---@param topic string
---@param message Variant
function MessagingService:PublishAsync(topic, message) end

---@param topic string
---@param callback Function
---@return RBXScriptConnection
function MessagingService:SubscribeAsync(topic, callback) end

