---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class MetaBreakpointManager: Instance  
MetaBreakpointManager = {}
---@param script Instance
---@param line int
---@param condition Instance
---@return Instance
function MetaBreakpointManager:AddBreakpoint(script, line, condition) end

---@param metaBreakpointId int
---@return MetaBreakpoint
function MetaBreakpointManager:GetBreakpointById(metaBreakpointId) end

---@param metaBreakpointId int
function MetaBreakpointManager:RemoveBreakpointById(metaBreakpointId) end

