---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum ModelStreamingMode  
ModelStreamingMode = {
  Default = 0
, Atomic = 1
, Persistent = 2
, PersistentPerPlayer = 3
, Nonatomic = 4
}
