---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum ModerationStatus  
ModerationStatus = {
  ReviewedApproved = 1
, ReviewedRejected = 2
, NotReviewed = 3
, NotApplicable = 4
, Invalid = 5
}
