---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Model: PVInstance  
Model = {}
---@param playerInstance Player
function Model:AddPersistentPlayer(playerInstance) end


function Model:BreakJoints() end


---@return CFrame
---@return Vector3
function Model:GetBoundingBox() end


---@return Vector3
function Model:GetExtentsSize() end


---@return CFrame
function Model:GetModelCFrame() end


---@return Vector3
function Model:GetModelSize() end


---@return Objects
function Model:GetPersistentPlayers() end


---@return CFrame
function Model:GetPrimaryPartCFrame() end


---@return float
function Model:GetScale() end


function Model:MakeJoints() end

---@param position Vector3
function Model:MoveTo(position) end

---@param playerInstance Player
function Model:RemovePersistentPlayer(playerInstance) end


function Model:ResetOrientationToIdentity() end

---@param newScaleFactor float
function Model:ScaleTo(newScaleFactor) end


function Model:SetIdentityOrientation() end

---@param cframe CFrame
function Model:SetPrimaryPartCFrame(cframe) end

---@param delta Vector3
function Model:TranslateBy(delta) end


function Model:breakJoints() end


function Model:makeJoints() end

---@param location Vector3
function Model:move(location) end

---@param location Vector3
function Model:moveTo(location) end
---@field LevelOfDetail ModelLevelOfDetail
---@field LodEntity LodDataEntity
---@field ModelMeshCFrame CFrame
---@field ModelMeshData SharedString
---@field ModelMeshSize Vector3
---@field ModelStreamingMode ModelStreamingMode
---@field NeedsPivotMigration bool
---@field PrimaryPart BasePart
---@field Scale float
---@field ScaleFactor float
---@field WorldPivot CFrame
---@field WorldPivotData OptionalCoordinateFrame
