---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ModuleScript: LuaSourceContainer  
ModuleScript = {}

---@field Confidential bool
---@field LinkedSource Content
---@field Source ProtectedString
