---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Motor: JointInstance  
Motor = {}
---@param value float
function Motor:SetDesiredAngle(value) end
---@field CurrentAngle float
---@field DesiredAngle float
---@field MaxVelocity float
