---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Mouse: Instance  
Mouse = {}

---@field Hit CFrame
---@field Icon Content
---@field Origin CFrame
---@field Target BasePart
---@field TargetFilter Instance
---@field TargetSurface NormalId
---@field UnitRay Ray
---@field ViewSizeX int
---@field ViewSizeY int
---@field X int
---@field Y int
---@field hit CFrame
---@field target BasePart
