---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class MultipleDocumentInterfaceInstance: Instance  
MultipleDocumentInterfaceInstance = {}

---@field FocusedDataModelSession Instance
