---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class NetworkServer: NetworkPeer  
NetworkServer = {}
---@param toEncrypt string
---@param playerId int64
---@return string
function NetworkServer:EncryptStringForPlayerId(toEncrypt, playerId) end

