---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class NetworkSettings: Instance  
NetworkSettings = {}

---@field EmulatedTotalMemoryInMB int
---@field FreeMemoryMBytes float
---@field HttpProxyEnabled bool
---@field HttpProxyURL string
---@field IncomingReplicationLag double
---@field OpenCertManagerDialog int
---@field PrintJoinSizeBreakdown bool
---@field PrintPhysicsErrors bool
---@field PrintStreamInstanceQuota bool
---@field RandomizeJoinInstanceOrder bool
---@field RenderStreamedRegions bool
---@field ShowActiveAnimationAsset bool
