---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class NoCollisionConstraint: Instance  
NoCollisionConstraint = {}

---@field Enabled bool
---@field Part0 BasePart
---@field Part1 BasePart
