---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Noise: Instance  
Noise = {}
---@param position Vector3
---@param direction Vector3
---@return float
function Noise:SampleDirectional(position, direction) end

---@param position Vector3
---@return float
function Noise:SampleUniform(position) end
---@field NoiseType NoiseType
---@field Seed int
