---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class NotificationService: Instance  
NotificationService = {}
---@param actionType AppShellActionType
function NotificationService:ActionEnabled(actionType) end

---@param actionType AppShellActionType
function NotificationService:ActionTaken(actionType) end

---@param userId int64
function NotificationService:CancelAllNotification(userId) end

---@param userId int64
---@param alertId int
function NotificationService:CancelNotification(userId, alertId) end

---@param userId int64
---@param alertId int
---@param alertMsg string
---@param minutesToFire int
function NotificationService:ScheduleNotification(userId, alertId, alertMsg, minutesToFire) end

---@param appShellFeature AppShellFeature
function NotificationService:SwitchedToAppShellFeature(appShellFeature) end

---@param userId int64
---@return Array
function NotificationService:GetScheduledNotifications(userId) end
---@field IsConnected bool
---@field IsLuaChatEnabled bool
---@field IsLuaGameDetailsEnabled bool
---@field SelectedTheme string
