---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class OmniRecommendationsService: Instance  
OmniRecommendationsService = {}

function OmniRecommendationsService:ClearSessionId() end


---@return string
function OmniRecommendationsService:GetSessionId() end

---@param nextPageToken string
---@return HttpRequest
function OmniRecommendationsService:MakeRequest(nextPageToken) end

