---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class OpenCloudApiV1: Instance  
OpenCloudApiV1 = {}
---@param name string
---@return OpenCloudModel
function OpenCloudApiV1:CreateModel(name) end

---@param user string
---@param userNotification OpenCloudModel
---@return OpenCloudModel
function OpenCloudApiV1:CreateUserNotificationAsync(user, userNotification) end

