---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class OrderedDataStore: GlobalDataStore  
OrderedDataStore = {}
---@param ascending bool
---@param pagesize int
---@param minValue Variant
---@param maxValue Variant
---@return Instance
function OrderedDataStore:GetSortedAsync(ascending, pagesize, minValue, maxValue) end

