---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PackageLink: Instance  
PackageLink = {}

---@field AutoUpdate bool
---@field CanAutoUpdate bool
---@field Creator string
---@field DefaultName string
---@field ModifiedState int
---@field PackageAssetName string
---@field PackageGuid int64
---@field PackageId Content
---@field PackageIdSerialize Content
---@field PermissionLevel PackagePermission
---@field SerializedDefaultAttributes BinaryString
---@field Status string
---@field VersionIdSerialize int64
---@field VersionNumber int64
