---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PackageUIService: Instance  
PackageUIService = {}
---@param uploadUrl string
---@param cloneInstances Objects
---@param originalInstances Objects
function PackageUIService:ConvertToPackageUpload(uploadUrl, cloneInstances, originalInstances) end

---@param packageAssetId int64
---@return Dictionary
function PackageUIService:GetPackageInfo(packageAssetId) end

---@param packageInstance Instance
---@param addUndoWayPoint bool
function PackageUIService:PublishPackage(packageInstance, addUndoWayPoint) end

---@param packageInstance Instance
---@param versionNumber int64
---@return Instance
function PackageUIService:SetPackageVersion(packageInstance, versionNumber) end

