---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Pages: Instance  
Pages = {}

---@return Array
function Pages:GetCurrentPage() end


function Pages:AdvanceToNextPageAsync() end
---@field IsFinished bool
