---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ParabolaAdornment: PVAdornment  
ParabolaAdornment = {}
---@param ignoreDescendentsTable Objects
---@return Tuple
function ParabolaAdornment:FindPartOnParabola(ignoreDescendentsTable) end
---@field A float
---@field B float
---@field C float
---@field Range float
---@field Thickness float
