---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum ParticleFlipbookTextureCompatible  
ParticleFlipbookTextureCompatible = {
  NotCompatible = 0
, Compatible = 1
, Unknown = 2
}
