---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum ParticleOrientation  
ParticleOrientation = {
  FacingCamera = 0
, FacingCameraWorldUp = 1
, VelocityParallel = 2
, VelocityPerpendicular = 3
}
