---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PartOperation: TriangleMeshPart  
PartOperation = {}
---@param source Instance
function PartOperation:SubstituteGeometry(source) end
---@field AssetId Content
---@field CSGMesh2KernelMap SharedString
---@field CSGPropertyData CSGPropertyData
---@field ChildData BinaryString
---@field ChildData2 SharedString
---@field DCDPropertyData CSGPropertyData
---@field FormFactor FormFactor
---@field InitialSize Vector3
---@field ManifoldMesh SharedString
---@field MeshData BinaryString
---@field MeshData2 SharedString
---@field PhysicsData BinaryString
---@field RenderFidelity RenderFidelity
---@field SerializedCSGTree SharedString
---@field SerializedOperationGraph SharedString
---@field SmoothingAngle float
---@field TriangleCount int
---@field UsePartColor bool
