---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PartOperationAsset: Instance  
PartOperationAsset = {}

---@field ChildData BinaryString
---@field MeshData BinaryString
