---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PatchMapping: Instance  
PatchMapping = {}

---@field FlattenTree bool
---@field PatchId string
---@field TargetPath string
