---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PathfindingLink: Instance  
PathfindingLink = {}

---@field Attachment0 Attachment
---@field Attachment1 Attachment
---@field IsBidirectional bool
---@field Label string
