---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum PathStatus  
PathStatus = {
  Success = 0
, NoPath = 5
, ClosestNoPath = 1
, ClosestOutOfRange = 2
, FailStartNotEmpty = 3
, FailFinishNotEmpty = 4
}
