---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Path: Instance  
Path = {}

---@return Array
function Path:GetPointCoordinates() end


---@return Array
function Path:GetWaypoints() end

---@param start int
---@return int
function Path:CheckOcclusionAsync(start) end

---@param start Vector3
---@param finish Vector3
function Path:ComputeAsync(start, finish) end
---@field Status PathStatus
