---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Path2D: GuiBase  
Path2D = {}

---@return Rect
function Path2D:GetBoundingRect() end

---@param index int
---@return Path2DControlPoint
function Path2D:GetControlPoint(index) end


---@return Array
function Path2D:GetControlPoints() end


---@return float
function Path2D:GetLength() end

---@param t float
---@return UDim2
function Path2D:GetPositionOnCurve(t) end

---@param t float
---@return UDim2
function Path2D:GetPositionOnCurveArcLength(t) end


---@return int
function Path2D:GetSegmentCount() end

---@param t float
---@return Vector2
function Path2D:GetTangentOnCurve(t) end

---@param t float
---@return Vector2
function Path2D:GetTangentOnCurveArcLength(t) end

---@param index int
---@param point Path2DControlPoint
function Path2D:InsertControlPoint(index, point) end

---@param index int
function Path2D:RemoveControlPoint(index) end

---@param controlPoints Array
function Path2D:SetControlPoints(controlPoints) end

---@param index int
---@param point Path2DControlPoint
function Path2D:UpdateControlPoint(index, point) end
---@field Color3 Color3
---@field PropertiesSerialize BinaryString
---@field SelectedControlPoint int
---@field SelectedControlPointData Path2DControlPoint
---@field Thickness float
---@field Transparency float
---@field Visible bool
---@field ZIndex int
