---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PausedState: Instance  
PausedState = {}

---@field AllThreadsPaused bool
---@field Reason DebuggerPauseReason
---@field ThreadId int
