---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum PermissionLevelShown  
PermissionLevelShown = {
  Game = 0
, RobloxGame = 1
, RobloxScript = 2
, Studio = 3
, Roblox = 4
}
