---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PermissionsService: Instance  
PermissionsService = {}

---@return bool
function PermissionsService:GetIsThirdPartyAssetAllowed() end


---@return bool
function PermissionsService:GetIsThirdPartyPurchaseAllowed() end


---@return bool
function PermissionsService:GetIsThirdPartyTeleportAllowed() end

---@param assetId string
---@return Array
function PermissionsService:GetPermissions(assetId) end

---@param assetId string
---@param permissions Array
function PermissionsService:SetPermissions(assetId, permissions) end

