---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PlacesService: Instance  
PlacesService = {}

function PlacesService:StartPlaySolo() end


function PlacesService:StopPlaySolo() end

