---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PlatformFriendsService: Instance  
PlatformFriendsService = {}

---@return bool
function PlatformFriendsService:IsInviteFriendsEnabled() end


---@return bool
function PlatformFriendsService:IsProfileEnabled() end


function PlatformFriendsService:ShowInviteFriendsUI() end

---@param platformUserId string
function PlatformFriendsService:ShowProfile(platformUserId) end


---@return Array
function PlatformFriendsService:GetPartyMembers() end

