---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PlatformCloudStorageService: Instance  
PlatformCloudStorageService = {}

---@return bool
function PlatformCloudStorageService:IsUserDataAvailable() end

---@param key string
---@return Dictionary
function PlatformCloudStorageService:GetUserDataAsync(key) end

---@param key string
---@param data Dictionary
function PlatformCloudStorageService:SetUserDataAsync(key, data) end

