---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PlayerEmulatorService: Instance  
PlayerEmulatorService = {}

---@return Dictionary
function PlayerEmulatorService:GetEmulatedPolicyInfo() end

---@param regionCode string
---@return bool
function PlayerEmulatorService:RegionCodeWillHaveAutomaticNonCustomPolicies(regionCode) end

---@param emulatedPolicyInfo Dictionary
function PlayerEmulatorService:SetEmulatedPolicyInfo(emulatedPolicyInfo) end
---@field CustomPoliciesEnabled bool
---@field EmulatedCountryCode string
---@field EmulatedGameLocale string
---@field PlayerEmulationEnabled bool
---@field PseudolocalizationEnabled bool
---@field SerializedEmulatedPolicyInfo BinaryString
