---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Players: Instance  
Players = {}
---@param message string
function Players:Chat(message) end


---@return Player
function Players:CreateLocalPlayer() end

---@param userId int64
---@return Player
function Players:GetPlayerByUserId(userId) end

---@param character Model
---@return Player
function Players:GetPlayerFromCharacter(character) end


---@return Objects
function Players:GetPlayers() end

---@param player Player
---@param reason string
---@param optionalMessage string
function Players:ReportAbuse(player, reason, optionalMessage) end

---@param player Player
---@param jsonTags string
function Players:ReportAbuseV3(player, jsonTags) end


function Players:ResetLocalPlayer() end

---@param style ChatStyle
function Players:SetChatStyle(style) end

---@param userId int64
---@param userName string
---@param displayName string
---@param membershipType MembershipType
---@param isUnder13 bool
function Players:SetLocalPlayerInfo(userId, userName, displayName, membershipType, isUnder13) end

---@param message string
function Players:TeamChat(message) end

---@param message string
---@param player Instance
function Players:WhisperChat(message, player) end


---@return Objects
function Players:getPlayers() end

---@param character Model
---@return Player
function Players:playerFromCharacter(character) end


---@return Objects
function Players:players() end

---@param config Dictionary
function Players:BanAsync(config) end

---@param description HumanoidDescription
---@param rigType HumanoidRigType
---@param assetTypeVerification AssetTypeVerification
---@return Model
function Players:CreateHumanoidModelFromDescription(description, rigType, assetTypeVerification) end

---@param userId int64
---@return Model
function Players:CreateHumanoidModelFromUserId(userId) end

---@param userId int64
---@return BanHistoryPages
function Players:GetBanHistoryAsync(userId) end

---@param userId int64
---@return Model
function Players:GetCharacterAppearanceAsync(userId) end

---@param userId int64
---@return Dictionary
function Players:GetCharacterAppearanceInfoAsync(userId) end

---@param userId int64
---@return FriendPages
function Players:GetFriendsAsync(userId) end

---@param outfitId int64
---@return HumanoidDescription
function Players:GetHumanoidDescriptionFromOutfitId(outfitId) end

---@param userId int64
---@return HumanoidDescription
function Players:GetHumanoidDescriptionFromUserId(userId) end

---@param userId int64
---@return string
function Players:GetNameFromUserIdAsync(userId) end

---@param userName string
---@return int64
function Players:GetUserIdFromNameAsync(userName) end

---@param userId int64
---@param thumbnailType ThumbnailType
---@param thumbnailSize ThumbnailSize
---@return Tuple
function Players:GetUserThumbnailAsync(userId, thumbnailType, thumbnailSize) end

---@param config Dictionary
function Players:UnbanAsync(config) end
---@field BubbleChat bool
---@field CharacterAutoLoads bool
---@field ClassicChat bool
---@field LocalPlayer Player
---@field MaxPlayers int
---@field MaxPlayersInternal int
---@field NumPlayers int
---@field PreferredPlayers int
---@field PreferredPlayersInternal int
---@field RespawnTime float
---@field ServerGitHash string
---@field ServerLogPrefix string
---@field UseStrafingAnimations bool
---@field localPlayer Player
---@field numPlayers int
