---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Player: Instance  
Player = {}
---@param userIds Array
function Player:AddToBlockList(userIds) end


function Player:ClearCharacterAppearance() end

---@param point Vector3
---@return float
function Player:DistanceFromCharacter(point) end

---@param player Player
---@return FriendStatus
function Player:GetFriendStatus(player) end


---@return string
function Player:GetGameSessionID() end


---@return Dictionary
function Player:GetJoinData() end


---@return Mouse
function Player:GetMouse() end


---@return float
function Player:GetNetworkPing() end


---@return bool
function Player:GetUnder13() end


---@return bool
function Player:HasAppearanceLoaded() end


---@return bool
function Player:IsVerified() end

---@param message string
function Player:Kick(message) end

---@param key string
---@return bool
function Player:LoadBoolean(key) end

---@param assetInstance Instance
function Player:LoadCharacterAppearance(assetInstance) end


function Player:LoadData() end

---@param key string
---@return Instance
function Player:LoadInstance(key) end

---@param key string
---@return double
function Player:LoadNumber(key) end

---@param key string
---@return string
function Player:LoadString(key) end

---@param walkDirection Vector3
---@param relativeToCamera bool
function Player:Move(walkDirection, relativeToCamera) end


function Player:RemoveCharacter() end

---@param player Player
function Player:RequestFriendship(player) end

---@param player Player
function Player:RevokeFriendship(player) end

---@param key string
---@param value bool
function Player:SaveBoolean(key, value) end


function Player:SaveData() end

---@param key string
---@param value Instance
function Player:SaveInstance(key, value) end

---@param key string
---@param value double
function Player:SaveNumber(key, value) end

---@param key string
---@param value string
function Player:SaveString(key, value) end

---@param accountAge int
function Player:SetAccountAge(accountAge) end


function Player:SetBlockListInitialized() end

---@param jsonBlob string
function Player:SetCharacterAppearanceJson(jsonBlob) end

---@param locale string
function Player:SetChatTranslationSettingsLocaleId(locale) end

---@param locale string
function Player:SetExperienceSettingsLocaleId(locale) end

---@param membershipType MembershipType
function Player:SetMembershipType(membershipType) end

---@param moderationAccessKey string
function Player:SetModerationAccessKey(moderationAccessKey) end

---@param value bool
function Player:SetSuperSafeChat(value) end

---@param value bool
function Player:SetUnder13(value) end

---@param userId int64
---@param blocked bool
function Player:UpdatePlayerBlocked(userId, blocked) end

---@param key string
---@return bool
function Player:loadBoolean(key) end

---@param key string
---@return Instance
function Player:loadInstance(key) end

---@param key string
---@return double
function Player:loadNumber(key) end

---@param key string
---@return string
function Player:loadString(key) end

---@param key string
---@param value bool
function Player:saveBoolean(key, value) end

---@param key string
---@param value Instance
function Player:saveInstance(key, value) end

---@param key string
---@param value double
function Player:saveNumber(key, value) end

---@param key string
---@param value string
function Player:saveString(key, value) end

---@param maxFriends int
---@return Array
function Player:GetFriendsOnline(maxFriends) end

---@param groupId int64
---@return int
function Player:GetRankInGroup(groupId) end

---@param groupId int64
---@return string
function Player:GetRoleInGroup(groupId) end

---@param userId int64
---@return bool
function Player:IsBestFriendsWith(userId) end

---@param userId int64
---@return bool
function Player:IsFriendsWith(userId) end

---@param groupId int64
---@return bool
function Player:IsInGroup(groupId) end


function Player:LoadCharacter() end


function Player:LoadCharacterBlocking() end

---@param humanoidDescription HumanoidDescription
function Player:LoadCharacterWithHumanoidDescription(humanoidDescription) end

---@param position Vector3
---@param timeOut double
function Player:RequestStreamAroundAsync(position, timeOut) end


---@return bool
function Player:WaitForDataReady() end

---@param userId int64
---@return bool
function Player:isFriendsWith(userId) end


---@return bool
function Player:waitForDataReady() end
---@field AccountAge int
---@field AccountAgeReplicate int
---@field AppearanceDidLoad bool
---@field AutoJumpEnabled bool
---@field CameraMaxZoomDistance float
---@field CameraMinZoomDistance float
---@field CameraMode CameraMode
---@field CanLoadCharacterAppearance bool
---@field Character Model
---@field CharacterAppearance string
---@field CharacterAppearanceId int64
---@field ChararacterRegionId Vector3
---@field ChatMode ChatMode
---@field ChatPrivacyMode ChatPrivacyMode
---@field CloudEditCameraCoordinateFrame CFrame
---@field CloudEditPlayerActive bool
---@field CountryRegionCodeReplicate string
---@field DataComplexity int
---@field DataComplexityLimit int
---@field DataReady bool
---@field DevCameraOcclusionMode DevCameraOcclusionMode
---@field DevComputerCameraMode DevComputerCameraMovementMode
---@field DevComputerMovementMode DevComputerMovementMode
---@field DevEnableMouseLock bool
---@field DevTouchCameraMode DevTouchCameraMovementMode
---@field DevTouchMovementMode DevTouchMovementMode
---@field DisplayName string
---@field FollowUserId int64
---@field FollowUserIdReplicated int64
---@field GameplayPaused bool
---@field Guest bool
---@field HasVerifiedBadge bool
---@field HealthDisplayDistance float
---@field InternalCharacterAppearanceLoaded bool
---@field LocaleId string
---@field MaxSimulationRadius float
---@field MaximumSimulationRadius float
---@field MembershipType MembershipType
---@field MembershipTypeReplicate MembershipType
---@field NameDisplayDistance float
---@field Neutral bool
---@field OsPlatform string
---@field PlatformName string
---@field RawJoinData BinaryString
---@field ReplicationFocus Instance
---@field RespawnLocation SpawnLocation
---@field SimulationRadius float
---@field SuperSafeChatReplicate bool
---@field Team Team
---@field TeamColor BrickColor
---@field Teleported bool
---@field TeleportedIn bool
---@field UnfilteredChat bool
---@field UserId int64
---@field VRDevice string
---@field VREnabled bool
---@field userId int64
