---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PlayerScripts: Instance  
PlayerScripts = {}

function PlayerScripts:ClearComputerCameraMovementModes() end


function PlayerScripts:ClearComputerMovementModes() end


function PlayerScripts:ClearTouchCameraMovementModes() end


function PlayerScripts:ClearTouchMovementModes() end


---@return Array
function PlayerScripts:GetRegisteredComputerCameraMovementModes() end


---@return Array
function PlayerScripts:GetRegisteredComputerMovementModes() end


---@return Array
function PlayerScripts:GetRegisteredTouchCameraMovementModes() end


---@return Array
function PlayerScripts:GetRegisteredTouchMovementModes() end

---@param cameraMovementMode ComputerCameraMovementMode
function PlayerScripts:RegisterComputerCameraMovementMode(cameraMovementMode) end

---@param movementMode ComputerMovementMode
function PlayerScripts:RegisterComputerMovementMode(movementMode) end

---@param cameraMovementMode TouchCameraMovementMode
function PlayerScripts:RegisterTouchCameraMovementMode(cameraMovementMode) end

---@param movementMode TouchMovementMode
function PlayerScripts:RegisterTouchMovementMode(movementMode) end

