---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PlayerGui: BasePlayerGui  
PlayerGui = {}

---@return float
function PlayerGui:GetTopbarTransparency() end

---@param transparency float
function PlayerGui:SetTopbarTransparency(transparency) end
---@field CurrentScreenOrientation ScreenOrientation
---@field ScreenOrientation ScreenOrientation
---@field SelectionImageObject GuiObject
