---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum PlayerActions  
PlayerActions = {
  CharacterForward = 0
, CharacterBackward = 1
, CharacterLeft = 2
, CharacterRight = 3
, CharacterJump = 4
}
