---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PluginManagementService: Instance  
PluginManagementService = {}
---@param pluginId int64
---@param state bool
function PluginManagementService:SetAutoUpdate(pluginId, state) end

---@param pluginName string
---@return int64
function PluginManagementService:GetOTAPluginVersion(pluginName) end

