---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PluginToolbarButton: Instance  
PluginToolbarButton = {}
---@param active bool
function PluginToolbarButton:SetActive(active) end

---@param active bool
function PluginToolbarButton:SetDropdownActive(active) end
---@field ClickableWhenViewportHidden bool
---@field Enabled bool
---@field Icon Content
