---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PluginToolbar: Instance  
PluginToolbar = {}
---@param buttonId string
---@param tooltip string
---@param iconname string
---@param text string
---@return PluginToolbarButton
function PluginToolbar:CreateButton(buttonId, tooltip, iconname, text) end

---@param buttonId string
---@param tooltip string
---@param iconname string
---@param text string
---@return PluginToolbarButton
function PluginToolbar:CreatePopupButton(buttonId, tooltip, iconname, text) end

