---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PluginMenu: Instance  
PluginMenu = {}
---@param action Instance
function PluginMenu:AddAction(action) end

---@param menu Instance
function PluginMenu:AddMenu(menu) end

---@param actionId string
---@param text string
---@param icon string
---@return Instance
function PluginMenu:AddNewAction(actionId, text, icon) end


function PluginMenu:AddSeparator() end


function PluginMenu:Clear() end


---@return Instance
function PluginMenu:ShowAsync() end
---@field Icon string
---@field Title string
