---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PluginAction: Instance  
PluginAction = {}

---@field ActionId string
---@field AllowBinding bool
---@field Checked bool
---@field DefaultShortcut string
---@field Enabled bool
---@field StatusTip string
---@field Text string
