---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PluginManager: Instance  
PluginManager = {}

---@return Instance
function PluginManager:CreatePlugin() end

---@param filePath string
function PluginManager:ExportPlace(filePath) end

---@param filePath string
function PluginManager:ExportSelection(filePath) end

