---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PluginManagerInterface: Instance  
PluginManagerInterface = {}

---@return Instance
function PluginManagerInterface:CreatePlugin() end

---@param filePath string
function PluginManagerInterface:ExportPlace(filePath) end

---@param filePath string
function PluginManagerInterface:ExportSelection(filePath) end

