---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PluginPolicyService: Instance  
PluginPolicyService = {}
---@param pluginName string
---@return Dictionary
function PluginPolicyService:GetPluginPolicy(pluginName) end

