---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PluginGui: LayerCollector  
PluginGui = {}
---@param function Function
function PluginGui:BindToClose(function) end


---@return Vector2
function PluginGui:GetRelativeMousePosition() end
---@field Title string
