---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PluginDragEvent: Instance  
PluginDragEvent = {}

---@field Data string
---@field MimeType string
---@field Position Vector2
---@field Sender string
