---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PolicyService: Instance  
PolicyService = {}
---@param player Instance
---@return Dictionary
function PolicyService:GetPolicyInfoForPlayerAsync(player) end


---@return Dictionary
function PolicyService:GetPolicyInfoForServerRobloxOnlyAsync() end
---@field IsLuobuServer TriStateBoolean
---@field LuobuWhitelisted TriStateBoolean
