---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PoseBase: Instance  
PoseBase = {}

---@field EasingDirection PoseEasingDirection
---@field EasingStyle PoseEasingStyle
---@field Weight float
