---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Pose: PoseBase  
Pose = {}
---@param pose Instance
function Pose:AddSubPose(pose) end


---@return Objects
function Pose:GetSubPoses() end

---@param pose Instance
function Pose:RemoveSubPose(pose) end
---@field CFrame CFrame
---@field MaskWeight float
