---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ProjectFolderService: Instance  
ProjectFolderService = {}
---@param path string
function ProjectFolderService:ExportScripts(path) end

---@param path string
function ProjectFolderService:ImportScripts(path) end


---@return string
function ProjectFolderService:SelectFolder() end

