---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum PromptPublishAssetResult  
PromptPublishAssetResult = {
  Success = 1
, PermissionDenied = 2
, Timeout = 3
, UploadFailed = 4
, NoUserInput = 5
, UnknownFailure = 6
}
