---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum PromptCreateAvatarResult  
PromptCreateAvatarResult = {
  Success = 1
, PermissionDenied = 2
, Timeout = 3
, UploadFailed = 4
, NoUserInput = 5
, InvalidHumanoidDescription = 6
, UGCValidationFailed = 7
, ModeratedName = 8
, MaxOutfits = 9
, UnknownFailure = 10
}
