---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ProximityPrompt: Instance  
ProximityPrompt = {}

function ProximityPrompt:InputHoldBegin() end


function ProximityPrompt:InputHoldEnd() end
---@field ActionText string
---@field AutoLocalize bool
---@field ClickablePrompt bool
---@field Enabled bool
---@field Exclusivity ProximityPromptExclusivity
---@field GamepadKeyCode KeyCode
---@field HoldDuration float
---@field KeyboardKeyCode KeyCode
---@field MaxActivationDistance float
---@field ObjectText string
---@field RequiresLineOfSight bool
---@field RootLocalizationTable LocalizationTable
---@field Style ProximityPromptStyle
---@field UIOffset Vector2
