---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class PVInstance: Instance  
PVInstance = {}

---@return CFrame
function PVInstance:GetPivot() end

---@param targetCFrame CFrame
function PVInstance:PivotTo(targetCFrame) end
---@field Origin CFrame
---@field Pivot Offset CFrame
