---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ReflectionMetadataClass: ReflectionMetadataItem  
ReflectionMetadataClass = {}

---@field ExplorerImageIndex int
---@field ExplorerOrder int
---@field Insertable bool
---@field PreferredParent string
---@field ServiceVisibility ServiceVisibility
