---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ReflectionMetadataItem: Instance  
ReflectionMetadataItem = {}

---@field Browsable bool
---@field ClassCategory string
---@field ClientOnly bool
---@field Constraint string
---@field Deprecated bool
---@field EditingDisabled bool
---@field EditorType string
---@field FFlag string
---@field IsBackend bool
---@field PropertyOrder int
---@field ScriptContext string
---@field ServerOnly bool
---@field SliderScaling string
---@field UIMaximum double
---@field UIMinimum double
---@field UINumTicks double
