---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ReflectionService: Instance  
ReflectionService = {}
---@param name string
---@return Array
function ReflectionService:GetPropertyNames(name) end

