---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class RemoteEvent: BaseRemoteEvent  
RemoteEvent = {}
---@param arguments Tuple
function RemoteEvent:FireAllClients(arguments) end

---@param player Player
---@param arguments Tuple
function RemoteEvent:FireClient(player, arguments) end

---@param arguments Tuple
function RemoteEvent:FireServer(arguments) end

