---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class RemoteFunction: Instance  
RemoteFunction = {}
---@param player Player
---@param arguments Tuple
---@return Tuple
function RemoteFunction:InvokeClient(player, arguments) end

---@param arguments Tuple
---@return Tuple
function RemoteFunction:InvokeServer(arguments) end

