---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class RenderSettings: Instance  
RenderSettings = {}

---@return int
function RenderSettings:GetMaxQualityLevel() end
---@field AutoFRMLevel int
---@field EagerBulkExecution bool
---@field EditQualityLevel QualityLevel
---@field Enable VR Mode bool
---@field EnableFRM bool
---@field ExportMergeByMaterial bool
---@field FrameRateManager FramerateManagerMode
---@field GraphicsMode GraphicsMode
---@field MeshCacheSize int
---@field MeshPartDetailLevel MeshPartDetailLevel
---@field QualityLevel QualityLevel
---@field ReloadAssets bool
---@field RenderCSGTrianglesDebug bool
---@field ShowBoundingBoxes bool
---@field ViewMode ViewMode
