---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class RenderingTest: Instance  
RenderingTest = {}

function RenderingTest:RenderdocTriggerCapture() end
---@field CFrame CFrame
---@field ComparisonDiffThreshold int
---@field ComparisonMethod RenderingTestComparisonMethod
---@field ComparisonPsnrThreshold float
---@field Description string
---@field FieldOfView float
---@field Orientation Vector3
---@field PerfTest bool
---@field Position Vector3
---@field QualityAuto bool
---@field QualityLevel int
---@field RenderingTestFrameCount int
---@field ShouldSkip bool
---@field Ticket string
---@field Timeout int
