---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ReplicatedFirst: Instance  
ReplicatedFirst = {}

---@return bool
function ReplicatedFirst:IsDefaultLoadingGuiRemoved() end


---@return bool
function ReplicatedFirst:IsFinishedReplicating() end


function ReplicatedFirst:RemoveDefaultLoadingScreen() end


function ReplicatedFirst:SetDefaultLoadingGuiRemoved() end

