---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ReverbSoundEffect: SoundEffect  
ReverbSoundEffect = {}

---@field DecayTime float
---@field Density float
---@field Diffusion float
---@field DryLevel float
---@field WetLevel float
