---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class RibbonNotificationService: Instance  
RibbonNotificationService = {}
---@param newNotificationId string
---@param seenNotificationId string
function RibbonNotificationService:OnNotificationUpdateFromPlugin(newNotificationId, seenNotificationId) end

