---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class RocketPropulsion: BodyMover  
RocketPropulsion = {}

function RocketPropulsion:Abort() end


function RocketPropulsion:Fire() end


function RocketPropulsion:fire() end
---@field Active bool
---@field CartoonFactor float
---@field MaxSpeed float
---@field MaxThrust float
---@field MaxTorque Vector3
---@field Target BasePart
---@field TargetOffset Vector3
---@field TargetRadius float
---@field ThrustD float
---@field ThrustP float
---@field TurnD float
---@field TurnP float
