---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class RodConstraint: Constraint  
RodConstraint = {}

---@field CurrentDistance float
---@field Length float
---@field LimitAngle0 float
---@field LimitAngle1 float
---@field LimitsEnabled bool
---@field Thickness float
