---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class RopeConstraint: Constraint  
RopeConstraint = {}

---@field CurrentDistance float
---@field Length float
---@field Restitution float
---@field Thickness float
---@field WinchEnabled bool
---@field WinchForce float
---@field WinchResponsiveness float
---@field WinchSpeed float
---@field WinchTarget float
