---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class RTAnimationTracker: Instance  
RTAnimationTracker = {}

---@field Active bool
---@field EnableFallbackAudioInput bool
---@field SessionName string
---@field TrackerMode TrackerMode
---@field TrackerType TrackerType
