---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class RunService: Instance  
RunService = {}
---@param name string
---@param priority int
---@param function Function
function RunService:BindToRenderStep(name, priority, function) end


---@return string
function RunService:GetCoreScriptVersion() end


---@return string
function RunService:GetRobloxClientChannel() end


---@return bool
function RunService:GetRobloxGuiFocused() end


---@return string
function RunService:GetRobloxVersion() end


---@return bool
function RunService:IsClient() end


---@return bool
function RunService:IsEdit() end


---@return bool
function RunService:IsRunMode() end


---@return bool
function RunService:IsRunning() end


---@return bool
function RunService:IsServer() end


---@return bool
function RunService:IsStudio() end


function RunService:Pause() end


function RunService:Reset() end


function RunService:Run() end

---@param enable bool
function RunService:Set3dRenderingEnabled(enable) end

---@param focus bool
function RunService:SetRobloxGuiFocused(focus) end


function RunService:Stop() end

---@param name string
function RunService:UnbindFromRenderStep(name) end

---@param enable bool
function RunService:setThrottleFramerateEnabled(enable) end
---@field ClientGitHash string
---@field RunState RunState
