---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SafetyService: Instance  
SafetyService = {}
---@param screenshotOptions Dictionary
---@return int64
function SafetyService:TakeScreenshot(screenshotOptions) end
---@field IsCaptureModeForReport bool
