---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum SavedQualitySetting  
SavedQualitySetting = {
  Automatic = 0
, QualityLevel1 = 1
, QualityLevel2 = 2
, QualityLevel3 = 3
, QualityLevel4 = 4
, QualityLevel5 = 5
, QualityLevel6 = 6
, QualityLevel7 = 7
, QualityLevel8 = 8
, QualityLevel9 = 9
, QualityLevel10 = 10
}
