---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum SaveAvatarThumbnailCustomizationFailure  
SaveAvatarThumbnailCustomizationFailure = {
  BadThumbnailType = 1
, BadYRotDeg = 2
, BadFieldOfViewDeg = 3
, BadDistanceScale = 4
, Other = 5
, Throttled = 6
}
