---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ScreenGui: LayerCollector  
ScreenGui = {}

---@field ClipToDeviceSafeArea bool
---@field DisplayOrder int
---@field IgnoreGuiInset bool
---@field OnTopOfCoreBlur bool
---@field SafeAreaCompatibility SafeAreaCompatibility
---@field ScreenInsets ScreenInsets
