---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum ScreenOrientation  
ScreenOrientation = {
  LandscapeLeft = 0
, LandscapeRight = 1
, LandscapeSensor = 2
, Portrait = 3
, Sensor = 4
}
