---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ScreenshotHud: Instance  
ScreenshotHud = {}

---@field CameraButtonIcon Content
---@field CameraButtonPosition UDim2
---@field CloseButtonPosition UDim2
---@field CloseWhenScreenshotTaken bool
---@field ExperienceNameOverlayEnabled bool
---@field HideCoreGuiForCaptures bool
---@field HidePlayerGuiForCaptures bool
---@field OverlayFont Font
---@field UsernameOverlayEnabled bool
---@field Visible bool
