---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ScriptRegistrationService: Instance  
ScriptRegistrationService = {}
---@param guid string
---@return LuaSourceContainer
function ScriptRegistrationService:GetSourceContainerByScriptGuid(guid) end

