---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ScriptProfilerService: Instance  
ScriptProfilerService = {}
---@param player Player
function ScriptProfilerService:ClientRequestData(player) end

---@param player Player
---@param frequency int?
function ScriptProfilerService:ClientStart(player, frequency) end

---@param player Player
function ScriptProfilerService:ClientStop(player) end

---@param jsonString string?
---@return Dictionary
function ScriptProfilerService:DeserializeJSON(jsonString) end

---@param jsonString string
---@param filename string
---@return string
function ScriptProfilerService:SaveScriptProfilingData(jsonString, filename) end


function ScriptProfilerService:ServerRequestData() end

---@param frequency int?
function ScriptProfilerService:ServerStart(frequency) end


function ScriptProfilerService:ServerStop() end

