---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ScriptEditorService: Instance  
ScriptEditorService = {}
---@param name string
function ScriptEditorService:DeregisterAutocompleteCallback(name) end

---@param name string
function ScriptEditorService:DeregisterScriptAnalysisCallback(name) end

---@param script LuaSourceContainer
---@return ScriptDocument
function ScriptEditorService:FindScriptDocument(script) end

---@param uri string
---@param newsrc string
function ScriptEditorService:ForceReloadSource(uri, newsrc) end

---@param script LuaSourceContainer
---@return string
function ScriptEditorService:GetEditorSource(script) end


---@return Objects
function ScriptEditorService:GetScriptDocuments() end

---@param name string
---@return bool
function ScriptEditorService:IsAutocompleteCallbackRegistered(name) end

---@param name string
---@return bool
function ScriptEditorService:IsScriptAnalysisCallbackRegistered(name) end

---@param name string
---@param priority int
---@param callbackFunction Function
function ScriptEditorService:RegisterAutocompleteCallback(name, priority, callbackFunction) end

---@param name string
---@param priority int
---@param callbackFunction Function
function ScriptEditorService:RegisterScriptAnalysisCallback(name, priority, callbackFunction) end

---@param code string
---@return string
function ScriptEditorService:StripComments(code) end

---@param script LuaSourceContainer
---@param newText string
---@param startLine int
---@param startCharacter int
---@param endLine int
---@param endCharacter int
---@return Tuple
function ScriptEditorService:EditSourceAsyncWithRanges(script, newText, startLine, startCharacter, endLine, endCharacter) end

---@param script LuaSourceContainer
---@return Tuple
function ScriptEditorService:OpenScriptDocumentAsync(script) end

---@param script LuaSourceContainer
---@param callback Function
function ScriptEditorService:UpdateSourceAsync(script, callback) end

