---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ScriptDebugger: Instance  
ScriptDebugger = {}
---@param expression string
---@return Instance
function ScriptDebugger:AddWatch(expression) end


---@return Objects
function ScriptDebugger:GetBreakpoints() end

---@param stackFrame int
---@return Map
function ScriptDebugger:GetGlobals(stackFrame) end

---@param stackFrame int
---@return Map
function ScriptDebugger:GetLocals(stackFrame) end


---@return Array
function ScriptDebugger:GetStack() end

---@param stackFrame int
---@return Map
function ScriptDebugger:GetUpvalues(stackFrame) end

---@param watch Instance
---@return Variant
function ScriptDebugger:GetWatchValue(watch) end


---@return Objects
function ScriptDebugger:GetWatches() end

---@param line int
---@param isContextDependentBreakpoint bool
---@return Instance
function ScriptDebugger:SetBreakpoint(line, isContextDependentBreakpoint) end

---@param name string
---@param value Variant
---@param stackFrame int
function ScriptDebugger:SetGlobal(name, value, stackFrame) end

---@param name string
---@param value Variant
---@param stackFrame int
function ScriptDebugger:SetLocal(name, value, stackFrame) end

---@param name string
---@param value Variant
---@param stackFrame int
function ScriptDebugger:SetUpvalue(name, value, stackFrame) end
---@field CoreScriptIdentifier string
---@field CurrentLine int
---@field IsDebugging bool
---@field IsPaused bool
---@field Script Instance
---@field ScriptGuid string
