---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ScrollingFrame: GuiObject  
ScrollingFrame = {}

function ScrollingFrame:ClearInertialScrolling() end


---@return Vector2
function ScrollingFrame:GetSampledInertialVelocity() end


function ScrollingFrame:ScrollToTop() end
---@field AbsoluteCanvasSize Vector2
---@field AbsoluteWindowSize Vector2
---@field AutomaticCanvasSize AutomaticSize
---@field BottomImage Content
---@field CanvasPosition Vector2
---@field CanvasSize UDim2
---@field ElasticBehavior ElasticBehavior
---@field HorizontalBarRect Rect
---@field HorizontalScrollBarInset ScrollBarInset
---@field MaxCanvasPosition Vector2
---@field MidImage Content
---@field ScrollBarImageColor3 Color3
---@field ScrollBarImageTransparency float
---@field ScrollBarThickness int
---@field ScrollVelocity Vector2
---@field ScrollingDirection ScrollingDirection
---@field ScrollingEnabled bool
---@field TopImage Content
---@field VerticalBarRect Rect
---@field VerticalScrollBarInset ScrollBarInset
---@field VerticalScrollBarPosition VerticalScrollBarPosition
