---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Seat: Part  
Seat = {}
---@param humanoid Instance
function Seat:Sit(humanoid) end
---@field Disabled bool
---@field Occupant Humanoid
