---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SelectionSphere: PVAdornment  
SelectionSphere = {}

---@field SurfaceColor BrickColor
---@field SurfaceColor3 Color3
---@field SurfaceTransparency float
