---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SelectionBox: InstanceAdornment  
SelectionBox = {}

---@field LineThickness float
---@field StudioSelectionBox bool
---@field SurfaceColor BrickColor
---@field SurfaceColor3 Color3
---@field SurfaceTransparency float
