---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Selection: Instance  
Selection = {}
---@param instancesToAdd Objects
function Selection:Add(instancesToAdd) end

---@param priority int
---@param function Function
---@return RBXScriptConnection
function Selection:AddFocusCallback(priority, function) end


function Selection:ClearTerrainSelectionHack() end


---@return Objects
function Selection:Get() end

---@param instancesToRemove Objects
function Selection:Remove(instancesToRemove) end

---@param selection Objects
function Selection:Set(selection) end

---@param center Vector3
---@param size Vector3
function Selection:SetTerrainSelectionHack(center, size) end
---@field ActiveInstance Instance
---@field RenderMode SelectionRenderMode
---@field SelectionBoxThickness float
---@field SelectionLineThickness int
---@field SelectionThickness float
---@field ShowActiveInstanceHighlight bool
