---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum SelfViewPosition  
SelfViewPosition = {
  LastPosition = 0
, TopLeft = 1
, TopRight = 2
, BottomLeft = 3
, BottomRight = 4
}
