---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ServiceProvider: Instance  
ServiceProvider = {}
---@param className string
---@return Instance
function ServiceProvider:FindService(className) end

---@param className string
---@return Instance
function ServiceProvider:GetService(className) end

---@param className string
---@return Instance
function ServiceProvider:getService(className) end

---@param className string
---@return Instance
function ServiceProvider:service(className) end

