---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ServiceVisibilityService: Instance  
ServiceVisibilityService = {}

---@field HiddenServices BinaryString
---@field VisibleServices BinaryString
