---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SessionService: Instance  
SessionService = {}
---@param context string
function SessionService:AcquireContextFocus(context) end

---@param includeArbitrarySessions bool
---@param includeTag bool
---@param includeTimestamps bool
---@param includeMetadata bool
---@return string
function SessionService:GenerateSessionInfoString(includeArbitrarySessions, includeTag, includeTimestamps, includeMetadata) end

---@param sid string
---@return int64
function SessionService:GetCreatedTimestampUtcMs(sid) end

---@param sid string
---@param key string
---@return Variant
function SessionService:GetMetadata(sid, key) end


---@return string
function SessionService:GetRootSID() end

---@param sid string
---@return string
function SessionService:GetSessionTag(sid) end

---@param context string
---@return bool
function SessionService:IsContextFocused(context) end

---@param context string
function SessionService:ReleaseContextFocus(context) end

---@param sid string
---@param key string
---@param context string
function SessionService:RemoveMetadata(sid, key, context) end

---@param sid string
---@param context string
function SessionService:RemoveSession(sid, context) end

---@param key string
function SessionService:RemoveSessionsWithMetadataKey(key) end

---@param sid string
---@param tag string
function SessionService:ReplaceSession(sid, tag) end

---@param sid string
---@return bool
function SessionService:SessionExists(sid) end

---@param sid string
---@param key string
---@param value Variant
---@param context string
function SessionService:SetMetadata(sid, key, value, context) end

---@param parentSid string
---@param childSid string
---@param tag string
---@param context string
function SessionService:SetSession(parentSid, childSid, tag, context) end

