---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SharedTableRegistry: Instance  
SharedTableRegistry = {}
---@param name string
---@return SharedTable
function SharedTableRegistry:GetSharedTable(name) end

---@param name string
---@param st SharedTable?
function SharedTableRegistry:SetSharedTable(name, st) end

