---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ShorelineUpgraderService: Instance  
ShorelineUpgraderService = {}

function ShorelineUpgraderService:Cancel() end


function ShorelineUpgraderService:Start() end

