---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SkateboardPlatform: Part  
SkateboardPlatform = {}
---@param impulseWorld Vector3
function SkateboardPlatform:ApplySpecificImpulse(impulseWorld) end
---@field Controller SkateboardController
---@field ControllingHumanoid Humanoid
---@field MoveState MoveState
---@field Steer int
---@field StickyWheels bool
---@field Throttle int
