---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Sky: Instance  
Sky = {}

---@field CelestialBodiesShown bool
---@field MoonAngularSize float
---@field MoonTextureId Content
---@field SkyboxBk Content
---@field SkyboxDn Content
---@field SkyboxFt Content
---@field SkyboxLf Content
---@field SkyboxRt Content
---@field SkyboxUp Content
---@field StarCount int
---@field SunAngularSize float
---@field SunTextureId Content
