---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SlidingBallConstraint: Constraint  
SlidingBallConstraint = {}

---@field ActuatorType ActuatorType
---@field CurrentPosition float
---@field LimitsEnabled bool
---@field LinearResponsiveness float
---@field LowerLimit float
---@field MotorMaxAcceleration float
---@field MotorMaxForce float
---@field Restitution float
---@field ServoMaxForce float
---@field Size float
---@field SoftlockServoUponReachingTarget bool
---@field Speed float
---@field TargetPosition float
---@field UpperLimit float
---@field Velocity float
