---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Smoke: Instance  
Smoke = {}
---@param numFrames int
function Smoke:FastForward(numFrames) end
---@field Color Color3
---@field Enabled bool
---@field LocalTransparencyModifier float
---@field Opacity float
---@field RiseVelocity float
---@field Size float
---@field TimeScale float
---@field opacity_xml float
---@field riseVelocity_xml float
---@field size_xml float
