---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SmoothVoxelsUpgraderService: Instance  
SmoothVoxelsUpgraderService = {}

function SmoothVoxelsUpgraderService:Cancel() end


function SmoothVoxelsUpgraderService:Start() end

