---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SocialService: Instance  
SocialService = {}

function SocialService:HideSelfView() end

---@param player Instance
---@param recipientIds Array
function SocialService:InvokeGameInvitePromptClosed(player, recipientIds) end

---@param player Instance
---@param tag string
---@param irisParticipants Array
function SocialService:InvokeIrisInvite(player, tag, irisParticipants) end

---@param player Instance
function SocialService:InvokeIrisInvitePromptClosed(player) end

---@param player Instance
---@param experienceInviteOptions Instance
function SocialService:PromptGameInvite(player, experienceInviteOptions) end

---@param player Instance
---@param tag string
function SocialService:PromptPhoneBook(player, tag) end

---@param selfViewPosition SelfViewPosition
function SocialService:ShowSelfView(selfViewPosition) end

---@param player Instance
---@return bool
function SocialService:CanSendCallInviteAsync(player) end

---@param player Instance
---@param recipientId int64
---@return bool
function SocialService:CanSendGameInviteAsync(player, recipientId) end

