---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum SolverConvergenceVisualizationMode  
SolverConvergenceVisualizationMode = {
  Disabled = 0
, PerIsland = 1
, PerEdge = 2
}
