---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Sound: Instance  
Sound = {}

function Sound:Pause() end


function Sound:Play() end


function Sound:Resume() end


function Sound:Stop() end


function Sound:pause() end


function Sound:play() end


function Sound:stop() end
---@field ChannelCount int
---@field EmitterSize float
---@field IsLoaded bool
---@field IsPaused bool
---@field IsPlaying bool
---@field IsSpatial bool
---@field LoopRegion NumberRange
---@field Looped bool
---@field MaxDistance float
---@field MinDistance float
---@field Pitch float
---@field PlayOnRemove bool
---@field PlaybackLoudness double
---@field PlaybackRegion NumberRange
---@field PlaybackRegionsEnabled bool
---@field PlaybackSpeed float
---@field Playing bool
---@field PlayingReplicator bool
---@field RollOffGain float
---@field RollOffMaxDistance float
---@field RollOffMinDistance float
---@field RollOffMode RollOffMode
---@field SoundGroup SoundGroup
---@field SoundId Content
---@field TimeLength double
---@field TimePosition double
---@field TimePositionReplicator double
---@field UsageContextPermission UsageContext
---@field Volume float
---@field isPlaying bool
---@field xmlRead_MaxDistance_3 float
---@field xmlRead_MinDistance_3 float
