---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SoundService: Instance  
SoundService = {}

---@return bool
function SoundService:BeginRecording() end


---@return Tuple
function SoundService:GetInputDevice() end


---@return Tuple
function SoundService:GetInputDevices() end


---@return Tuple
function SoundService:GetListener() end


---@return Tuple
function SoundService:GetOutputDevice() end


---@return Tuple
function SoundService:GetOutputDevices() end


---@return Dictionary
function SoundService:GetSoundMemoryData() end

---@param selectedCurveObjects Objects
function SoundService:OpenAttenuationCurveEditor(selectedCurveObjects) end

---@param sound Instance
function SoundService:PlayLocalSound(sound) end

---@param name string
---@param guid string
function SoundService:SetInputDevice(name, guid) end

---@param listenerType ListenerType
---@param listener Tuple
function SoundService:SetListener(listenerType, listener) end

---@param name string
---@param guid string
function SoundService:SetOutputDevice(name, guid) end

---@param deviceIndex int
---@return bool
function SoundService:SetRecordingDevice(deviceIndex) end


---@return Dictionary
function SoundService:EndRecording() end


---@return Dictionary
function SoundService:GetRecordingDevices() end
---@field AmbientReverb ReverbType
---@field DistanceFactor float
---@field DopplerScale float
---@field RespectFilteringEnabled bool
---@field RolloffScale float
---@field VolumetricAudio VolumetricAudio
