---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Sparkles: Instance  
Sparkles = {}
---@param numFrames int
function Sparkles:FastForward(numFrames) end
---@field Color Color3
---@field Enabled bool
---@field LocalTransparencyModifier float
---@field SparkleColor Color3
---@field TimeScale float
