---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SpawnLocation: Part  
SpawnLocation = {}

---@field AllowTeamChangeOnTouch bool
---@field Duration int
---@field Enabled bool
---@field Neutral bool
---@field TeamColor BrickColor
