---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SpringConstraint: Constraint  
SpringConstraint = {}

---@field Coils float
---@field CurrentLength float
---@field Damping float
---@field FreeLength float
---@field LimitsEnabled bool
---@field MaxForce float
---@field MaxLength float
---@field MinLength float
---@field Radius float
---@field Stiffness float
---@field Thickness float
