---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StackFrame: Instance  
StackFrame = {}

---@field FrameId int
---@field FrameName string
---@field FrameType DebuggerFrameType
---@field Globals DebuggerVariable
---@field Line int
---@field Locals DebuggerVariable
---@field Populated bool
---@field Script string
---@field Upvalues DebuggerVariable
