---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StartupMessageService: Instance  
StartupMessageService = {}

---@return Variant
function StartupMessageService:GetStartupMessage() end

