---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StarterGui: BasePlayerGui  
StarterGui = {}
---@param coreGuiType CoreGuiType
---@return bool
function StarterGui:GetCoreGuiEnabled(coreGuiType) end

---@param parameterName string
---@param getFunction Function
function StarterGui:RegisterGetCore(parameterName, getFunction) end

---@param parameterName string
---@param setFunction Function
function StarterGui:RegisterSetCore(parameterName, setFunction) end

---@param parameterName string
---@param value Variant
function StarterGui:SetCore(parameterName, value) end

---@param coreGuiType CoreGuiType
---@param enabled bool
function StarterGui:SetCoreGuiEnabled(coreGuiType, enabled) end

---@param parameterName string
---@return Variant
function StarterGui:GetCore(parameterName) end
---@field ProcessUserInput bool
---@field ResetPlayerGuiOnSpawn bool
---@field RtlTextSupport RtlTextSupport
---@field ScreenOrientation ScreenOrientation
---@field ShowDevelopmentGui bool
---@field VirtualCursorMode VirtualCursorMode
