---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StatsItem: Instance  
StatsItem = {}

---@return double
function StatsItem:GetValue() end


---@return string
function StatsItem:GetValueString() end
---@field DisplayName string
