---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Stats: Instance  
Stats = {}

---@return string
function Stats:GetBrowserTrackerId() end

---@param tag DeveloperMemoryTag
---@return float
function Stats:GetMemoryUsageMbForTag(tag) end


---@return float
function Stats:GetTotalMemoryUsageMb() end

---@param queryType TextureQueryType
---@param pageIndex int
---@param pageSize int
---@return Dictionary
function Stats:GetPaginatedMemoryByTexture(queryType, pageIndex, pageSize) end
---@field ContactsCount int
---@field DataReceiveKbps float
---@field DataSendKbps float
---@field HeartbeatTimeMs float
---@field InstanceCount int
---@field MovingPrimitivesCount int
---@field PhysicsReceiveKbps float
---@field PhysicsSendKbps float
---@field PhysicsStepTimeMs float
---@field PrimitivesCount int
