---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum StreamingIntegrityMode  
StreamingIntegrityMode = {
  Default = 0
, Disabled = 1
, MinimumRadiusPause = 2
, PauseOutsideLoadedArea = 3
}
