---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum StudioScriptEditorColorCategories  
StudioScriptEditorColorCategories = {
  Default = 0
, Operator = 1
, Number = 2
, String = 3
, Comment = 4
, Keyword = 5
, Builtin = 6
, Method = 7
, Property = 8
, Nil = 9
, Bool = 10
, Function = 11
, Local = 12
, Self = 13
, LuauKeyword = 14
, FunctionName = 15
, TODO = 16
, Background = 17
, SelectionText = 18
, SelectionBackground = 19
, FindSelectionBackground = 20
, MatchingWordBackground = 21
, Warning = 22
, Error = 23
, Info = 24
, Hint = 25
, Whitespace = 26
, ActiveLine = 27
, DebuggerCurrentLine = 28
, DebuggerErrorLine = 29
, Ruler = 30
, Bracket = 31
, MenuPrimaryText = 32
, MenuSecondaryText = 33
, MenuSelectedText = 34
, MenuBackground = 35
, MenuSelectedBackground = 36
, MenuScrollbarBackground = 37
, MenuScrollbarHandle = 38
, MenuBorder = 39
, DocViewCodeBackground = 40
, AICOOverlayText = 41
, AICOOverlayButtonBackground = 42
, AICOOverlayButtonBackgroundHover = 43
, AICOOverlayButtonBackgroundPressed = 44
, IndentationRuler = 45
}
