---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StudioWidgetsService: Instance  
StudioWidgetsService = {}
---@param target StudioWidget
function StudioWidgetsService:ApplyFillInBox(target) end

---@param target StudioWidget
---@param rowName string?
function StudioWidgetsService:ApplyHighlight(target, rowName) end


function StudioWidgetsService:ApplyShadows() end

---@param target StudioWidget
---@param rowName string?
function StudioWidgetsService:ApplySpotlight(target, rowName) end

---@param target StudioWidget
---@param gui PluginGui
---@param attachment StudioAttachment
function StudioWidgetsService:AttachPluginGui(target, gui, attachment) end

---@param label string
---@return StudioWidget
function StudioWidgetsService:GetWidgetFromLabel(label) end

---@param gui PluginGui
---@return StudioWidget
function StudioWidgetsService:GetWidgetFromPluginGui(gui) end


function StudioWidgetsService:HideSpotlight() end

