---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StudioAssetService: Instance  
StudioAssetService = {}
---@param uploadUrl string
---@param cloneInstances Objects
---@param originalInstances Objects
function StudioAssetService:ConvertToPackageUpload(uploadUrl, cloneInstances, originalInstances) end

---@param cancelled bool
function StudioAssetService:FireOnUGCSubmitCompleted(cancelled) end

---@param instance Instance
---@param publishInfo Dictionary
function StudioAssetService:PublishPackage(instance, publishInfo) end

---@param instances Objects
---@param assetType Variant
---@param hasSubsequent bool
function StudioAssetService:ShowSaveToRoblox(instances, assetType, hasSubsequent) end

---@param assetmetadata Dictionary
---@param rootInstance Instance
---@param isConvert bool
---@param addUndoWaypoint bool
function StudioAssetService:UpdatePublishedPackage(assetmetadata, rootInstance, isConvert, addUndoWaypoint) end

---@param instances Objects
---@return string
function StudioAssetService:DEPRECATED_SerializeInstances(instances) end

---@param meshId Content
---@param textureId Content
---@param progressCallback Function
---@return Instance
function StudioAssetService:RequestAvatarAutosetupAsync(meshId, textureId, progressCallback) end

---@param instances Objects
---@param groupId int64
---@param isPackage bool
---@return string
function StudioAssetService:SerializeInstances(instances, groupId, isPackage) end

