---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StudioCallout: Instance  
StudioCallout = {}
---@param onClick Function
function StudioCallout:SetOnNextClicked(onClick) end
---@field AnchorPoint Vector2
---@field IsArrowVisible bool
---@field IsNextVisible bool
---@field RowName string
---@field Text string
---@field Title string
