---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StudioWidget: StudioObjectBase  
StudioWidget = {}
---@param width int
---@param height int
function StudioWidget:SetFixedSize(width, height) end

