---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StudioService: Instance  
StudioService = {}
---@param id int64
function StudioService:AnimationIdSelected(id) end

---@param stringToCopy string
function StudioService:CopyToClipboard(stringToCopy) end

---@param badgeId int64
---@return string
function StudioService:GetBadgeConfigureUrl(badgeId) end


---@return string
function StudioService:GetBadgeUploadUrl() end

---@param className string
---@return Dictionary
function StudioService:GetClassIcon(className) end


---@return bool
function StudioService:GetPlaceIsPersistedToCloud() end

---@param category string
---@return Dictionary
function StudioService:GetResourceByCategory(category) end


---@return string
function StudioService:GetStartupAssetId() end


---@return string
function StudioService:GetStartupPluginId() end


---@return string
function StudioService:GetTermsOfUseUrl() end


---@return int64
function StudioService:GetUserId() end

---@param origin Vector3
---@param direction Vector3
---@param raycastParams RaycastParams
---@return RaycastResult
function StudioService:GizmoRaycast(origin, direction, raycastParams) end


---@return bool
function StudioService:HasInternalPermission() end

---@param assetId int64
---@return bool
function StudioService:IsPluginInstalled(assetId) end

---@param assetId int64
---@param currentAssetVersion int64
---@return bool
function StudioService:IsPluginUpToDate(assetId, currentAssetVersion) end

---@param url string
function StudioService:OpenInBrowser_DONOTUSE(url) end

---@param closeMode StudioCloseMode
function StudioService:RequestClose(closeMode) end

---@param assetId int64
---@param state bool
function StudioService:SetPluginEnabled(assetId, state) end

---@param placeId int64
function StudioService:ShowPlaceVersionHistoryDialog(placeId) end


function StudioService:ShowPublishToRoblox() end

---@param assetId int64
function StudioService:UninstallPlugin(assetId) end


function StudioService:UpdatePluginManagement() end

---@param fileTypeFilter Array
---@return Instance
function StudioService:PromptImportFile(fileTypeFilter) end

---@param fileTypeFilter Array
---@return Objects
function StudioService:PromptImportFiles(fileTypeFilter) end

---@param assetId int64
---@param assetVersionId int64
function StudioService:TryInstallPlugin(assetId, assetVersionId) end
---@field ActiveScript Instance
---@field AlignDraggedObjects bool
---@field DraggerSolveConstraints bool
---@field DrawConstraintsOnTop bool
---@field GridSize float
---@field HoverInstance Instance
---@field InstalledPluginData string
---@field PivotSnapToGeometry bool
---@field RotateIncrement float
---@field Secrets string
---@field ShowConstraintDetails bool
---@field StudioLocaleId string
---@field UseLocalSpace bool
