---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StudioSdkService: Instance  
StudioSdkService = {}

---@return Instance
function StudioSdkService:GetSdk() end

---@param sdk Instance
function StudioSdkService:SetSdk(sdk) end

