---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum StudioScriptEditorColorPresets  
StudioScriptEditorColorPresets = {
  RobloxDefault = 0
, Extra1 = 1
, Extra2 = 2
, Custom = 3
}
