---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StudioPublishService: Instance  
StudioPublishService = {}

function StudioPublishService:ClearUploadNames() end


---@return string
function StudioPublishService:GetLocalFilePath() end


---@return string
function StudioPublishService:GetPlaceDisplayName() end

---@param universeId int64
---@param placeId int64
---@param groupId int64
---@param isPublish bool
---@param publishParameters Variant
---@param willRetryOnConflict bool
---@param allowOpeningNewPlace bool
function StudioPublishService:PublishAs(universeId, placeId, groupId, isPublish, publishParameters, willRetryOnConflict, allowOpeningNewPlace) end


function StudioPublishService:PublishThenTurnOnTeamCreate() end


function StudioPublishService:RefreshDocumentDisplayName() end

---@param shouldTurnOnTcOnPublish bool
---@param newPlaceName string
function StudioPublishService:SetTeamCreateOnPublishInfo(shouldTurnOnTcOnPublish, newPlaceName) end

---@param newName string
function StudioPublishService:SetUniverseDisplayName(newName) end

---@param placeName string
---@param universeName string
function StudioPublishService:SetUploadNames(placeName, universeName) end

---@param showGameSelect bool
---@param isPublish bool
---@param closeMode StudioCloseMode
function StudioPublishService:ShowSaveOrPublishPlaceToRoblox(showGameSelect, isPublish, closeMode) end
---@field PublishLocked bool
