---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StudioAttachment: Instance  
StudioAttachment = {}

---@field AutoHideParent bool
---@field IsArrowVisible bool
---@field Offset Vector2
---@field SourceAnchorPoint Vector2
---@field TargetAnchorPoint Vector2
