---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StudioTheme: Instance  
StudioTheme = {}
---@param styleguideitem StudioStyleGuideColor
---@param modifier StudioStyleGuideModifier
---@return Color3
function StudioTheme:GetColor(styleguideitem, modifier) end

