---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum StudioStyleGuideModifier  
StudioStyleGuideModifier = {
  Default = 0
, Selected = 1
, Pressed = 2
, Disabled = 3
, Hover = 4
}
