---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StudioDeviceEmulatorService: Instance  
StudioDeviceEmulatorService = {}

---@return int
function StudioDeviceEmulatorService:GetMaxNumTouches() end

---@param index int
---@return bool
function StudioDeviceEmulatorService:GetTouchInBounds(index) end

---@param index int
---@return Vector2
function StudioDeviceEmulatorService:GetTouchPosition(index) end

---@param deviceId string
---@param resolution Vector2
---@return bool
function StudioDeviceEmulatorService:EmulatePCDeviceWithResolution(deviceId, resolution) end


---@return string
function StudioDeviceEmulatorService:GetCurrentDeviceId() end


---@return ScreenOrientation
function StudioDeviceEmulatorService:GetCurrentOrientation() end

---@param deviceId string
---@return bool
function StudioDeviceEmulatorService:HasDeviceWithId(deviceId) end

---@param deviceId string
function StudioDeviceEmulatorService:SetCurrentDeviceId(deviceId) end

---@param orientation ScreenOrientation
function StudioDeviceEmulatorService:SetCurrentOrientation(orientation) end
---@field HasMultiTouchStarted bool
---@field IsMultiTouchEmulationOn bool
---@field IsMultiTouchEnabled bool
---@field PivotPosition Vector2
