---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StylingService: Instance  
StylingService = {}
---@param instance Instance
---@return Array
function StylingService:GetAppliedStyles(instance) end

---@param style StyleRule
---@return Dictionary
function StylingService:GetStyleInfo(style) end

---@param styleSheet StyleSheet
---@return Objects
function StylingService:GetStyleSheetDerivesChain(styleSheet) end

---@param styleSheet StyleSheet
---@return Dictionary
function StylingService:GetStyleSheetInfo(styleSheet) end

