---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StyleBase: Instance  
StyleBase = {}

---@return Objects
function StyleBase:GetStyleRules() end

---@param rule StyleRule
---@param index int?
function StyleBase:InsertStyleRule(rule, index) end

---@param rules Objects
function StyleBase:SetStyleRules(rules) end

