---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StyleSheet: StyleBase  
StyleSheet = {}

---@return Objects
function StyleSheet:GetDerives() end

---@param derives Objects
function StyleSheet:SetDerives(derives) end

