---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class StyleRule: StyleBase  
StyleRule = {}

---@return Dictionary
function StyleRule:GetProperties() end


---@return Dictionary
function StyleRule:GetPropertiesResolved() end

---@param name string
---@return Variant
function StyleRule:GetProperty(name) end

---@param name string
---@return Variant
function StyleRule:GetPropertyResolved(name) end

---@param table Dictionary
function StyleRule:SetProperties(table) end

---@param name string
---@param value Variant
function StyleRule:SetProperty(name, value) end
---@field Index int
---@field PropertiesSerialize BinaryString
---@field Selector string
---@field SelectorError string
