---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum SubscriptionState  
SubscriptionState = {
  NeverSubscribed = 0
, SubscribedWillRenew = 1
, SubscribedWillNotRenew = 2
, SubscribedRenewalPaymentPending = 3
, Expired = 4
}
