---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum SubscriptionExpirationReason  
SubscriptionExpirationReason = {
  ProductInactive = 0
, ProductDeleted = 1
, SubscriberCancelled = 2
, SubscriberRefunded = 3
, Lapsed = 4
}
