---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SurfaceGuiBase: LayerCollector  
SurfaceGuiBase = {}

---@field Active bool
---@field Adornee Instance
---@field Face NormalId
