---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SurfaceAppearance: Instance  
SurfaceAppearance = {}

---@field AlphaMode AlphaMode
---@field Color Color3
---@field ColorMap Content
---@field MetalnessMap Content
---@field NormalMap Content
---@field RoughnessMap Content
---@field TexturePack Content
