---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SurfaceGui: SurfaceGuiBase  
SurfaceGui = {}

---@field AlwaysOnTop bool
---@field Brightness float
---@field CanvasSize Vector2
---@field ClipsDescendants bool
---@field HorizontalCurvature float
---@field LightInfluence float
---@field MaxDistance float
---@field PixelsPerStud float
---@field Shape SurfaceGuiShape
---@field SizingMode SurfaceGuiSizingMode
---@field ToolPunchThroughDistance float
---@field ZOffset float
