---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SwimController: ControllerBase  
SwimController = {}

---@field AccelerationTime float
---@field PitchMaxTorque float
---@field PitchSpeedFactor float
---@field RollMaxTorque float
---@field RollSpeedFactor float
