---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class SyncScriptBuilder: ScriptBuilder  
SyncScriptBuilder = {}

---@field CompileTarget CompileTarget
---@field CoverageInfo bool
---@field DebugInfo bool
---@field PackAsSource bool
---@field RawBytecode bool
