---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TaskScheduler: Instance  
TaskScheduler = {}

---@field SchedulerDutyCycle double
---@field SchedulerRate double
---@field ThreadPoolConfig ThreadPoolConfig
---@field ThreadPoolSize int
