---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Team: Instance  
Team = {}

---@return Objects
function Team:GetPlayers() end
---@field AutoAssignable bool
---@field AutoColorCharacters bool
---@field ChildOrder int
---@field Score int
---@field TeamColor BrickColor
