---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum TeleportMethod  
TeleportMethod = {
  TeleportToSpawnByName = 0
, TeleportToPlaceInstance = 1
, TeleportToPrivateServer = 2
, TeleportPartyAsync = 3
, TeleportToVIPServer = 4
, TeleportUnknown = 5
}
