---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum TeleportResult  
TeleportResult = {
  Success = 0
, Failure = 1
, GameNotFound = 2
, GameEnded = 3
, GameFull = 4
, Unauthorized = 5
, Flooded = 6
, IsTeleporting = 7
}
