---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TeleportAsyncResult: Instance  
TeleportAsyncResult = {}

---@field PrivateServerId string
---@field ReservedServerAccessCode string
