---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TeleportOptions: Instance  
TeleportOptions = {}

---@return Variant
function TeleportOptions:GetTeleportData() end

---@param teleportData Variant
function TeleportOptions:SetTeleportData(teleportData) end
---@field ReservedServerAccessCode string
---@field ServerInstanceId string
---@field ShouldReserveServer bool
