---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum TeleportState  
TeleportState = {
  RequestedFromServer = 0
, Started = 1
, WaitingForServer = 2
, Failed = 3
, InProgress = 4
}
