---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TerrainRegion: Instance  
TerrainRegion = {}
---@param rotation CFrame
---@param size Vector3
function TerrainRegion:ApplyTransform(rotation, size) end

---@param rotation CFrame
---@param size Vector3
---@param region Region3int16
---@return TerrainRegion
function TerrainRegion:ApplyTransformSubregion(rotation, size, region) end


function TerrainRegion:ConvertToSmooth() end


---@return Array
function TerrainRegion:GetRegionWireframe() end
---@field ExtentsMax Vector3int16
---@field ExtentsMin Vector3int16
---@field GridV3 BinaryString
---@field IsSmooth bool
---@field SizeInCells Vector3
---@field SmoothGrid BinaryString
