---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TerrainDetail: Instance  
TerrainDetail = {}

---@field ColorMap Content
---@field Face TerrainFace
---@field MaterialPattern MaterialPattern
---@field MetalnessMap Content
---@field NormalMap Content
---@field RoughnessMap Content
---@field StudsPerTile float
---@field TexturePack Content
