---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum TerrainAcquisitionMethod  
TerrainAcquisitionMethod = {
  None = 0
, Legacy = 1
, Template = 2
, Generate = 3
, Import = 4
, Convert = 5
, EditAddTool = 6
, EditSeaLevelTool = 7
, EditReplaceTool = 8
, RegionFillTool = 9
, RegionPasteTool = 10
, Other = 11
}
