---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TestService: Instance  
TestService = {}
---@param condition bool
---@param description string
---@param source Instance
---@param line int
function TestService:Check(condition, description, source, line) end

---@param text string
---@param source Instance
---@param line int
function TestService:Checkpoint(text, source, line) end


function TestService:Done() end

---@param description string
---@param source Instance
---@param line int
function TestService:Error(description, source, line) end

---@param description string
---@param source Instance
---@param line int
function TestService:Fail(description, source, line) end

---@param text string
---@param source Instance
---@param line int
function TestService:Message(text, source, line) end

---@param condition bool
---@param description string
---@param source Instance
---@param line int
function TestService:Require(condition, description, source, line) end


---@return Dictionary
function TestService:ScopeTime() end

---@param condition bool
---@param description string
---@param source Instance
---@param line int
function TestService:Warn(condition, description, source, line) end

---@param name string
---@return bool
function TestService:isFeatureEnabled(name) end


function TestService:Run() end
---@field AutoRuns bool
---@field Description string
---@field ErrorCount int
---@field ExecuteWithStudioRun bool
---@field Is30FpsThrottleEnabled bool
---@field IsPhysicsEnvironmentalThrottled bool
---@field IsSleepAllowed bool
---@field NumberOfPlayers int
---@field SimulateSecondsLag double
---@field TestCount int
---@field Timeout double
---@field WarnCount int
