---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TextChatMessage: Instance  
TextChatMessage = {}

---@field BubbleChatMessageProperties BubbleChatMessageProperties
---@field MessageId string
---@field Metadata string
---@field PrefixText string
---@field Status TextChatMessageStatus
---@field Text string
---@field TextChannel TextChannel
---@field TextSource TextSource
---@field Timestamp DateTime
---@field Translation string
