---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TextureGenerationPartGroup: Instance  
TextureGenerationPartGroup = {}

---@return Objects
function TextureGenerationPartGroup:GetInstances() end


---@return string
function TextureGenerationPartGroup:GetMeshIdsHash() end

