---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TextFilterResult: Instance  
TextFilterResult = {}
---@param toUserId int64
---@return string
function TextFilterResult:GetChatForUserAsync(toUserId) end


---@return string
function TextFilterResult:GetNonChatStringForBroadcastAsync() end

---@param toUserId int64
---@return string
function TextFilterResult:GetNonChatStringForUserAsync(toUserId) end

