---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum TextureQueryType  
TextureQueryType = {
  NonHumanoid = 0
, NonHumanoidOrphaned = 1
, Humanoid = 2
, HumanoidOrphaned = 3
}
