---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TextBox: GuiObject  
TextBox = {}

function TextBox:CaptureFocus() end


---@return bool
function TextBox:IsFocused() end

---@param submitted bool
function TextBox:ReleaseFocus(submitted) end


function TextBox:ResetKeyboardMode() end

---@param text string
function TextBox:SetTextFromInput(text) end
---@field ClearTextOnFocus bool
---@field Confidential bool
---@field ContentText string
---@field CursorPosition int
---@field Font Font
---@field FontFace Font
---@field FontSize FontSize
---@field LineHeight float
---@field LocalizationMatchIdentifier string
---@field LocalizationMatchedSourceText string
---@field ManualFocusRelease bool
---@field MaxVisibleGraphemes int
---@field MultiLine bool
---@field OpenTypeFeatures string
---@field OpenTypeFeaturesError string
---@field OverlayNativeInput bool
---@field PlaceholderColor3 Color3
---@field PlaceholderText string
---@field ReturnKeyType ReturnKeyType
---@field RichText bool
---@field SelectionStart int
---@field ShowNativeInput bool
---@field Text string
---@field TextBounds Vector2
---@field TextColor BrickColor
---@field TextColor3 Color3
---@field TextDirection TextDirection
---@field TextEditable bool
---@field TextFits bool
---@field TextInputType TextInputType
---@field TextScaled bool
---@field TextSize float
---@field TextStrokeColor3 Color3
---@field TextStrokeTransparency float
---@field TextTransparency float
---@field TextTruncate TextTruncate
---@field TextWrap bool
---@field TextWrapped bool
---@field TextXAlignment TextXAlignment
---@field TextYAlignment TextYAlignment
