---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Texture: Decal  
Texture = {}

---@field OffsetStudsU float
---@field OffsetStudsV float
---@field StudsPerTileU float
---@field StudsPerTileV float
