---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TextureGenerationUnwrappingRequest: Instance  
TextureGenerationUnwrappingRequest = {}
---@param partGroup TextureGenerationPartGroup
---@return TextureGenerationPartGroup
function TextureGenerationUnwrappingRequest:ApplyToDataModel(partGroup) end


---@return TextureGenerationPartGroup
function TextureGenerationUnwrappingRequest:GetPartGroup() end

