---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TextChatMessageProperties: Instance  
TextChatMessageProperties = {}

---@field PrefixText string
---@field Text string
---@field Translation string
