---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TextFilterTranslatedResult: Instance  
TextFilterTranslatedResult = {}
---@param locale string
---@return TextFilterResult
function TextFilterTranslatedResult:GetTranslationForLocale(locale) end


---@return Dictionary
function TextFilterTranslatedResult:GetTranslations() end
---@field SourceLanguage string
---@field SourceText TextFilterResult
