---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TextChannel: Instance  
TextChannel = {}
---@param systemMessage string
---@param metadata string
---@return TextChatMessage
function TextChannel:DisplaySystemMessage(systemMessage, metadata) end

---@param userId int64
---@return Tuple
function TextChannel:AddUserAsync(userId) end

---@param message string
---@param metadata string
---@return TextChatMessage
function TextChannel:SendAsync(message, metadata) end

