---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TextChatCommand: Instance  
TextChatCommand = {}

---@field AutocompleteVisible bool
---@field Enabled bool
---@field PrimaryAlias string
---@field SecondaryAlias string
