---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum TextChatMessageStatus  
TextChatMessageStatus = {
  Unknown = 1
, Success = 2
, Sending = 3
, TextFilterFailed = 4
, Floodchecked = 5
, InvalidPrivacySettings = 6
, InvalidTextChannelPermissions = 7
, MessageTooLong = 8
}
