---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ThreadState: Instance  
ThreadState = {}
---@param index int
---@return Instance
function ThreadState:GetFrame(index) end
---@field FrameCount int
---@field Populated bool
---@field ThreadId int
---@field ThreadName string
