---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ToastNotificationService: Instance  
ToastNotificationService = {}
---@param notificationId string
function ToastNotificationService:HideNotification(notificationId) end

---@param message string
---@param notificationId string
function ToastNotificationService:ShowNotification(message, notificationId) end

