---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Tool: BackpackItem  
Tool = {}

function Tool:Activate() end


function Tool:Deactivate() end
---@field CanBeDropped bool
---@field Enabled bool
---@field Grip CFrame
---@field GripForward Vector3
---@field GripPos Vector3
---@field GripRight Vector3
---@field GripUp Vector3
---@field ManualActivationOnly bool
---@field RequiresHandle bool
---@field ToolTip string
