---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TorsionSpringConstraint: Constraint  
TorsionSpringConstraint = {}

---@field Coils float
---@field CurrentAngle float
---@field Damping float
---@field LimitEnabled bool
---@field LimitsEnabled bool
---@field MaxAngle float
---@field MaxTorque float
---@field Radius float
---@field Restitution float
---@field Stiffness float
