---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum TouchMovementMode  
TouchMovementMode = {
  Default = 0
, Thumbstick = 1
, DPad = 2
, Thumbpad = 3
, ClickToMove = 4
, DynamicThumbstick = 5
}
