---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TracerService: Instance  
TracerService = {}
---@param spanId string
function TracerService:FinishSpan(spanId) end

---@param name string
---@param parentId string
---@return string
function TracerService:StartSpan(name, parentId) end

