---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum TrackerExtrapolationFlagMode  
TrackerExtrapolationFlagMode = {
  Auto = 3
, ForceDisabled = 0
, ExtrapolateFacsAndPose = 1
, ExtrapolateFacsOnly = 2
}
