---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TrackerLodController: Instance  
TrackerLodController = {}

---@return int
function TrackerLodController:getExtrapolation() end


---@return int
function TrackerLodController:getVideoLod() end


---@return bool
function TrackerLodController:isAudioEnabled() end


---@return bool
function TrackerLodController:isVideoEnabled() end
---@field AudioMode TrackerLodFlagMode
---@field VideoExtrapolationMode TrackerExtrapolationFlagMode
---@field VideoLodMode TrackerLodValueMode
---@field VideoMode TrackerLodFlagMode
