---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum TrackerFaceTrackingStatus  
TrackerFaceTrackingStatus = {
  FaceTrackingSuccess = 0
, FaceTrackingNoFaceFound = 1
, FaceTrackingUnknown = 2
, FaceTrackingLost = 3
, FaceTrackingHasTrackingError = 4
, FaceTrackingIsOccluded = 5
, FaceTrackingUninitialized = 6
}
