---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum TrackerError  
TrackerError = {
  Ok = 0
, NoService = 1
, InitFailed = 2
, NoVideo = 3
, VideoError = 4
, VideoNoPermission = 5
, VideoUnsupported = 6
, NoAudio = 7
, AudioError = 8
, AudioNoPermission = 9
, UnsupportedDevice = 10
}
