---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Trail: Instance  
Trail = {}

function Trail:Clear() end
---@field Attachment0 Attachment
---@field Attachment1 Attachment
---@field Brightness float
---@field Color ColorSequence
---@field Enabled bool
---@field FaceCamera bool
---@field Lifetime float
---@field LightEmission float
---@field LightInfluence float
---@field LocalTransparencyModifier float
---@field MaxLength float
---@field MinLength float
---@field Texture Content
---@field TextureLength float
---@field TextureMode TextureMode
---@field Transparency NumberSequence
---@field WidthScale NumberSequence
