---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Translator: Instance  
Translator = {}
---@param key string
---@param args Variant
---@return string
function Translator:FormatByKey(key, args) end

---@param context Instance
---@param text string
---@return string
function Translator:RobloxOnlyTranslate(context, text) end

---@param context Instance
---@param text string
---@return string
function Translator:Translate(context, text) end
---@field LocaleId string
