---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TremoloSoundEffect: SoundEffect  
TremoloSoundEffect = {}

---@field Depth float
---@field Duty float
---@field Frequency float
