---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TriangleMeshPart: BasePart  
TriangleMeshPart = {}

---@field AeroMeshData SharedString
---@field CollisionFidelity CollisionFidelity
---@field FluidFidelity FluidFidelity
---@field FluidFidelityInternal FluidFidelity
---@field MeshSize Vector3
---@field PhysicalConfigData SharedString
---@field UnscaledCofm Vector3
---@field UnscaledVolInertiaDiags Vector3
---@field UnscaledVolInertiaOffDiags Vector3
---@field UnscaledVolume float
