---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TutorialService: Instance  
TutorialService = {}

---@return string
function TutorialService:GetMainViewSessionId() end

---@param label string
---@return StudioWidget
function TutorialService:GetStudioWidgetFromLabel(label) end


---@return string
function TutorialService:GetTutorialIDToLaunch() end


---@return bool
function TutorialService:HasUserCompletedTutorial() end

---@param commaSeparatedNames string
---@return bool
function TutorialService:HideWidgets(commaSeparatedNames) end


function TutorialService:PromptClosePlace() end

---@param completed bool
function TutorialService:SetTutorialCompletionStatus(completed) end


---@return bool
function TutorialService:ShouldLaunchTutorial() end

---@param commaSeparatedNames string
---@return bool
function TutorialService:ShowWidgets(commaSeparatedNames) end

