---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TweenBase: Instance  
TweenBase = {}

function TweenBase:Cancel() end


function TweenBase:Pause() end


function TweenBase:Play() end
---@field PlaybackState PlaybackState
