---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class TweenService: Instance  
TweenService = {}
---@param instance Instance
---@param tweenInfo TweenInfo
---@param propertyTable Dictionary
---@return Tween
function TweenService:Create(instance, tweenInfo, propertyTable) end

---@param alpha float
---@param easingStyle EasingStyle
---@param easingDirection EasingDirection
---@return float
function TweenService:GetValue(alpha, easingStyle, easingDirection) end

