---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UIAspectRatioConstraint: UIConstraint  
UIAspectRatioConstraint = {}

---@field AspectRatio float
---@field AspectType AspectType
---@field DominantAxis DominantAxis
