---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum UIDragDetectorDragStyle  
UIDragDetectorDragStyle = {
  TranslatePlane = 0
, TranslateLine = 1
, Rotate = 2
, Scriptable = 3
}
