---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum UIDragDetectorResponseStyle  
UIDragDetectorResponseStyle = {
  Offset = 0
, Scale = 1
, CustomOffset = 2
, CustomScale = 3
}
