---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UIDragDetector: UIComponent  
UIDragDetector = {}
---@param priority int
---@param function Function
---@return RBXScriptConnection
function UIDragDetector:AddConstraintFunction(priority, function) end


---@return UDim2
function UIDragDetector:GetReferencePosition() end


---@return float
function UIDragDetector:GetReferenceRotation() end

---@param function Function
function UIDragDetector:SetDragStyleFunction(function) end
---@field ActivatedCursorIcon Content
---@field BoundingUI GuiBase2d
---@field CursorIcon Content
---@field DragAxis Vector2
---@field DragRelativity UIDragDetectorDragRelativity
---@field DragRotation float
---@field DragSpace UIDragDetectorDragSpace
---@field DragStyle UIDragDetectorDragStyle
---@field DragUDim2 UDim2
---@field Enabled bool
---@field MaxDragAngle float
---@field MaxDragTranslation UDim2
---@field MinDragAngle float
---@field MinDragTranslation UDim2
---@field ReferenceUIInstance GuiObject
---@field ResponseStyle UIDragDetectorResponseStyle
