---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UIFlexItem: UIComponent  
UIFlexItem = {}

---@field FlexMode UIFlexMode
---@field GrowRatio float
---@field ItemLineAlignment ItemLineAlignment
---@field ShrinkRatio float
