---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UIGradient: UIComponent  
UIGradient = {}

---@field Color ColorSequence
---@field Enabled bool
---@field Offset Vector2
---@field Rotation float
---@field Transparency NumberSequence
