---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UIGridLayout: UIGridStyleLayout  
UIGridLayout = {}

---@field AbsoluteCellCount Vector2
---@field AbsoluteCellSize Vector2
---@field CellPadding UDim2
---@field CellSize UDim2
---@field FillDirectionMaxCells int
---@field StartCorner StartCorner
