---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UIGridStyleLayout: UILayout  
UIGridStyleLayout = {}

function UIGridStyleLayout:ApplyLayout() end

---@param function Function
function UIGridStyleLayout:SetCustomSortFunction(function) end
---@field AbsoluteContentSize Vector2
---@field FillDirection FillDirection
---@field HorizontalAlignment HorizontalAlignment
---@field SortOrder SortOrder
---@field VerticalAlignment VerticalAlignment
