---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UIListLayout: UIGridStyleLayout  
UIListLayout = {}

---@field HorizontalFlex UIFlexAlignment
---@field HorizontalPadding UDim
---@field ItemLineAlignment ItemLineAlignment
---@field Padding UDim
---@field VerticalFlex UIFlexAlignment
---@field VerticalPadding UDim
---@field Wraps bool
