---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UIPageLayout: UIGridStyleLayout  
UIPageLayout = {}
---@param page Instance
function UIPageLayout:JumpTo(page) end

---@param index int
function UIPageLayout:JumpToIndex(index) end


function UIPageLayout:Next() end


function UIPageLayout:Previous() end
---@field Animated bool
---@field Circular bool
---@field CurrentPage GuiObject
---@field EasingDirection EasingDirection
---@field EasingStyle EasingStyle
---@field GamepadInputEnabled bool
---@field Padding UDim
---@field ScrollWheelInputEnabled bool
---@field TouchInputEnabled bool
---@field TweenTime float
