---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UIPadding: UIComponent  
UIPadding = {}

---@field PaddingBottom UDim
---@field PaddingLeft UDim
---@field PaddingRight UDim
---@field PaddingTop UDim
