---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UIStroke: UIComponent  
UIStroke = {}

---@field ApplyStrokeMode ApplyStrokeMode
---@field Color Color3
---@field Enabled bool
---@field LineJoinMode LineJoinMode
---@field Thickness float
---@field Transparency float
