---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UITableLayout: UIGridStyleLayout  
UITableLayout = {}

---@field FillEmptySpaceColumns bool
---@field FillEmptySpaceRows bool
---@field MajorAxis TableMajorAxis
---@field Padding UDim2
