---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UniversalConstraint: Constraint  
UniversalConstraint = {}

---@field LimitsEnabled bool
---@field MaxAngle float
---@field Radius float
---@field Restitution float
