---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UnreliableRemoteEvent: BaseRemoteEvent  
UnreliableRemoteEvent = {}
---@param arguments Tuple
function UnreliableRemoteEvent:FireAllClients(arguments) end

---@param player Player
---@param arguments Tuple
function UnreliableRemoteEvent:FireClient(player, arguments) end

---@param arguments Tuple
function UnreliableRemoteEvent:FireServer(arguments) end

