---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UnvalidatedAssetService: Instance  
UnvalidatedAssetService = {}
---@param userId int64
---@param id int64
---@param lookAt Vector3
---@param camPos Vector3
---@param usage string
function UnvalidatedAssetService:AppendTempAssetId(userId, id, lookAt, camPos, usage) end

---@param userId int64
---@param id int64
---@param lookAt Vector3
---@param camPos Vector3
---@return bool
function UnvalidatedAssetService:AppendVantagePoint(userId, id, lookAt, camPos) end

---@param userId int64
---@param tempId int64
---@param assetId int64
---@return bool
function UnvalidatedAssetService:UpgradeTempAssetId(userId, tempId, assetId) end
---@field CachedData string
