---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UserService: Instance  
UserService = {}
---@param userIds Array
---@return Array
function UserService:GetUserInfosByUserIdsAsync(userIds) end

