---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class UserSettings: GenericSettings  
UserSettings = {}
---@param name string
---@return bool
function UserSettings:IsUserFeatureEnabled(name) end


function UserSettings:Reset() end


function UserSettings:SaveState() end

