---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class VectorForce: Constraint  
VectorForce = {}

---@field ApplyAtCenterOfMass bool
---@field Force Vector3
---@field RelativeTo ActuatorRelativeTo
