---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Vector3Curve: Instance  
Vector3Curve = {}
---@param time float
---@return Array
function Vector3Curve:GetValueAtTime(time) end


---@return FloatCurve
function Vector3Curve:X() end


---@return FloatCurve
function Vector3Curve:Y() end


---@return FloatCurve
function Vector3Curve:Z() end

