---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class VehicleSeat: BasePart  
VehicleSeat = {}
---@param humanoid Instance
function VehicleSeat:Sit(humanoid) end
---@field AreHingesDetected int
---@field Disabled bool
---@field HeadsUpDisplay bool
---@field MaxSpeed float
---@field Occupant Humanoid
---@field Steer int
---@field SteerFloat float
---@field Throttle int
---@field ThrottleFloat float
---@field Torque float
---@field TurnSpeed float
