---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class VelocityMotor: JointInstance  
VelocityMotor = {}

---@field CurrentAngle float
---@field DesiredAngle float
---@field Hole Hole
---@field MaxVelocity float
