---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class VersionControlService: Instance  
VersionControlService = {}

---@field ScriptCollabEnabled bool
---@field ScriptCollabVersionHistoryEnabled bool
