---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum VibrationMotor  
VibrationMotor = {
  Large = 0
, Small = 1
, LeftTrigger = 2
, RightTrigger = 3
, LeftHand = 4
, RightHand = 5
}
