---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class VideoDeviceInput: Instance  
VideoDeviceInput = {}

---@field Active bool
---@field CameraId string
---@field CaptureQuality VideoDeviceCaptureQuality
---@field IsReady bool
