---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class VideoCaptureService: Instance  
VideoCaptureService = {}

---@return Map
function VideoCaptureService:GetCameraDevices() end
---@field Active bool
---@field CameraID string
