---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class ViewportFrame: GuiObject  
ViewportFrame = {}

---@return Content
function ViewportFrame:CaptureSnapshotAsync() end
---@field Ambient Color3
---@field CameraCFrame CFrame
---@field CameraFieldOfView float
---@field CurrentCamera Camera
---@field ImageColor3 Color3
---@field ImageTransparency float
---@field IsMirrored bool
---@field LightColor Color3
---@field LightDirection Vector3
