---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class VirtualUser: Instance  
VirtualUser = {}
---@param position Vector2
---@param camera CFrame
function VirtualUser:Button1Down(position, camera) end

---@param position Vector2
---@param camera CFrame
function VirtualUser:Button1Up(position, camera) end

---@param position Vector2
---@param camera CFrame
function VirtualUser:Button2Down(position, camera) end

---@param position Vector2
---@param camera CFrame
function VirtualUser:Button2Up(position, camera) end


function VirtualUser:CaptureController() end

---@param position Vector2
---@param camera CFrame
function VirtualUser:ClickButton1(position, camera) end

---@param position Vector2
---@param camera CFrame
function VirtualUser:ClickButton2(position, camera) end

---@param position Vector2
---@param camera CFrame
function VirtualUser:MoveMouse(position, camera) end

---@param key string
function VirtualUser:SetKeyDown(key) end

---@param key string
function VirtualUser:SetKeyUp(key) end


function VirtualUser:StartRecording() end


---@return string
function VirtualUser:StopRecording() end

---@param key string
function VirtualUser:TypeKey(key) end

