---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class VirtualInputManager: Instance  
VirtualInputManager = {}

function VirtualInputManager:Dump() end

---@param objectId int
---@param keyCode KeyCode
---@param x float
---@param y float
---@param z float
function VirtualInputManager:HandleGamepadAxisInput(objectId, keyCode, x, y, z) end

---@param deviceId int
---@param keyCode KeyCode
---@param buttonState int
function VirtualInputManager:HandleGamepadButtonInput(deviceId, keyCode, buttonState) end

---@param deviceId int
function VirtualInputManager:HandleGamepadConnect(deviceId) end

---@param deviceId int
function VirtualInputManager:HandleGamepadDisconnect(deviceId) end

---@param x float
---@param y float
---@param z float
function VirtualInputManager:SendAccelerometerEvent(x, y, z) end

---@param x float
---@param y float
---@param z float
function VirtualInputManager:SendGravityEvent(x, y, z) end

---@param quatX float
---@param quatY float
---@param quatZ float
---@param quatW float
function VirtualInputManager:SendGyroscopeEvent(quatX, quatY, quatZ, quatW) end

---@param isPressed bool
---@param keyCode KeyCode
---@param isRepeatedKey bool
---@param layerCollector Instance
function VirtualInputManager:SendKeyEvent(isPressed, keyCode, isRepeatedKey, layerCollector) end

---@param x int
---@param y int
---@param mouseButton int
---@param isDown bool
---@param layerCollector Instance
---@param repeatCount int
function VirtualInputManager:SendMouseButtonEvent(x, y, mouseButton, isDown, layerCollector, repeatCount) end

---@param x float
---@param y float
---@param layerCollector Instance
function VirtualInputManager:SendMouseMoveEvent(x, y, layerCollector) end

---@param x float
---@param y float
---@param isForwardScroll bool
---@param layerCollector Instance
function VirtualInputManager:SendMouseWheelEvent(x, y, isForwardScroll, layerCollector) end

---@param str string
---@param layerCollector Instance
function VirtualInputManager:SendTextInputCharacterEvent(str, layerCollector) end

---@param touchId int64
---@param state int
---@param x float
---@param y float
function VirtualInputManager:SendTouchEvent(touchId, state, x, y) end

---@param inputTypesToIgnore Variant
function VirtualInputManager:SetInputTypesToIgnore(inputTypesToIgnore) end

---@param fileName string
function VirtualInputManager:StartPlaying(fileName) end

---@param string string
function VirtualInputManager:StartPlayingJSON(string) end


function VirtualInputManager:StartRecording() end


function VirtualInputManager:StopPlaying() end


function VirtualInputManager:StopRecording() end

---@param namespace string
---@param detail string
---@param detailType string
function VirtualInputManager:sendRobloxEvent(namespace, detail, detailType) end

---@param themeName string
function VirtualInputManager:sendThemeChangeEvent(themeName) end


function VirtualInputManager:WaitForInputEventsProcessed() end
---@field AdditionalLuaState string
