---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class VisualizationMode: Instance  
VisualizationMode = {}

---@field Enabled bool
---@field Title string
---@field ToolTip string
