---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum VoiceChatState  
VoiceChatState = {
  Idle = 0
, Joining = 1
, JoiningRetry = 2
, Joined = 3
, Leaving = 4
, Ended = 5
, Failed = 6
}
