---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class VRService: Instance  
VRService = {}
---@param pad VRTouchpad
---@return VRTouchpadMode
function VRService:GetTouchpadMode(pad) end

---@param type UserCFrame
---@return CFrame
function VRService:GetUserCFrame(type) end

---@param type UserCFrame
---@return bool
function VRService:GetUserCFrameEnabled(type) end


---@return bool
function VRService:IsMaquettes() end


---@return bool
function VRService:IsVRAppBuild() end


function VRService:RecenterUserHeadCFrame() end

---@param cframe CFrame
---@param inputUserCFrame UserCFrame
function VRService:RequestNavigation(cframe, inputUserCFrame) end

---@param pad VRTouchpad
---@param mode VRTouchpadMode
function VRService:SetTouchpadMode(pad, mode) end
---@field AutomaticScaling VRScaling
---@field AvatarGestures bool
---@field DidPointerHit bool
---@field FadeOutViewOnCollision bool
---@field GuiInputUserCFrame UserCFrame
---@field LaserDistance float
---@field PointerHitCFrame CFrame
---@field QuestASWState bool
---@field QuestDisplayRefreshRate float
---@field ThirdPersonFollowCamEnabled bool
---@field VRDeviceAvailable bool
---@field VRDeviceName string
---@field VREnabled bool
---@field VRSessionState VRSessionState
