---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class WeldConstraint: Instance  
WeldConstraint = {}

---@field Active bool
---@field CFrame0 CFrame
---@field CFrame1 CFrame
---@field Enabled bool
---@field Part0 BasePart
---@field Part0Internal BasePart
---@field Part1 BasePart
---@field Part1Internal BasePart
---@field State int
