---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Wire: Instance  
Wire = {}

---@field Connected bool
---@field SourceInstance Instance
---@field SourceName string
---@field TargetInstance Instance
---@field TargetName string
