---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class Workspace: WorldRoot  
Workspace = {}
---@param objects Objects
function Workspace:BreakJoints(objects) end

---@param gravity float
---@param jumpPower float
---@param walkSpeed float
---@return float
function Workspace:CalculateJumpDistance(gravity, jumpPower, walkSpeed) end

---@param gravity float
---@param jumpPower float
---@return float
function Workspace:CalculateJumpHeight(gravity, jumpPower) end

---@param gravity float
---@param jumpHeight float
---@return float
function Workspace:CalculateJumpPower(gravity, jumpHeight) end


---@return bool
function Workspace:ExperimentalSolverIsEnabled() end


---@return int
function Workspace:GetNumAwakeParts() end


---@return int
function Workspace:GetPhysicsThrottling() end


---@return double
function Workspace:GetRealPhysicsFPS() end


---@return double
function Workspace:GetServerTimeNow() end

---@param objects Objects
---@param jointType JointCreationMode
function Workspace:JoinToOutsiders(objects, jointType) end

---@param objects Objects
function Workspace:MakeJoints(objects) end


---@return bool
function Workspace:PGSIsEnabled() end

---@param value AvatarUnificationMode
function Workspace:SetAvatarUnificationMode(value) end

---@param value MeshPartHeadsAndAccessories
function Workspace:SetMeshPartHeadsAndAccessories(value) end

---@param value bool
function Workspace:SetPhysicsThrottleEnabled(value) end

---@param objects Objects
function Workspace:UnjoinFromOutsiders(objects) end


function Workspace:ZoomToExtents() end
---@field AirDensity float
---@field AllowThirdPartySales bool
---@field AvatarUnificationMode AvatarUnificationMode
---@field CSGAsyncDynamicCollision CSGAsyncDynamicCollision
---@field ClientAnimatorThrottling ClientAnimatorThrottlingMode
---@field CollisionGroupData BinaryString
---@field CollisionGroups string
---@field CurrentCamera Camera
---@field DataModelPlaceVersion int
---@field DecreaseMinimumPartDensityMode DecreaseMinimumPartDensityMode
---@field DistributedGameTime double
---@field ExplicitAutoJoints bool
---@field FallenPartsDestroyHeight float
---@field FilteringEnabled bool
---@field FluidForces FluidForces
---@field GlobalWind Vector3
---@field Gravity float
---@field IKControlConstraintSupport IKControlConstraintSupport
---@field InsertPoint Vector3
---@field InterpolationThrottling InterpolationThrottlingMode
---@field MeshPartHeadsAndAccessories MeshPartHeadsAndAccessories
---@field ModelStreamingBehavior ModelStreamingBehavior
---@field MoverConstraintRootBehavior MoverConstraintRootBehaviorMode
---@field PhysicsSteppingMethod PhysicsSteppingMethod
---@field PlayerCharacterDestroyBehavior PlayerCharacterDestroyBehavior
---@field PrimalPhysicsSolver PrimalPhysicsSolver
---@field RejectCharacterDeletions RejectCharacterDeletions
---@field RenderingCacheOptimizations RenderingCacheOptimizationMode
---@field ReplicateInstanceDestroySetting ReplicateInstanceDestroySetting
---@field Retargeting AnimatorRetargetingMode
---@field SignalBehavior SignalBehavior
---@field SignalBehavior2 SignalBehavior
---@field StreamOutBehavior StreamOutBehavior
---@field StreamingEnabled bool
---@field StreamingIntegrityMode StreamingIntegrityMode
---@field StreamingMinRadius int
---@field StreamingPauseMode StreamingPauseMode
---@field StreamingTargetRadius int
---@field Terrain Terrain
---@field TerrainWeldsFixed bool
---@field TouchesUseCollisionGroups bool
