---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class WrapLayer: BaseWrap  
WrapLayer = {}

---@field AutoSkin WrapLayerAutoSkin
---@field BindOffset CFrame
---@field Color Color3
---@field DebugMode WrapLayerDebugMode
---@field Enabled bool
---@field Order int
---@field Puffiness float
---@field ReferenceMeshId Content
---@field ReferenceOrigin CFrame
---@field ReferenceOriginWorld CFrame
---@field ShrinkFactor float
---@field TemporaryReferenceId Content
