---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@class WrapTarget: BaseWrap  
WrapTarget = {}

---@field Color Color3
---@field DebugMode WrapTargetDebugMode
---@field Stiffness float
