---@meta
--- This file is autogenerated by lite-xl-robolox-luacats.

---@enum WrapTargetDebugMode  
WrapTargetDebugMode = {
  None = 0
, TargetCageOriginal = 1
, TargetCageCompressed = 2
, TargetCageInterface = 3
, TargetLayerCageOriginal = 4
, TargetLayerCageCompressed = 5
, TargetLayerInterface = 6
, Rbf = 7
, OuterCageDetail = 8
}
